<?xml version="1.0" encoding="utf-8"?><Database Name="Realty" Class="AhmedabadMarathonRegistrationDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=10.0.200.119;Initial Catalog=Realty;Persist Security Info=True;User ID=sitecoreuser" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="RealtyConnectionString4" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AhmedabadMarathonPaymentHistory" Member="AhmedabadMarathonPaymentHistories">
    <Type Name="AhmedabadMarathonPaymentHistory">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AccountNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OrderId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Amount" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RequestTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Checksumkey" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CurrencyType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GatewayType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="msg" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AdvanceAmmount" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PaymentType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TransactionId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Responsecode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ResponseTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PaymentRef" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ResponseMsg" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PaymentMode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Created_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Modified_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ISU_UPDATE_FLAG" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="ISU_UPDATE_DATETIME" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ISU_UPDATE_MESSAGE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AhmedabadMarathonTrainingOption" Member="AhmedabadMarathonTrainingOptions">
    <Type Name="AhmedabadMarathonTrainingOption">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RegistrationId" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Race_Category" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="First_Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Last_Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Email_Id" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Contact_Number" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FormSubmitOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TrackingOption" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AhmedabadMarathonTrainingRun" Member="AhmedabadMarathonTrainingRuns">
    <Type Name="AhmedabadMarathonTrainingRun">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Race_Category" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="First_Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Last_Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Email_Id" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Contact_Number" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FormSubmitOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TrackingOption" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AhmedabadMarathonOTP" Member="AhmedabadMarathonOTPs">
    <Type Name="AhmedabadMarathonOTP">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmailId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OTP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Modified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CurrentSession" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Count" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ValidateOTPCount" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MarathonCity" Member="MarathonCities">
    <Type Name="MarathonCity">
      <Column Name="Cityid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CityName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="stateid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="MarathonState_MarathonCity" Member="MarathonState" ThisKey="stateid" OtherKey="stateid" Type="MarathonState" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MarathonStates" Member="MarathonStates">
    <Type Name="MarathonState">
      <Column Name="stateid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="statename" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="MarathonState_MarathonCity" Member="MarathonCities" ThisKey="stateid" OtherKey="stateid" Type="MarathonCity" />
    </Type>
  </Table>
  <Table Name="dbo.AhmedabadMarathonRegistration" Member="AhmedabadMarathonRegistrations">
    <Type Name="AhmedabadMarathonRegistration">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RaceDistance" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RaceAmount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ReferenceCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DateofBirth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ContactNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Nationality" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="TShirtSize" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NamePreferredonBIB" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IdentityProofType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IdentityProofNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IDCardAttachment" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Pincode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EmergencyContactName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EmergencyContactRelationship" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EmergencyContactNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BloodGroup" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ChronicIllness" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HeartAilment" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RespiratoryAilment" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AnyFaintingEpisodesinPast" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AnyOtherAilment" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AnyKnownAllergies" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PayrollCompany" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EmployeeID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UnitStation" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ShantigramIdProof" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DiscountRate" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FinalAmount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="PaymentStatus" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AmountReceived" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="RegistrationStatus" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FormSubmitOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Age" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RaceCertificate" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DetailsOfFullHalfMarathon" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DefencePersonnel" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RegistrationType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PayableBy" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Updated" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RunType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RunMode" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="RunDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TimeSlot" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Vaccinationted" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="VaccinationCertificate" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="RaceLocation" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BIBNumber" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="IsRaceDistanceChanged" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DonationAmount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="PANNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TaxExemptionCertificate" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TaxExemptionCause" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="EmployeeEmailId" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AhmedabadMarathonDonation" Member="AhmedabadMarathonDonations">
    <Type Name="AhmedabadMarathonDonation">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AffiliateCode" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="EmailId" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CauseTitle" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="FormSubmitOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PaymentStatus" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MobileNo" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PAN_No" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TaxExemptionCause" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
</Database>