//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.Ports.Website.ExpectedAICTPLServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExpectedAICTPLServiceReference.get_expected_southbasinSoap")]
    public interface get_expected_southbasinSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_expected_southbasin_data", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet get_expected_southbasin_data();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_expected_southbasin_data", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> get_expected_southbasin_dataAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface get_expected_southbasinSoapChannel : Sitecore.Ports.Website.ExpectedAICTPLServiceReference.get_expected_southbasinSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class get_expected_southbasinSoapClient : System.ServiceModel.ClientBase<Sitecore.Ports.Website.ExpectedAICTPLServiceReference.get_expected_southbasinSoap>, Sitecore.Ports.Website.ExpectedAICTPLServiceReference.get_expected_southbasinSoap {
        
        public get_expected_southbasinSoapClient() {
        }
        
        public get_expected_southbasinSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public get_expected_southbasinSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public get_expected_southbasinSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public get_expected_southbasinSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet get_expected_southbasin_data() {
            return base.Channel.get_expected_southbasin_data();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> get_expected_southbasin_dataAsync() {
            return base.Channel.get_expected_southbasin_dataAsync();
        }
    }
}
