<?xml version="1.0" encoding="utf-8"?><Database Name="Realty" Class="ICANSubmitIdeaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=tcp:adanistaging-sql.database.windows.net;Initial Catalog=Realty;User ID=Sitecore" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="RealtyConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ICANChallengeSignUp" Member="ICANChallengeSignUps">
    <Type Name="ICANChallengeSignUp">
      <Column Name="STUID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SchoolUDISENumber" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="SchoolAddress" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PrincipalName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PrincipalEmailID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SchoolBoard" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TeamCoordinatorName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TeamCoordinatorEmailID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TeamCoordinatorMobileNumber" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ICANChallengeSignIn" Member="ICANChallengeSignIns">
    <Type Name="ICANChallengeSignIn">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SchoolCoordinateNumber" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ICANOtpHistory" Member="ICANOtpHistories">
    <Type Name="ICANOtpHistory">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MobileNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="otp" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ICANSubmitYourIdea" Member="ICANSubmitYourIdeas">
    <Type Name="ICANSubmitYourIdea">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RegistrationNumber" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="GroupName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Student1Name" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Student1Grade" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Student1DOB" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Student2Name" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Student2Grade" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Student2DOB" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Student3Name" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Student3Grade" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Student3DOB" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Student4Name" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Student4Grade" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Student4DOB" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TitleForProject" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="TweetLengthIntro" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ExplainatoryText" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Image1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Image2" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Image3" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Image4" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Image5" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Image6" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Image7" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="VideoLink" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="YLink" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="FormName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="SchoolCoordinateNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ICANJuryLogin" Member="ICANJuryLogins">
    <Type Name="ICANJuryLogin">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="JuryMobileNumber" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ICANJuryScore" Member="ICANJuryScores">
    <Type Name="ICANJuryScore">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RegistrationNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreativityScore" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DetailingScore" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ScientificScore" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PermanencyScore" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClimateScore" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OverallPresentaionScore" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalScore" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GroupName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="JuryPhoneNumber" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="SchoolUDISENumber" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ICANFinalistReview" Member="ICANFinalistReviews">
    <Type Name="ICANFinalistReview">
      <Column Name="SrNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="School_details" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Project_Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Id" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RegistrationNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UDISE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="School_Name_Address" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="GroupName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Student1Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Student1Grade" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Student1DOB" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Student2Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Student2Grade" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Student2DOB" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Student3Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Student3Grade" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Student3DOB" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Student4Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Student4Grade" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Student4DOB" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TitleForProject" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TweetLengthIntro" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ExplainatoryText" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Image1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Image2" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Image3" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Image4" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Image5" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Image6" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Image7" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="VideoLink" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="YLink" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FormName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SchoolCoordinateNumber" Type="System.String" DbType="NVarChar(53)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ICANFinalistDashboardNew" Member="ICANFinalistDashboardNews">
    <Type Name="ICANFinalistDashboardNew">
      <Column Name="ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UDISE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SchoolName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProjectName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CoordinateName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>