<?xml version="1.0" encoding="utf-8"?><Database Name="AdaniAirports" Class="TenderDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Corrigendum" Member="Corrigendums">
    <Type Name="Corrigendum">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Created_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Modified_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Corrigendum_CorrigendumTenderMapping" Member="CorrigendumTenderMappings" ThisKey="Id" OtherKey="CorrigendumId" Type="CorrigendumTenderMapping" />
      <Association Name="Corrigendum_CorrigendumDocument" Member="CorrigendumDocuments" ThisKey="Id" OtherKey="CorrigendumId" Type="CorrigendumDocument" />
    </Type>
  </Table>
  <Table Name="dbo.CorrigendumTenderMapping" Member="CorrigendumTenderMappings">
    <Type Name="CorrigendumTenderMapping">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CorrigendumId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="TenderId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Created_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Modified_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Corrigendum_CorrigendumTenderMapping" Member="Corrigendum" ThisKey="CorrigendumId" OtherKey="Id" Type="Corrigendum" IsForeignKey="true" />
      <Association Name="TenderList_CorrigendumTenderMapping" Member="TenderList" ThisKey="TenderId" OtherKey="Id" Type="TenderList" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserTenderMapping" Member="UserTenderMappings">
    <Type Name="UserTenderMapping">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="TenderId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Envelope" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.AdaniAirportsContactForm" Member="AdaniAirportsContactForms">
    <Type Name="AdaniAirportsContactForm">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="MessageType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FormType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PageInfo" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="FormSubmitOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TenderDocument" Member="TenderDocuments">
    <Type Name="TenderDocument">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenderId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DocumentPath" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Created_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Modified_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ContentType" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DocData" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IsPQDoc" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TenderList_TenderDocument" Member="TenderList" ThisKey="TenderId" OtherKey="Id" Type="TenderList" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserTenderDocument" Member="UserTenderDocuments">
    <Type Name="UserTenderDocument">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="EnvelopeType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DocumentPath" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Created_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Modified_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ContentType" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DocData" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IsPQDoc" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="UserTenderDocument_UserTenderDocument" Member="UserTenderDocument2" ThisKey="Id" OtherKey="Id" Type="UserTenderDocument" Cardinality="One" />
      <Association Name="UserTenderDocument_UserTenderDocument" Member="UserTenderDocument1" ThisKey="Id" OtherKey="Id" Type="UserTenderDocument" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CorrigendumDocument" Member="CorrigendumDocuments">
    <Type Name="CorrigendumDocument">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CorrigendumId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DocumentPath" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Created_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Modified_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ContentType" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DocData" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IsPQDoc" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Corrigendum_CorrigendumDocument" Member="Corrigendum" ThisKey="CorrigendumId" OtherKey="Id" Type="Corrigendum" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Registration" Member="Registrations">
    <Type Name="Registration">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="UserType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TenderId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Created_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Modified_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Fax_No" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsPQVerified" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsFinalSubmit" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AllowLogin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UniqueId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PQEnvelopeReviewStatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PQEnvelopeReviewBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="TenderList_Registration" Member="TenderList" ThisKey="TenderId" OtherKey="Id" Type="TenderList" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TenderList" Member="TenderLists">
    <Type Name="TenderList">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NITNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Business" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Adv_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Closing_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Estimated_Cost" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Cost_of_EMD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Staus" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Created_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Modified_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsReminderMailSent" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsCloseEmailSent" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PQApprovalRequired" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TenderType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SupportEmailAddress" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="TenderList_CorrigendumTenderMapping" Member="CorrigendumTenderMappings" ThisKey="Id" OtherKey="TenderId" Type="CorrigendumTenderMapping" />
      <Association Name="TenderList_TenderDocument" Member="TenderDocuments" ThisKey="Id" OtherKey="TenderId" Type="TenderDocument" />
      <Association Name="TenderList_Registration" Member="Registrations" ThisKey="Id" OtherKey="TenderId" Type="Registration" />
    </Type>
  </Table>
  <Table Name="dbo.LoginHistory" Member="LoginHistories">
    <Type Name="LoginHistory">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Userid" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AirportAssistance" Member="AirportAssistances">
    <Type Name="AirportAssistance">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ContactNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AlternateContactNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EmailAddress" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TravelDate" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TypeOfService" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FormSubmitDate" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TravelSector" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MangaloreAirportFlights" Member="MangaloreAirportFlights">
    <Type Name="MangaloreAirportFlight">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OriginDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FlightNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ArrivingFrom" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DepartureFrom" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Scheduled" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Airline" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Terminal" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OperationalStatus" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ServiceType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AssociatedFlightLegSchedule" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EstimationTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ScheduledTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ActualTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SpecialAction" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="flightkind" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FlightType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.IXE_AirportSurveyFeedback" Member="IXE_AirportSurveyFeedbacks">
    <Type Name="IXE_AirportSurveyFeedback">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DateOfVisit" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FlightDetails" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Contact" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FacilitiesServices" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AirportCleanliness" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AirportFacilities" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ShoppingFacilities" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CourtesyOfStaff" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="WaitingTime" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ArrivalFacilities" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TransportationFacilities" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FlightConnectivity" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaintenanceUpkeep" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RecommendationScale" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Suggestion" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TravelPurpose" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AgeGroup" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FormSubmitDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.IXE_AirportContactUsForm" Member="IXE_AirportContactUsForms">
    <Type Name="IXE_AirportContactUsForm">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="ContactNo" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ContactType" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CaseNumber" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ResMessage" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FormSubmitDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IPAddress" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>