//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_CA_Details_SendService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://aeml.com/Web", ConfigurationName="SI_CA_Details_SendService.SI_CA_Details_Send")]
    public interface SI_CA_Details_Send
    {
        
        // CODEGEN: Generating message contract since the operation SI_CA_Details_Send is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        SI_CA_Details_SendService.SI_CA_Details_SendResponse SI_CA_Details_Send(SI_CA_Details_SendService.SI_CA_Details_SendRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<SI_CA_Details_SendService.SI_CA_Details_SendResponse> SI_CA_Details_SendAsync(SI_CA_Details_SendService.SI_CA_Details_SendRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rel.com/xi/KAM/CA_Details")]
    public partial class DT_CA_Details_Req
    {
        
        private string vKONTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string VKONT
        {
            get
            {
                return this.vKONTField;
            }
            set
            {
                this.vKONTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aeml.com/Web")]
    public partial class DT_CA_Details_Res
    {
        
        private string vKONT_OUTField;
        
        private string nAMEField;
        
        private string aDDRESS1Field;
        
        private string aDDRESS2Field;
        
        private string aDDRESS3Field;
        
        private string aDDRESS4Field;
        
        private string mOBILE_NOField;
        
        private string tELEPHONE_NOField;
        
        private string fAX_NOField;
        
        private string tARIFTYPField;
        
        private string bSTATUSField;
        
        private decimal oVERDUE_AMTField;
        
        private bool oVERDUE_AMTFieldSpecified;
        
        private string sMTP_ADDRField;
        
        private string iNVALIDCAFLAGField;
        
        private string mOVEOUTFLAGField;
        
        private string dISCONNECTEDFLAGField;
        
        private string vIGILANCEFLAGField;
        
        private string aKLASSEField;
        
        private string vERTRAGField;
        
        private string aNLAGEField;
        
        private string gPARTField;
        
        private string cOKEYField;
        
        private string vAPLZField;
        
        private string cHNG_OVER_FLAGField;
        
        private string eINZDATField;
        
        private string lAST_BIL_AMND_FLField;
        
        private string nO_LAST_BILL_FLGField;
        
        private string rEGIO_GROUP_TEXTField;
        
        private string rEGIO_AREA_CODEField;
        
        private string rEGIO_AREA_TEXTField;
        
        private DT_CA_Details_ResItem[] iT_LOADField;
        
        private DT_CA_Details_ResItem1[] iT_METERField;
        
        private DT_CA_Details_ResItem2[] iT_RETURNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string VKONT_OUT
        {
            get
            {
                return this.vKONT_OUTField;
            }
            set
            {
                this.vKONT_OUTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string NAME
        {
            get
            {
                return this.nAMEField;
            }
            set
            {
                this.nAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ADDRESS1
        {
            get
            {
                return this.aDDRESS1Field;
            }
            set
            {
                this.aDDRESS1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ADDRESS2
        {
            get
            {
                return this.aDDRESS2Field;
            }
            set
            {
                this.aDDRESS2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ADDRESS3
        {
            get
            {
                return this.aDDRESS3Field;
            }
            set
            {
                this.aDDRESS3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ADDRESS4
        {
            get
            {
                return this.aDDRESS4Field;
            }
            set
            {
                this.aDDRESS4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MOBILE_NO
        {
            get
            {
                return this.mOBILE_NOField;
            }
            set
            {
                this.mOBILE_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string TELEPHONE_NO
        {
            get
            {
                return this.tELEPHONE_NOField;
            }
            set
            {
                this.tELEPHONE_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string FAX_NO
        {
            get
            {
                return this.fAX_NOField;
            }
            set
            {
                this.fAX_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string TARIFTYP
        {
            get
            {
                return this.tARIFTYPField;
            }
            set
            {
                this.tARIFTYPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string BSTATUS
        {
            get
            {
                return this.bSTATUSField;
            }
            set
            {
                this.bSTATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public decimal OVERDUE_AMT
        {
            get
            {
                return this.oVERDUE_AMTField;
            }
            set
            {
                this.oVERDUE_AMTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OVERDUE_AMTSpecified
        {
            get
            {
                return this.oVERDUE_AMTFieldSpecified;
            }
            set
            {
                this.oVERDUE_AMTFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string SMTP_ADDR
        {
            get
            {
                return this.sMTP_ADDRField;
            }
            set
            {
                this.sMTP_ADDRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string INVALIDCAFLAG
        {
            get
            {
                return this.iNVALIDCAFLAGField;
            }
            set
            {
                this.iNVALIDCAFLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string MOVEOUTFLAG
        {
            get
            {
                return this.mOVEOUTFLAGField;
            }
            set
            {
                this.mOVEOUTFLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string DISCONNECTEDFLAG
        {
            get
            {
                return this.dISCONNECTEDFLAGField;
            }
            set
            {
                this.dISCONNECTEDFLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string VIGILANCEFLAG
        {
            get
            {
                return this.vIGILANCEFLAGField;
            }
            set
            {
                this.vIGILANCEFLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string AKLASSE
        {
            get
            {
                return this.aKLASSEField;
            }
            set
            {
                this.aKLASSEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string VERTRAG
        {
            get
            {
                return this.vERTRAGField;
            }
            set
            {
                this.vERTRAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string ANLAGE
        {
            get
            {
                return this.aNLAGEField;
            }
            set
            {
                this.aNLAGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string GPART
        {
            get
            {
                return this.gPARTField;
            }
            set
            {
                this.gPARTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string COKEY
        {
            get
            {
                return this.cOKEYField;
            }
            set
            {
                this.cOKEYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string VAPLZ
        {
            get
            {
                return this.vAPLZField;
            }
            set
            {
                this.vAPLZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string CHNG_OVER_FLAG
        {
            get
            {
                return this.cHNG_OVER_FLAGField;
            }
            set
            {
                this.cHNG_OVER_FLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string EINZDAT
        {
            get
            {
                return this.eINZDATField;
            }
            set
            {
                this.eINZDATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string LAST_BIL_AMND_FL
        {
            get
            {
                return this.lAST_BIL_AMND_FLField;
            }
            set
            {
                this.lAST_BIL_AMND_FLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string NO_LAST_BILL_FLG
        {
            get
            {
                return this.nO_LAST_BILL_FLGField;
            }
            set
            {
                this.nO_LAST_BILL_FLGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string REGIO_GROUP_TEXT
        {
            get
            {
                return this.rEGIO_GROUP_TEXTField;
            }
            set
            {
                this.rEGIO_GROUP_TEXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string REGIO_AREA_CODE
        {
            get
            {
                return this.rEGIO_AREA_CODEField;
            }
            set
            {
                this.rEGIO_AREA_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string REGIO_AREA_TEXT
        {
            get
            {
                return this.rEGIO_AREA_TEXTField;
            }
            set
            {
                this.rEGIO_AREA_TEXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_CA_Details_ResItem[] IT_LOAD
        {
            get
            {
                return this.iT_LOADField;
            }
            set
            {
                this.iT_LOADField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_CA_Details_ResItem1[] IT_METER
        {
            get
            {
                return this.iT_METERField;
            }
            set
            {
                this.iT_METERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_CA_Details_ResItem2[] IT_RETURN
        {
            get
            {
                return this.iT_RETURNField;
            }
            set
            {
                this.iT_RETURNField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://aeml.com/Web")]
    public partial class DT_CA_Details_ResItem
    {
        
        private string oPERANDField;
        
        private decimal zLOADField;
        
        private bool zLOADFieldSpecified;
        
        private string uNITField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string OPERAND
        {
            get
            {
                return this.oPERANDField;
            }
            set
            {
                this.oPERANDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal ZLOAD
        {
            get
            {
                return this.zLOADField;
            }
            set
            {
                this.zLOADField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ZLOADSpecified
        {
            get
            {
                return this.zLOADFieldSpecified;
            }
            set
            {
                this.zLOADFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string UNIT
        {
            get
            {
                return this.uNITField;
            }
            set
            {
                this.uNITField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://aeml.com/Web")]
    public partial class DT_CA_Details_ResItem1
    {
        
        private string sERNRField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string SERNR
        {
            get
            {
                return this.sERNRField;
            }
            set
            {
                this.sERNRField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://aeml.com/Web")]
    public partial class DT_CA_Details_ResItem2
    {
        
        private string tYPEField;
        
        private string idField;
        
        private string nUMBERField;
        
        private string mESSAGEField;
        
        private string lOG_NOField;
        
        private string lOG_MSG_NOField;
        
        private string mESSAGE_V1Field;
        
        private string mESSAGE_V2Field;
        
        private string mESSAGE_V3Field;
        
        private string mESSAGE_V4Field;
        
        private string pARAMETERField;
        
        private string rOWField;
        
        private string fIELDField;
        
        private string sYSTEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TYPE
        {
            get
            {
                return this.tYPEField;
            }
            set
            {
                this.tYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NUMBER
        {
            get
            {
                return this.nUMBERField;
            }
            set
            {
                this.nUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MESSAGE
        {
            get
            {
                return this.mESSAGEField;
            }
            set
            {
                this.mESSAGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string LOG_NO
        {
            get
            {
                return this.lOG_NOField;
            }
            set
            {
                this.lOG_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string LOG_MSG_NO
        {
            get
            {
                return this.lOG_MSG_NOField;
            }
            set
            {
                this.lOG_MSG_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MESSAGE_V1
        {
            get
            {
                return this.mESSAGE_V1Field;
            }
            set
            {
                this.mESSAGE_V1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string MESSAGE_V2
        {
            get
            {
                return this.mESSAGE_V2Field;
            }
            set
            {
                this.mESSAGE_V2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string MESSAGE_V3
        {
            get
            {
                return this.mESSAGE_V3Field;
            }
            set
            {
                this.mESSAGE_V3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string MESSAGE_V4
        {
            get
            {
                return this.mESSAGE_V4Field;
            }
            set
            {
                this.mESSAGE_V4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string PARAMETER
        {
            get
            {
                return this.pARAMETERField;
            }
            set
            {
                this.pARAMETERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string ROW
        {
            get
            {
                return this.rOWField;
            }
            set
            {
                this.rOWField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string FIELD
        {
            get
            {
                return this.fIELDField;
            }
            set
            {
                this.fIELDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string SYSTEM
        {
            get
            {
                return this.sYSTEMField;
            }
            set
            {
                this.sYSTEMField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_CA_Details_SendRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rel.com/xi/KAM/CA_Details", Order=0)]
        public SI_CA_Details_SendService.DT_CA_Details_Req MT_CA_Details_Req;
        
        public SI_CA_Details_SendRequest()
        {
        }
        
        public SI_CA_Details_SendRequest(SI_CA_Details_SendService.DT_CA_Details_Req MT_CA_Details_Req)
        {
            this.MT_CA_Details_Req = MT_CA_Details_Req;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_CA_Details_SendResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://aeml.com/Web", Order=0)]
        public SI_CA_Details_SendService.DT_CA_Details_Res MT_CA_Details_Res;
        
        public SI_CA_Details_SendResponse()
        {
        }
        
        public SI_CA_Details_SendResponse(SI_CA_Details_SendService.DT_CA_Details_Res MT_CA_Details_Res)
        {
            this.MT_CA_Details_Res = MT_CA_Details_Res;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_CA_Details_SendChannel : SI_CA_Details_SendService.SI_CA_Details_Send, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_CA_Details_SendClient : System.ServiceModel.ClientBase<SI_CA_Details_SendService.SI_CA_Details_Send>, SI_CA_Details_SendService.SI_CA_Details_Send
    {
        
        public SI_CA_Details_SendClient()
        {
        }
        
        public SI_CA_Details_SendClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public SI_CA_Details_SendClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public SI_CA_Details_SendClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public SI_CA_Details_SendClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SI_CA_Details_SendService.SI_CA_Details_SendResponse SI_CA_Details_SendService.SI_CA_Details_Send.SI_CA_Details_Send(SI_CA_Details_SendService.SI_CA_Details_SendRequest request)
        {
            return base.Channel.SI_CA_Details_Send(request);
        }
        
        public SI_CA_Details_SendService.DT_CA_Details_Res SI_CA_Details_Send(SI_CA_Details_SendService.DT_CA_Details_Req MT_CA_Details_Req)
        {
            SI_CA_Details_SendService.SI_CA_Details_SendRequest inValue = new SI_CA_Details_SendService.SI_CA_Details_SendRequest();
            inValue.MT_CA_Details_Req = MT_CA_Details_Req;
            SI_CA_Details_SendService.SI_CA_Details_SendResponse retVal = ((SI_CA_Details_SendService.SI_CA_Details_Send)(this)).SI_CA_Details_Send(inValue);
            return retVal.MT_CA_Details_Res;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SI_CA_Details_SendService.SI_CA_Details_SendResponse> SI_CA_Details_SendService.SI_CA_Details_Send.SI_CA_Details_SendAsync(SI_CA_Details_SendService.SI_CA_Details_SendRequest request)
        {
            return base.Channel.SI_CA_Details_SendAsync(request);
        }
        
        public System.Threading.Tasks.Task<SI_CA_Details_SendService.SI_CA_Details_SendResponse> SI_CA_Details_SendAsync(SI_CA_Details_SendService.DT_CA_Details_Req MT_CA_Details_Req)
        {
            SI_CA_Details_SendService.SI_CA_Details_SendRequest inValue = new SI_CA_Details_SendService.SI_CA_Details_SendRequest();
            inValue.MT_CA_Details_Req = MT_CA_Details_Req;
            return ((SI_CA_Details_SendService.SI_CA_Details_Send)(this)).SI_CA_Details_SendAsync(inValue);
        }
    }
}
