//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8943
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace = "http://rel.com/xi/RelMobApp/Cms_Isu_Ca_Display", ConfigurationName = "SI_Cms_Isu_Ca_Display_in")]
public interface SI_Cms_Isu_Ca_Display_in
{

    // CODEGEN: Generating message contract since the operation SI_Cms_Isu_Ca_Display_in is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action = "http://sap.com/xi/WebService/soap1.1", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    SI_Cms_Isu_Ca_Display_inResponse SI_Cms_Isu_Ca_Display_in(SI_Cms_Isu_Ca_Display_inRequest request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://rel.com/xi/RelMobApp/Cms_Isu_Ca_Display")]
public partial class DT_Cms_Isu_Ca_Display_req
{

    private DT_Cms_Isu_Ca_Display_reqIMPORT_CANUMBER iMPORT_CANUMBERField;

    private string iMPORT_CSNUMBERField;

    private string iMPORT_TELEPHONE_NOField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
    public DT_Cms_Isu_Ca_Display_reqIMPORT_CANUMBER IMPORT_CANUMBER
    {
        get
        {
            return this.iMPORT_CANUMBERField;
        }
        set
        {
            this.iMPORT_CANUMBERField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
    public string IMPORT_CSNUMBER
    {
        get
        {
            return this.iMPORT_CSNUMBERField;
        }
        set
        {
            this.iMPORT_CSNUMBERField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
    public string IMPORT_TELEPHONE_NO
    {
        get
        {
            return this.iMPORT_TELEPHONE_NOField;
        }
        set
        {
            this.iMPORT_TELEPHONE_NOField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://rel.com/xi/RelMobApp/Cms_Isu_Ca_Display")]
public partial class DT_Cms_Isu_Ca_Display_reqIMPORT_CANUMBER
{

    private string cA_NUMBERField;

    private string cONTRACTField;

    private string sERIALNOField;

    private string tATA_CONSUMERField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
    public string CA_NUMBER
    {
        get
        {
            return this.cA_NUMBERField;
        }
        set
        {
            this.cA_NUMBERField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
    public string CONTRACT
    {
        get
        {
            return this.cONTRACTField;
        }
        set
        {
            this.cONTRACTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
    public string SERIALNO
    {
        get
        {
            return this.sERIALNOField;
        }
        set
        {
            this.sERIALNOField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
    public string TATA_CONSUMER
    {
        get
        {
            return this.tATA_CONSUMERField;
        }
        set
        {
            this.tATA_CONSUMERField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://rel.com/xi/RelMobApp/Cms_Isu_Ca_Display")]
public partial class DT_Cms_Isu_Ca_Display_resp
{

    private DT_Cms_Isu_Ca_Display_respItem[] bAPIMESSAGEField;

    private DT_Cms_Isu_Ca_Display_respItem1[] eXPORT_CADETAILSField;

    private DT_Cms_Isu_Ca_Display_respItem2[] eXPORT_CSDETAILSField;

    private DT_Cms_Isu_Ca_Display_respItem3[] rETURNField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public DT_Cms_Isu_Ca_Display_respItem[] BAPIMESSAGE
    {
        get
        {
            return this.bAPIMESSAGEField;
        }
        set
        {
            this.bAPIMESSAGEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public DT_Cms_Isu_Ca_Display_respItem1[] EXPORT_CADETAILS
    {
        get
        {
            return this.eXPORT_CADETAILSField;
        }
        set
        {
            this.eXPORT_CADETAILSField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public DT_Cms_Isu_Ca_Display_respItem2[] EXPORT_CSDETAILS
    {
        get
        {
            return this.eXPORT_CSDETAILSField;
        }
        set
        {
            this.eXPORT_CSDETAILSField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public DT_Cms_Isu_Ca_Display_respItem3[] RETURN
    {
        get
        {
            return this.rETURNField;
        }
        set
        {
            this.rETURNField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://rel.com/xi/RelMobApp/Cms_Isu_Ca_Display")]
public partial class DT_Cms_Isu_Ca_Display_respItem
{

    private string mESSAGEField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
    public string MESSAGE
    {
        get
        {
            return this.mESSAGEField;
        }
        set
        {
            this.mESSAGEField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://rel.com/xi/RelMobApp/Cms_Isu_Ca_Display")]
public partial class DT_Cms_Isu_Ca_Display_respItem1
{

    private string cA_NUMBERField;

    private string bP_NUMBERField;

    private string bP_NAMEField;

    private string bP_TYPEField;

    private string sEARCH_TERM1Field;

    private string sEARCH_TERM2Field;

    private string hOUSE_NUMBERField;

    private string hOUSE_NUMBER_SUPField;

    private string fLOORField;

    private string pREMISE_TYPEField;

    private string sTREETField;

    private string sTREET2Field;

    private string sTREET3Field;

    private string cITYField;

    private string pOST_CODEField;

    private string rEGIONField;

    private string cOUNTRYField;

    private string dESC_CON_OBJECTField;

    private string rEG_STR_GROUPField;

    private string dEVICE_SR_NUMBERField;

    private string tELEPHONE_NOField;

    private string mRUField;

    private string fUNC_DESCRField;

    private string oUTAGE_FROMTIMEField;

    private string oUTAGE_TOTIMEField;

    private string lEGACY_ACCTField;

    private string bILL_CLASSField;

    private string rATE_CATField;

    private string aCTIVITYField;

    private string aDR_NOTESField;

    private string tEL1_NUMBRField;

    private string vERTRAGField;

    private string e_MAILField;

    private string mOVE_OUT_DATEField;

    private string cON_OBJ_NOField;

    private string cLERK_IDField;

    private string tEXTField;

    private string sTATUSField;

    private string dISCREASONField;

    private string z_FUNCLField;

    private string tATA_CONSUMERField;

    private string cONN_TYPEField;

    private string zCATField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
    public string CA_NUMBER
    {
        get
        {
            return this.cA_NUMBERField;
        }
        set
        {
            this.cA_NUMBERField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
    public string BP_NUMBER
    {
        get
        {
            return this.bP_NUMBERField;
        }
        set
        {
            this.bP_NUMBERField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
    public string BP_NAME
    {
        get
        {
            return this.bP_NAMEField;
        }
        set
        {
            this.bP_NAMEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
    public string BP_TYPE
    {
        get
        {
            return this.bP_TYPEField;
        }
        set
        {
            this.bP_TYPEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
    public string SEARCH_TERM1
    {
        get
        {
            return this.sEARCH_TERM1Field;
        }
        set
        {
            this.sEARCH_TERM1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
    public string SEARCH_TERM2
    {
        get
        {
            return this.sEARCH_TERM2Field;
        }
        set
        {
            this.sEARCH_TERM2Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
    public string HOUSE_NUMBER
    {
        get
        {
            return this.hOUSE_NUMBERField;
        }
        set
        {
            this.hOUSE_NUMBERField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
    public string HOUSE_NUMBER_SUP
    {
        get
        {
            return this.hOUSE_NUMBER_SUPField;
        }
        set
        {
            this.hOUSE_NUMBER_SUPField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
    public string FLOOR
    {
        get
        {
            return this.fLOORField;
        }
        set
        {
            this.fLOORField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
    public string PREMISE_TYPE
    {
        get
        {
            return this.pREMISE_TYPEField;
        }
        set
        {
            this.pREMISE_TYPEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 10)]
    public string STREET
    {
        get
        {
            return this.sTREETField;
        }
        set
        {
            this.sTREETField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 11)]
    public string STREET2
    {
        get
        {
            return this.sTREET2Field;
        }
        set
        {
            this.sTREET2Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 12)]
    public string STREET3
    {
        get
        {
            return this.sTREET3Field;
        }
        set
        {
            this.sTREET3Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 13)]
    public string CITY
    {
        get
        {
            return this.cITYField;
        }
        set
        {
            this.cITYField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 14)]
    public string POST_CODE
    {
        get
        {
            return this.pOST_CODEField;
        }
        set
        {
            this.pOST_CODEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 15)]
    public string REGION
    {
        get
        {
            return this.rEGIONField;
        }
        set
        {
            this.rEGIONField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 16)]
    public string COUNTRY
    {
        get
        {
            return this.cOUNTRYField;
        }
        set
        {
            this.cOUNTRYField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 17)]
    public string DESC_CON_OBJECT
    {
        get
        {
            return this.dESC_CON_OBJECTField;
        }
        set
        {
            this.dESC_CON_OBJECTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 18)]
    public string REG_STR_GROUP
    {
        get
        {
            return this.rEG_STR_GROUPField;
        }
        set
        {
            this.rEG_STR_GROUPField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 19)]
    public string DEVICE_SR_NUMBER
    {
        get
        {
            return this.dEVICE_SR_NUMBERField;
        }
        set
        {
            this.dEVICE_SR_NUMBERField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 20)]
    public string TELEPHONE_NO
    {
        get
        {
            return this.tELEPHONE_NOField;
        }
        set
        {
            this.tELEPHONE_NOField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 21)]
    public string MRU
    {
        get
        {
            return this.mRUField;
        }
        set
        {
            this.mRUField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 22)]
    public string FUNC_DESCR
    {
        get
        {
            return this.fUNC_DESCRField;
        }
        set
        {
            this.fUNC_DESCRField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 23)]
    public string OUTAGE_FROMTIME
    {
        get
        {
            return this.oUTAGE_FROMTIMEField;
        }
        set
        {
            this.oUTAGE_FROMTIMEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 24)]
    public string OUTAGE_TOTIME
    {
        get
        {
            return this.oUTAGE_TOTIMEField;
        }
        set
        {
            this.oUTAGE_TOTIMEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 25)]
    public string LEGACY_ACCT
    {
        get
        {
            return this.lEGACY_ACCTField;
        }
        set
        {
            this.lEGACY_ACCTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 26)]
    public string BILL_CLASS
    {
        get
        {
            return this.bILL_CLASSField;
        }
        set
        {
            this.bILL_CLASSField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 27)]
    public string RATE_CAT
    {
        get
        {
            return this.rATE_CATField;
        }
        set
        {
            this.rATE_CATField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 28)]
    public string ACTIVITY
    {
        get
        {
            return this.aCTIVITYField;
        }
        set
        {
            this.aCTIVITYField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 29)]
    public string ADR_NOTES
    {
        get
        {
            return this.aDR_NOTESField;
        }
        set
        {
            this.aDR_NOTESField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 30)]
    public string TEL1_NUMBR
    {
        get
        {
            return this.tEL1_NUMBRField;
        }
        set
        {
            this.tEL1_NUMBRField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 31)]
    public string VERTRAG
    {
        get
        {
            return this.vERTRAGField;
        }
        set
        {
            this.vERTRAGField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 32)]
    public string E_MAIL
    {
        get
        {
            return this.e_MAILField;
        }
        set
        {
            this.e_MAILField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 33)]
    public string MOVE_OUT_DATE
    {
        get
        {
            return this.mOVE_OUT_DATEField;
        }
        set
        {
            this.mOVE_OUT_DATEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 34)]
    public string CON_OBJ_NO
    {
        get
        {
            return this.cON_OBJ_NOField;
        }
        set
        {
            this.cON_OBJ_NOField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 35)]
    public string CLERK_ID
    {
        get
        {
            return this.cLERK_IDField;
        }
        set
        {
            this.cLERK_IDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 36)]
    public string TEXT
    {
        get
        {
            return this.tEXTField;
        }
        set
        {
            this.tEXTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 37)]
    public string STATUS
    {
        get
        {
            return this.sTATUSField;
        }
        set
        {
            this.sTATUSField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 38)]
    public string DISCREASON
    {
        get
        {
            return this.dISCREASONField;
        }
        set
        {
            this.dISCREASONField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 39)]
    public string Z_FUNCL
    {
        get
        {
            return this.z_FUNCLField;
        }
        set
        {
            this.z_FUNCLField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 40)]
    public string TATA_CONSUMER
    {
        get
        {
            return this.tATA_CONSUMERField;
        }
        set
        {
            this.tATA_CONSUMERField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 41)]
    public string CONN_TYPE
    {
        get
        {
            return this.cONN_TYPEField;
        }
        set
        {
            this.cONN_TYPEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 42)]
    public string ZCAT
    {
        get
        {
            return this.zCATField;
        }
        set
        {
            this.zCATField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://rel.com/xi/RelMobApp/Cms_Isu_Ca_Display")]
public partial class DT_Cms_Isu_Ca_Display_respItem2
{

    private string cA_NUMBERField;

    private string cONTRACTField;

    private string bP_NAMEField;

    private string hOUSE_NUMBER_SUPField;

    private string sTREETField;

    private string sTREET2Field;

    private string aDR_NOTESField;

    private string fLAGField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
    public string CA_NUMBER
    {
        get
        {
            return this.cA_NUMBERField;
        }
        set
        {
            this.cA_NUMBERField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
    public string CONTRACT
    {
        get
        {
            return this.cONTRACTField;
        }
        set
        {
            this.cONTRACTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
    public string BP_NAME
    {
        get
        {
            return this.bP_NAMEField;
        }
        set
        {
            this.bP_NAMEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
    public string HOUSE_NUMBER_SUP
    {
        get
        {
            return this.hOUSE_NUMBER_SUPField;
        }
        set
        {
            this.hOUSE_NUMBER_SUPField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
    public string STREET
    {
        get
        {
            return this.sTREETField;
        }
        set
        {
            this.sTREETField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
    public string STREET2
    {
        get
        {
            return this.sTREET2Field;
        }
        set
        {
            this.sTREET2Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
    public string ADR_NOTES
    {
        get
        {
            return this.aDR_NOTESField;
        }
        set
        {
            this.aDR_NOTESField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
    public string FLAG
    {
        get
        {
            return this.fLAGField;
        }
        set
        {
            this.fLAGField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://rel.com/xi/RelMobApp/Cms_Isu_Ca_Display")]
public partial class DT_Cms_Isu_Ca_Display_respItem3
{

    private string tYPEField;

    private string idField;

    private string nUMBERField;

    private string mESSAGEField;

    private string lOG_NOField;

    private string lOG_MSG_NOField;

    private string mESSAGE_V1Field;

    private string mESSAGE_V2Field;

    private string mESSAGE_V3Field;

    private string mESSAGE_V4Field;

    private string pARAMETERField;

    private string rOWField;

    private string fIELDField;

    private string sYSTEMField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
    public string TYPE
    {
        get
        {
            return this.tYPEField;
        }
        set
        {
            this.tYPEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
    public string ID
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
    public string NUMBER
    {
        get
        {
            return this.nUMBERField;
        }
        set
        {
            this.nUMBERField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
    public string MESSAGE
    {
        get
        {
            return this.mESSAGEField;
        }
        set
        {
            this.mESSAGEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
    public string LOG_NO
    {
        get
        {
            return this.lOG_NOField;
        }
        set
        {
            this.lOG_NOField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
    public string LOG_MSG_NO
    {
        get
        {
            return this.lOG_MSG_NOField;
        }
        set
        {
            this.lOG_MSG_NOField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
    public string MESSAGE_V1
    {
        get
        {
            return this.mESSAGE_V1Field;
        }
        set
        {
            this.mESSAGE_V1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
    public string MESSAGE_V2
    {
        get
        {
            return this.mESSAGE_V2Field;
        }
        set
        {
            this.mESSAGE_V2Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
    public string MESSAGE_V3
    {
        get
        {
            return this.mESSAGE_V3Field;
        }
        set
        {
            this.mESSAGE_V3Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
    public string MESSAGE_V4
    {
        get
        {
            return this.mESSAGE_V4Field;
        }
        set
        {
            this.mESSAGE_V4Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 10)]
    public string PARAMETER
    {
        get
        {
            return this.pARAMETERField;
        }
        set
        {
            this.pARAMETERField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 11)]
    public string ROW
    {
        get
        {
            return this.rOWField;
        }
        set
        {
            this.rOWField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 12)]
    public string FIELD
    {
        get
        {
            return this.fIELDField;
        }
        set
        {
            this.fIELDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 13)]
    public string SYSTEM
    {
        get
        {
            return this.sYSTEMField;
        }
        set
        {
            this.sYSTEMField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class SI_Cms_Isu_Ca_Display_inRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://rel.com/xi/RelMobApp/Cms_Isu_Ca_Display", Order = 0)]
    public DT_Cms_Isu_Ca_Display_req MT_Cms_Isu_Ca_Display_req;

    public SI_Cms_Isu_Ca_Display_inRequest()
    {
    }

    public SI_Cms_Isu_Ca_Display_inRequest(DT_Cms_Isu_Ca_Display_req MT_Cms_Isu_Ca_Display_req)
    {
        this.MT_Cms_Isu_Ca_Display_req = MT_Cms_Isu_Ca_Display_req;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class SI_Cms_Isu_Ca_Display_inResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://rel.com/xi/RelMobApp/Cms_Isu_Ca_Display", Order = 0)]
    public DT_Cms_Isu_Ca_Display_resp MT_Cms_Isu_Ca_Display_resp;

    public SI_Cms_Isu_Ca_Display_inResponse()
    {
    }

    public SI_Cms_Isu_Ca_Display_inResponse(DT_Cms_Isu_Ca_Display_resp MT_Cms_Isu_Ca_Display_resp)
    {
        this.MT_Cms_Isu_Ca_Display_resp = MT_Cms_Isu_Ca_Display_resp;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface SI_Cms_Isu_Ca_Display_inChannel : SI_Cms_Isu_Ca_Display_in, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class SI_Cms_Isu_Ca_Display_inClient : System.ServiceModel.ClientBase<SI_Cms_Isu_Ca_Display_in>, SI_Cms_Isu_Ca_Display_in
{

    public SI_Cms_Isu_Ca_Display_inClient()
    {
    }

    public SI_Cms_Isu_Ca_Display_inClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
    {
    }

    public SI_Cms_Isu_Ca_Display_inClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public SI_Cms_Isu_Ca_Display_inClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public SI_Cms_Isu_Ca_Display_inClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    SI_Cms_Isu_Ca_Display_inResponse SI_Cms_Isu_Ca_Display_in.SI_Cms_Isu_Ca_Display_in(SI_Cms_Isu_Ca_Display_inRequest request)
    {
        return base.Channel.SI_Cms_Isu_Ca_Display_in(request);
    }

    public DT_Cms_Isu_Ca_Display_resp SI_Cms_Isu_Ca_Display_in(DT_Cms_Isu_Ca_Display_req MT_Cms_Isu_Ca_Display_req)
    {
        SI_Cms_Isu_Ca_Display_inRequest inValue = new SI_Cms_Isu_Ca_Display_inRequest();
        inValue.MT_Cms_Isu_Ca_Display_req = MT_Cms_Isu_Ca_Display_req;
        SI_Cms_Isu_Ca_Display_inResponse retVal = ((SI_Cms_Isu_Ca_Display_in)(this)).SI_Cms_Isu_Ca_Display_in(inValue);
        return retVal.MT_Cms_Isu_Ca_Display_resp;
    }
}

