//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SapPiService.Wsdl
{
    

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://rel.com/xi/RelMobApp/CHECK_CA_TYPE", ConfigurationName="SI_CHECK_CA_TYPE_in")]
    public interface SI_CHECK_CA_TYPE_in
    {
        
        // CODEGEN: Generating message contract since the operation SI_CHECK_CA_TYPE_in is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        SI_CHECK_CA_TYPE_inResponse SI_CHECK_CA_TYPE_in(SI_CHECK_CA_TYPE_inRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<SI_CHECK_CA_TYPE_inResponse> SI_CHECK_CA_TYPE_inAsync(SI_CHECK_CA_TYPE_inRequest request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rel.com/xi/RelMobApp/CHECK_CA_TYPE")]
    public partial class DT_CHECK_CA_TYPE_req
    {
        
        private string cONT_ACCTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CONT_ACCT
        {
            get
            {
                return this.cONT_ACCTField;
            }
            set
            {
                this.cONT_ACCTField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rel.com/xi/RelMobApp/CHECK_CA_TYPE")]
    public partial class DT_CHECK_CA_TYPE_resp
    {
        
        private string cYCLE_NOField;
        
        private string dONT_DISPLAYField;
        
        private string fORM_TYPEField;
        
        private DT_CHECK_CA_TYPE_respRETURN rETURNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CYCLE_NO
        {
            get
            {
                return this.cYCLE_NOField;
            }
            set
            {
                this.cYCLE_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DONT_DISPLAY
        {
            get
            {
                return this.dONT_DISPLAYField;
            }
            set
            {
                this.dONT_DISPLAYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string FORM_TYPE
        {
            get
            {
                return this.fORM_TYPEField;
            }
            set
            {
                this.fORM_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public DT_CHECK_CA_TYPE_respRETURN RETURN
        {
            get
            {
                return this.rETURNField;
            }
            set
            {
                this.rETURNField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rel.com/xi/RelMobApp/CHECK_CA_TYPE")]
    public partial class DT_CHECK_CA_TYPE_respRETURN
    {
        
        private string tYPEField;
        
        private string idField;
        
        private string nUMBERField;
        
        private string mESSAGEField;
        
        private string lOG_NOField;
        
        private string lOG_MSG_NOField;
        
        private string mESSAGE_V1Field;
        
        private string mESSAGE_V2Field;
        
        private string mESSAGE_V3Field;
        
        private string mESSAGE_V4Field;
        
        private string pARAMETERField;
        
        private string rOWField;
        
        private string fIELDField;
        
        private string sYSTEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TYPE
        {
            get
            {
                return this.tYPEField;
            }
            set
            {
                this.tYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NUMBER
        {
            get
            {
                return this.nUMBERField;
            }
            set
            {
                this.nUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MESSAGE
        {
            get
            {
                return this.mESSAGEField;
            }
            set
            {
                this.mESSAGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string LOG_NO
        {
            get
            {
                return this.lOG_NOField;
            }
            set
            {
                this.lOG_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string LOG_MSG_NO
        {
            get
            {
                return this.lOG_MSG_NOField;
            }
            set
            {
                this.lOG_MSG_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MESSAGE_V1
        {
            get
            {
                return this.mESSAGE_V1Field;
            }
            set
            {
                this.mESSAGE_V1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string MESSAGE_V2
        {
            get
            {
                return this.mESSAGE_V2Field;
            }
            set
            {
                this.mESSAGE_V2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string MESSAGE_V3
        {
            get
            {
                return this.mESSAGE_V3Field;
            }
            set
            {
                this.mESSAGE_V3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string MESSAGE_V4
        {
            get
            {
                return this.mESSAGE_V4Field;
            }
            set
            {
                this.mESSAGE_V4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string PARAMETER
        {
            get
            {
                return this.pARAMETERField;
            }
            set
            {
                this.pARAMETERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string ROW
        {
            get
            {
                return this.rOWField;
            }
            set
            {
                this.rOWField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string FIELD
        {
            get
            {
                return this.fIELDField;
            }
            set
            {
                this.fIELDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string SYSTEM
        {
            get
            {
                return this.sYSTEMField;
            }
            set
            {
                this.sYSTEMField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_CHECK_CA_TYPE_inRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rel.com/xi/RelMobApp/CHECK_CA_TYPE", Order=0)]
        public DT_CHECK_CA_TYPE_req MT_CHECK_CA_TYPE_req;
        
        public SI_CHECK_CA_TYPE_inRequest()
        {
        }
        
        public SI_CHECK_CA_TYPE_inRequest(DT_CHECK_CA_TYPE_req MT_CHECK_CA_TYPE_req)
        {
            this.MT_CHECK_CA_TYPE_req = MT_CHECK_CA_TYPE_req;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_CHECK_CA_TYPE_inResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rel.com/xi/RelMobApp/CHECK_CA_TYPE", Order=0)]
        public DT_CHECK_CA_TYPE_resp MT_CHECK_CA_TYPE_resp;
        
        public SI_CHECK_CA_TYPE_inResponse()
        {
        }
        
        public SI_CHECK_CA_TYPE_inResponse(DT_CHECK_CA_TYPE_resp MT_CHECK_CA_TYPE_resp)
        {
            this.MT_CHECK_CA_TYPE_resp = MT_CHECK_CA_TYPE_resp;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_CHECK_CA_TYPE_inChannel : SI_CHECK_CA_TYPE_in, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_CHECK_CA_TYPE_inClient : System.ServiceModel.ClientBase<SI_CHECK_CA_TYPE_in>, SI_CHECK_CA_TYPE_in
    {
        
        public SI_CHECK_CA_TYPE_inClient()
        {
        }
        
        public SI_CHECK_CA_TYPE_inClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public SI_CHECK_CA_TYPE_inClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public SI_CHECK_CA_TYPE_inClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public SI_CHECK_CA_TYPE_inClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SI_CHECK_CA_TYPE_inResponse SI_CHECK_CA_TYPE_in.SI_CHECK_CA_TYPE_in(SI_CHECK_CA_TYPE_inRequest request)
        {
            return base.Channel.SI_CHECK_CA_TYPE_in(request);
        }
        
        public DT_CHECK_CA_TYPE_resp SI_CHECK_CA_TYPE_in(DT_CHECK_CA_TYPE_req MT_CHECK_CA_TYPE_req)
        {
            SI_CHECK_CA_TYPE_inRequest inValue = new SI_CHECK_CA_TYPE_inRequest();
            inValue.MT_CHECK_CA_TYPE_req = MT_CHECK_CA_TYPE_req;
            SI_CHECK_CA_TYPE_inResponse retVal = ((SI_CHECK_CA_TYPE_in)(this)).SI_CHECK_CA_TYPE_in(inValue);
            return retVal.MT_CHECK_CA_TYPE_resp;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SI_CHECK_CA_TYPE_inResponse> SI_CHECK_CA_TYPE_in.SI_CHECK_CA_TYPE_inAsync(SI_CHECK_CA_TYPE_inRequest request)
        {
            return base.Channel.SI_CHECK_CA_TYPE_inAsync(request);
        }
        
        public System.Threading.Tasks.Task<SI_CHECK_CA_TYPE_inResponse> SI_CHECK_CA_TYPE_inAsync(DT_CHECK_CA_TYPE_req MT_CHECK_CA_TYPE_req)
        {
            SI_CHECK_CA_TYPE_inRequest inValue = new SI_CHECK_CA_TYPE_inRequest();
            inValue.MT_CHECK_CA_TYPE_req = MT_CHECK_CA_TYPE_req;
            return ((SI_CHECK_CA_TYPE_in)(this)).SI_CHECK_CA_TYPE_inAsync(inValue);
        }
    }
}