//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_compstatnewService_Website
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://aeml.com/Web", ConfigurationName="SI_compstatnewService_Website.SI_compstatnew")]
    public interface SI_compstatnew
    {
        
        // CODEGEN: Generating message contract since the operation SI_compstatnew is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        SI_compstatnewService_Website.SI_compstatnewResponse SI_compstatnew(SI_compstatnewService_Website.SI_compstatnewRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<SI_compstatnewService_Website.SI_compstatnewResponse> SI_compstatnewAsync(SI_compstatnewService_Website.SI_compstatnewRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aeml.com/Web")]
    public partial class DT_compstatnew_Req
    {
        
        private string mONTHField;
        
        private DT_compstatnew_ReqItem[] iT_INPUTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MONTH
        {
            get
            {
                return this.mONTHField;
            }
            set
            {
                this.mONTHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_compstatnew_ReqItem[] IT_INPUT
        {
            get
            {
                return this.iT_INPUTField;
            }
            set
            {
                this.iT_INPUTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://aeml.com/Web")]
    public partial class DT_compstatnew_ReqItem
    {
        
        private string vKONTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string VKONT
        {
            get
            {
                return this.vKONTField;
            }
            set
            {
                this.vKONTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZBAPI_OUTPUT_ST
    {
        
        private string aUFNRField;
        
        private string eRDATField;
        
        private string iDAT2Field;
        
        private string vKONTField;
        
        private string aUARTField;
        
        private string iLARTField;
        
        private string zCOMPTYPField;
        
        private string iPHASField;
        
        private string mNGRPField;
        
        private string mNCODField;
        
        private string cOMPLAINT_STATUSField;
        
        private string gLTRPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string AUFNR
        {
            get
            {
                return this.aUFNRField;
            }
            set
            {
                this.aUFNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ERDAT
        {
            get
            {
                return this.eRDATField;
            }
            set
            {
                this.eRDATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string IDAT2
        {
            get
            {
                return this.iDAT2Field;
            }
            set
            {
                this.iDAT2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string VKONT
        {
            get
            {
                return this.vKONTField;
            }
            set
            {
                this.vKONTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string AUART
        {
            get
            {
                return this.aUARTField;
            }
            set
            {
                this.aUARTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ILART
        {
            get
            {
                return this.iLARTField;
            }
            set
            {
                this.iLARTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ZCOMPTYP
        {
            get
            {
                return this.zCOMPTYPField;
            }
            set
            {
                this.zCOMPTYPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string IPHAS
        {
            get
            {
                return this.iPHASField;
            }
            set
            {
                this.iPHASField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string MNGRP
        {
            get
            {
                return this.mNGRPField;
            }
            set
            {
                this.mNGRPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string MNCOD
        {
            get
            {
                return this.mNCODField;
            }
            set
            {
                this.mNCODField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string COMPLAINT_STATUS
        {
            get
            {
                return this.cOMPLAINT_STATUSField;
            }
            set
            {
                this.cOMPLAINT_STATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string GLTRP
        {
            get
            {
                return this.gLTRPField;
            }
            set
            {
                this.gLTRPField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZBAPI_COMP_STATIMPORT_ST
    {
        
        private string vKONTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string VKONT
        {
            get
            {
                return this.vKONTField;
            }
            set
            {
                this.vKONTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZBAPI_COMP_STATUS_NEWResponse
    {
        
        private ZBAPI_COMP_STATIMPORT_ST[] iT_INPUTField;
        
        private ZBAPI_OUTPUT_ST[] iT_OUTPUTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZBAPI_COMP_STATIMPORT_ST[] IT_INPUT
        {
            get
            {
                return this.iT_INPUTField;
            }
            set
            {
                this.iT_INPUTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZBAPI_OUTPUT_ST[] IT_OUTPUT
        {
            get
            {
                return this.iT_OUTPUTField;
            }
            set
            {
                this.iT_OUTPUTField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_compstatnewRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://aeml.com/Web", Order=0)]
        public SI_compstatnewService_Website.DT_compstatnew_Req MT_compstatnew_Req;
        
        public SI_compstatnewRequest()
        {
        }
        
        public SI_compstatnewRequest(SI_compstatnewService_Website.DT_compstatnew_Req MT_compstatnew_Req)
        {
            this.MT_compstatnew_Req = MT_compstatnew_Req;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_compstatnewResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ZBAPI_COMP_STATUS_NEW.Response", Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ZBAPI_COMP_STATUS_NEW.Response")]
        public SI_compstatnewService_Website.ZBAPI_COMP_STATUS_NEWResponse ZBAPI_COMP_STATUS_NEWResponse;
        
        public SI_compstatnewResponse()
        {
        }
        
        public SI_compstatnewResponse(SI_compstatnewService_Website.ZBAPI_COMP_STATUS_NEWResponse ZBAPI_COMP_STATUS_NEWResponse)
        {
            this.ZBAPI_COMP_STATUS_NEWResponse = ZBAPI_COMP_STATUS_NEWResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_compstatnewChannel : SI_compstatnewService_Website.SI_compstatnew, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_compstatnewClient : System.ServiceModel.ClientBase<SI_compstatnewService_Website.SI_compstatnew>, SI_compstatnewService_Website.SI_compstatnew
    {
        
        public SI_compstatnewClient()
        {
        }
        
        public SI_compstatnewClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public SI_compstatnewClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public SI_compstatnewClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public SI_compstatnewClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SI_compstatnewService_Website.SI_compstatnewResponse SI_compstatnewService_Website.SI_compstatnew.SI_compstatnew(SI_compstatnewService_Website.SI_compstatnewRequest request)
        {
            return base.Channel.SI_compstatnew(request);
        }
        
        public SI_compstatnewService_Website.ZBAPI_COMP_STATUS_NEWResponse SI_compstatnew(SI_compstatnewService_Website.DT_compstatnew_Req MT_compstatnew_Req)
        {
            SI_compstatnewService_Website.SI_compstatnewRequest inValue = new SI_compstatnewService_Website.SI_compstatnewRequest();
            inValue.MT_compstatnew_Req = MT_compstatnew_Req;
            SI_compstatnewService_Website.SI_compstatnewResponse retVal = ((SI_compstatnewService_Website.SI_compstatnew)(this)).SI_compstatnew(inValue);
            return retVal.ZBAPI_COMP_STATUS_NEWResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SI_compstatnewService_Website.SI_compstatnewResponse> SI_compstatnewService_Website.SI_compstatnew.SI_compstatnewAsync(SI_compstatnewService_Website.SI_compstatnewRequest request)
        {
            return base.Channel.SI_compstatnewAsync(request);
        }
        
        public System.Threading.Tasks.Task<SI_compstatnewService_Website.SI_compstatnewResponse> SI_compstatnewAsync(SI_compstatnewService_Website.DT_compstatnew_Req MT_compstatnew_Req)
        {
            SI_compstatnewService_Website.SI_compstatnewRequest inValue = new SI_compstatnewService_Website.SI_compstatnewRequest();
            inValue.MT_compstatnew_Req = MT_compstatnew_Req;
            return ((SI_compstatnewService_Website.SI_compstatnew)(this)).SI_compstatnewAsync(inValue);
        }
    }
}
