//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_CreateCaseStreetService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://rel.com/xi/RelMobApp/CRM", ConfigurationName="SI_CreateCaseStreetService.SI_CreateCaseStreet")]
    public interface SI_CreateCaseStreet
    {
        
        // CODEGEN: Generating message contract since the operation SI_CreateCaseStreet is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        SI_CreateCaseStreetService.SI_CreateCaseStreetResponse SI_CreateCaseStreet(SI_CreateCaseStreetService.SI_CreateCaseStreetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<SI_CreateCaseStreetService.SI_CreateCaseStreetResponse> SI_CreateCaseStreetAsync(SI_CreateCaseStreetService.SI_CreateCaseStreetRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rel.com/xi/RelMobApp/CRM")]
    public partial class DT_CreateCase_Req
    {
        
        private string actualAddress1Field;
        
        private string actualAddress2Field;
        
        private string actualAddress3Field;
        
        private string actualCreationDateField;
        
        private string actualEmailAddressField;
        
        private string actualMobileNumberField;
        
        private string actualNameField;
        
        private string actualTelephoneNumberField;
        
        private string areaDetailsField;
        
        private string bpField;
        
        private string bPTypeField;
        
        private string cANumberField;
        
        private string closureDateField;
        
        private string complaintSubTypeField;
        
        private string complaintSusSubTypeField;
        
        private string complaintTypeField;
        
        private string consumerTypeField;
        
        private string contractNumberField;
        
        private string installationField;
        
        private string landMarkField;
        
        private string meterField;
        
        private string notificationNoField;
        
        private string orderStatusField;
        
        private string orderNumberField;
        
        private string orderTypeField;
        
        private string pMActivityField;
        
        private string pillarnoField;
        
        private string plannerGroupField;
        
        private string problemCodeField;
        
        private string processingGroupField;
        
        private string rccField;
        
        private string remarkField;
        
        private string sourceField;
        
        private string streetlightPolenoField;
        
        private string workCenterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ActualAddress1
        {
            get
            {
                return this.actualAddress1Field;
            }
            set
            {
                this.actualAddress1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ActualAddress2
        {
            get
            {
                return this.actualAddress2Field;
            }
            set
            {
                this.actualAddress2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ActualAddress3
        {
            get
            {
                return this.actualAddress3Field;
            }
            set
            {
                this.actualAddress3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ActualCreationDate
        {
            get
            {
                return this.actualCreationDateField;
            }
            set
            {
                this.actualCreationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ActualEmailAddress
        {
            get
            {
                return this.actualEmailAddressField;
            }
            set
            {
                this.actualEmailAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ActualMobileNumber
        {
            get
            {
                return this.actualMobileNumberField;
            }
            set
            {
                this.actualMobileNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ActualName
        {
            get
            {
                return this.actualNameField;
            }
            set
            {
                this.actualNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string ActualTelephoneNumber
        {
            get
            {
                return this.actualTelephoneNumberField;
            }
            set
            {
                this.actualTelephoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string AreaDetails
        {
            get
            {
                return this.areaDetailsField;
            }
            set
            {
                this.areaDetailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string BP
        {
            get
            {
                return this.bpField;
            }
            set
            {
                this.bpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string BPType
        {
            get
            {
                return this.bPTypeField;
            }
            set
            {
                this.bPTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string CANumber
        {
            get
            {
                return this.cANumberField;
            }
            set
            {
                this.cANumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string ClosureDate
        {
            get
            {
                return this.closureDateField;
            }
            set
            {
                this.closureDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string ComplaintSubType
        {
            get
            {
                return this.complaintSubTypeField;
            }
            set
            {
                this.complaintSubTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string ComplaintSusSubType
        {
            get
            {
                return this.complaintSusSubTypeField;
            }
            set
            {
                this.complaintSusSubTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string ComplaintType
        {
            get
            {
                return this.complaintTypeField;
            }
            set
            {
                this.complaintTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string ConsumerType
        {
            get
            {
                return this.consumerTypeField;
            }
            set
            {
                this.consumerTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string ContractNumber
        {
            get
            {
                return this.contractNumberField;
            }
            set
            {
                this.contractNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string Installation
        {
            get
            {
                return this.installationField;
            }
            set
            {
                this.installationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string LandMark
        {
            get
            {
                return this.landMarkField;
            }
            set
            {
                this.landMarkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string Meter
        {
            get
            {
                return this.meterField;
            }
            set
            {
                this.meterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string NotificationNo
        {
            get
            {
                return this.notificationNoField;
            }
            set
            {
                this.notificationNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string OrderStatus
        {
            get
            {
                return this.orderStatusField;
            }
            set
            {
                this.orderStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string OrderNumber
        {
            get
            {
                return this.orderNumberField;
            }
            set
            {
                this.orderNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string OrderType
        {
            get
            {
                return this.orderTypeField;
            }
            set
            {
                this.orderTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string PMActivity
        {
            get
            {
                return this.pMActivityField;
            }
            set
            {
                this.pMActivityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string Pillarno
        {
            get
            {
                return this.pillarnoField;
            }
            set
            {
                this.pillarnoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string PlannerGroup
        {
            get
            {
                return this.plannerGroupField;
            }
            set
            {
                this.plannerGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string ProblemCode
        {
            get
            {
                return this.problemCodeField;
            }
            set
            {
                this.problemCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string ProcessingGroup
        {
            get
            {
                return this.processingGroupField;
            }
            set
            {
                this.processingGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string Rcc
        {
            get
            {
                return this.rccField;
            }
            set
            {
                this.rccField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string Remark
        {
            get
            {
                return this.remarkField;
            }
            set
            {
                this.remarkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string Source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string StreetlightPoleno
        {
            get
            {
                return this.streetlightPolenoField;
            }
            set
            {
                this.streetlightPolenoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string WorkCenter
        {
            get
            {
                return this.workCenterField;
            }
            set
            {
                this.workCenterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rel.com/xi/RelMobApp/CRM")]
    public partial class DT_CreateCase_RespReturnResp
    {
        
        private string caseNumberField;
        
        private int respCodeField;
        
        private bool respCodeFieldSpecified;
        
        private string respMsgField;
        
        private string errorMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CaseNumber
        {
            get
            {
                return this.caseNumberField;
            }
            set
            {
                this.caseNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int RespCode
        {
            get
            {
                return this.respCodeField;
            }
            set
            {
                this.respCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RespCodeSpecified
        {
            get
            {
                return this.respCodeFieldSpecified;
            }
            set
            {
                this.respCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string RespMsg
        {
            get
            {
                return this.respMsgField;
            }
            set
            {
                this.respMsgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ErrorMsg
        {
            get
            {
                return this.errorMsgField;
            }
            set
            {
                this.errorMsgField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_CreateCaseStreetRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rel.com/xi/RelMobApp/CRM", Order=0)]
        public SI_CreateCaseStreetService.DT_CreateCase_Req MT_CreateCaseStreet_Req;
        
        public SI_CreateCaseStreetRequest()
        {
        }
        
        public SI_CreateCaseStreetRequest(SI_CreateCaseStreetService.DT_CreateCase_Req MT_CreateCaseStreet_Req)
        {
            this.MT_CreateCaseStreet_Req = MT_CreateCaseStreet_Req;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_CreateCaseStreetResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rel.com/xi/SAPISU/CRM_DYN", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ReturnResp", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SI_CreateCaseStreetService.DT_CreateCase_RespReturnResp[] MT_CreateCase_Resp;
        
        public SI_CreateCaseStreetResponse()
        {
        }
        
        public SI_CreateCaseStreetResponse(SI_CreateCaseStreetService.DT_CreateCase_RespReturnResp[] MT_CreateCase_Resp)
        {
            this.MT_CreateCase_Resp = MT_CreateCase_Resp;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_CreateCaseStreetChannel : SI_CreateCaseStreetService.SI_CreateCaseStreet, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_CreateCaseStreetClient : System.ServiceModel.ClientBase<SI_CreateCaseStreetService.SI_CreateCaseStreet>, SI_CreateCaseStreetService.SI_CreateCaseStreet
    {
        
        public SI_CreateCaseStreetClient()
        {
        }
        
        public SI_CreateCaseStreetClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public SI_CreateCaseStreetClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public SI_CreateCaseStreetClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public SI_CreateCaseStreetClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SI_CreateCaseStreetService.SI_CreateCaseStreetResponse SI_CreateCaseStreetService.SI_CreateCaseStreet.SI_CreateCaseStreet(SI_CreateCaseStreetService.SI_CreateCaseStreetRequest request)
        {
            return base.Channel.SI_CreateCaseStreet(request);
        }
        
        public SI_CreateCaseStreetService.DT_CreateCase_RespReturnResp[] SI_CreateCaseStreet(SI_CreateCaseStreetService.DT_CreateCase_Req MT_CreateCaseStreet_Req)
        {
            SI_CreateCaseStreetService.SI_CreateCaseStreetRequest inValue = new SI_CreateCaseStreetService.SI_CreateCaseStreetRequest();
            inValue.MT_CreateCaseStreet_Req = MT_CreateCaseStreet_Req;
            SI_CreateCaseStreetService.SI_CreateCaseStreetResponse retVal = ((SI_CreateCaseStreetService.SI_CreateCaseStreet)(this)).SI_CreateCaseStreet(inValue);
            return retVal.MT_CreateCase_Resp;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SI_CreateCaseStreetService.SI_CreateCaseStreetResponse> SI_CreateCaseStreetService.SI_CreateCaseStreet.SI_CreateCaseStreetAsync(SI_CreateCaseStreetService.SI_CreateCaseStreetRequest request)
        {
            return base.Channel.SI_CreateCaseStreetAsync(request);
        }
        
        public System.Threading.Tasks.Task<SI_CreateCaseStreetService.SI_CreateCaseStreetResponse> SI_CreateCaseStreetAsync(SI_CreateCaseStreetService.DT_CreateCase_Req MT_CreateCaseStreet_Req)
        {
            SI_CreateCaseStreetService.SI_CreateCaseStreetRequest inValue = new SI_CreateCaseStreetService.SI_CreateCaseStreetRequest();
            inValue.MT_CreateCaseStreet_Req = MT_CreateCaseStreet_Req;
            return ((SI_CreateCaseStreetService.SI_CreateCaseStreet)(this)).SI_CreateCaseStreetAsync(inValue);
        }
    }
}
