//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8944
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_EMIOptinService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://aeml.com/Web", ConfigurationName="SI_EMIOptinService.SI_EMIOptin")]
    public interface SI_EMIOptin
    {
        
        // CODEGEN: Generating message contract since the operation SI_EMIOptin is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        SI_EMIOptinService.SI_EMIOptinResponse SI_EMIOptin(SI_EMIOptinService.SI_EMIOptinRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aeml.com/Web")]
    public partial class DT_EMIOptin_Req
    {
        
        private string vKONTField;
        
        private string sOURCEField;
        
        private string pROCESS_TYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string VKONT
        {
            get
            {
                return this.vKONTField;
            }
            set
            {
                this.vKONTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string SOURCE
        {
            get
            {
                return this.sOURCEField;
            }
            set
            {
                this.sOURCEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string PROCESS_TYPE
        {
            get
            {
                return this.pROCESS_TYPEField;
            }
            set
            {
                this.pROCESS_TYPEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZST_EMI_OUTPUT
    {
        
        private string vKONTField;
        
        private string nAMEField;
        
        private string iNVOICE_NOField;
        
        private string bILL_MONTHField;
        
        private decimal tOT_OUTSTANDINGField;
        
        private bool tOT_OUTSTANDINGFieldSpecified;
        
        private string dUE_DATEField;
        
        private decimal iNST_AMNTField;
        
        private bool iNST_AMNTFieldSpecified;
        
        private string sTATUSField;
        
        private string rEMARKSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string VKONT
        {
            get
            {
                return this.vKONTField;
            }
            set
            {
                this.vKONTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string NAME
        {
            get
            {
                return this.nAMEField;
            }
            set
            {
                this.nAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string INVOICE_NO
        {
            get
            {
                return this.iNVOICE_NOField;
            }
            set
            {
                this.iNVOICE_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string BILL_MONTH
        {
            get
            {
                return this.bILL_MONTHField;
            }
            set
            {
                this.bILL_MONTHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal TOT_OUTSTANDING
        {
            get
            {
                return this.tOT_OUTSTANDINGField;
            }
            set
            {
                this.tOT_OUTSTANDINGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TOT_OUTSTANDINGSpecified
        {
            get
            {
                return this.tOT_OUTSTANDINGFieldSpecified;
            }
            set
            {
                this.tOT_OUTSTANDINGFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string DUE_DATE
        {
            get
            {
                return this.dUE_DATEField;
            }
            set
            {
                this.dUE_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal INST_AMNT
        {
            get
            {
                return this.iNST_AMNTField;
            }
            set
            {
                this.iNST_AMNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool INST_AMNTSpecified
        {
            get
            {
                return this.iNST_AMNTFieldSpecified;
            }
            set
            {
                this.iNST_AMNTFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string STATUS
        {
            get
            {
                return this.sTATUSField;
            }
            set
            {
                this.sTATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string REMARKS
        {
            get
            {
                return this.rEMARKSField;
            }
            set
            {
                this.rEMARKSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZBAPI_BI_EMIOPTINDETAILSResponse
    {
        
        private ZST_EMI_OUTPUT eMI_OUTPUTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ZST_EMI_OUTPUT EMI_OUTPUT
        {
            get
            {
                return this.eMI_OUTPUTField;
            }
            set
            {
                this.eMI_OUTPUTField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_EMIOptinRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://aeml.com/Web", Order=0)]
        public SI_EMIOptinService.DT_EMIOptin_Req MT_EMIOption_Req;
        
        public SI_EMIOptinRequest()
        {
        }
        
        public SI_EMIOptinRequest(SI_EMIOptinService.DT_EMIOptin_Req MT_EMIOption_Req)
        {
            this.MT_EMIOption_Req = MT_EMIOption_Req;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_EMIOptinResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ZBAPI_BI_EMIOPTINDETAILS.Response", Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ZBAPI_BI_EMIOPTINDETAILS.Response")]
        public SI_EMIOptinService.ZBAPI_BI_EMIOPTINDETAILSResponse ZBAPI_BI_EMIOPTINDETAILSResponse;
        
        public SI_EMIOptinResponse()
        {
        }
        
        public SI_EMIOptinResponse(SI_EMIOptinService.ZBAPI_BI_EMIOPTINDETAILSResponse ZBAPI_BI_EMIOPTINDETAILSResponse)
        {
            this.ZBAPI_BI_EMIOPTINDETAILSResponse = ZBAPI_BI_EMIOPTINDETAILSResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface SI_EMIOptinChannel : SI_EMIOptinService.SI_EMIOptin, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SI_EMIOptinClient : System.ServiceModel.ClientBase<SI_EMIOptinService.SI_EMIOptin>, SI_EMIOptinService.SI_EMIOptin
    {
        
        public SI_EMIOptinClient()
        {
        }
        
        public SI_EMIOptinClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public SI_EMIOptinClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public SI_EMIOptinClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public SI_EMIOptinClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SI_EMIOptinService.SI_EMIOptinResponse SI_EMIOptinService.SI_EMIOptin.SI_EMIOptin(SI_EMIOptinService.SI_EMIOptinRequest request)
        {
            return base.Channel.SI_EMIOptin(request);
        }
        
        public SI_EMIOptinService.ZBAPI_BI_EMIOPTINDETAILSResponse SI_EMIOptin(SI_EMIOptinService.DT_EMIOptin_Req MT_EMIOption_Req)
        {
            SI_EMIOptinService.SI_EMIOptinRequest inValue = new SI_EMIOptinService.SI_EMIOptinRequest();
            inValue.MT_EMIOption_Req = MT_EMIOption_Req;
            SI_EMIOptinService.SI_EMIOptinResponse retVal = ((SI_EMIOptinService.SI_EMIOptin)(this)).SI_EMIOptin(inValue);
            return retVal.ZBAPI_BI_EMIOPTINDETAILSResponse;
        }
    }
}
