//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_FI_WEB_ITAX_Website
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://aeml.com/Web", ConfigurationName="SI_FI_WEB_ITAX_Website.SI_FI_WEB_ITAX")]
    public interface SI_FI_WEB_ITAX
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        SI_FI_WEB_ITAX_Website.SI_FI_WEB_ITAXResponse SI_FI_WEB_ITAX(SI_FI_WEB_ITAX_Website.SI_FI_WEB_ITAXRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<SI_FI_WEB_ITAX_Website.SI_FI_WEB_ITAXResponse> SI_FI_WEB_ITAXAsync(SI_FI_WEB_ITAX_Website.SI_FI_WEB_ITAXRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZST_FI_WEB_ITAX
    {
        
        private string zFLAG_DECLARATIONField;
        
        private string zFLAG_INTIMATIONField;
        
        private string zFLAGField;
        
        private string zSOURCEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ZFLAG_DECLARATION
        {
            get
            {
                return this.zFLAG_DECLARATIONField;
            }
            set
            {
                this.zFLAG_DECLARATIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ZFLAG_INTIMATION
        {
            get
            {
                return this.zFLAG_INTIMATIONField;
            }
            set
            {
                this.zFLAG_INTIMATIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ZFLAG
        {
            get
            {
                return this.zFLAGField;
            }
            set
            {
                this.zFLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=3)]
        public string ZSOURCE
        {
            get
            {
                return this.zSOURCEField;
            }
            set
            {
                this.zSOURCEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZST_FI_WEB_ITAX_EXP
    {
        
        private string zFLAG_UPD_ZDECLARATIONField;
        
        private string zFLAG_UPD_ZINTIMATIONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ZFLAG_UPD_ZDECLARATION
        {
            get
            {
                return this.zFLAG_UPD_ZDECLARATIONField;
            }
            set
            {
                this.zFLAG_UPD_ZDECLARATIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ZFLAG_UPD_ZINTIMATION
        {
            get
            {
                return this.zFLAG_UPD_ZINTIMATIONField;
            }
            set
            {
                this.zFLAG_UPD_ZINTIMATIONField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZFINTIMATION
    {
        
        private string mANDTField;
        
        private string vKONTField;
        
        private string pAYMENT_DATEField;
        
        private string pAN_NOField;
        
        private decimal bILL_PAYABLE_AMTField;
        
        private bool bILL_PAYABLE_AMTFieldSpecified;
        
        private decimal pAYMENT_AMTField;
        
        private bool pAYMENT_AMTFieldSpecified;
        
        private string tDS_RATEField;
        
        private decimal tDS_AMOUNTField;
        
        private bool tDS_AMOUNTFieldSpecified;
        
        private string dOCUMENT_NOField;
        
        private string pOSTING_DATEField;
        
        private string sOURCEField;
        
        private string uSER_IDField;
        
        private string cREATED_ONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MANDT
        {
            get
            {
                return this.mANDTField;
            }
            set
            {
                this.mANDTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string VKONT
        {
            get
            {
                return this.vKONTField;
            }
            set
            {
                this.vKONTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string PAYMENT_DATE
        {
            get
            {
                return this.pAYMENT_DATEField;
            }
            set
            {
                this.pAYMENT_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string PAN_NO
        {
            get
            {
                return this.pAN_NOField;
            }
            set
            {
                this.pAN_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal BILL_PAYABLE_AMT
        {
            get
            {
                return this.bILL_PAYABLE_AMTField;
            }
            set
            {
                this.bILL_PAYABLE_AMTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BILL_PAYABLE_AMTSpecified
        {
            get
            {
                return this.bILL_PAYABLE_AMTFieldSpecified;
            }
            set
            {
                this.bILL_PAYABLE_AMTFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal PAYMENT_AMT
        {
            get
            {
                return this.pAYMENT_AMTField;
            }
            set
            {
                this.pAYMENT_AMTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PAYMENT_AMTSpecified
        {
            get
            {
                return this.pAYMENT_AMTFieldSpecified;
            }
            set
            {
                this.pAYMENT_AMTFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string TDS_RATE
        {
            get
            {
                return this.tDS_RATEField;
            }
            set
            {
                this.tDS_RATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public decimal TDS_AMOUNT
        {
            get
            {
                return this.tDS_AMOUNTField;
            }
            set
            {
                this.tDS_AMOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TDS_AMOUNTSpecified
        {
            get
            {
                return this.tDS_AMOUNTFieldSpecified;
            }
            set
            {
                this.tDS_AMOUNTFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string DOCUMENT_NO
        {
            get
            {
                return this.dOCUMENT_NOField;
            }
            set
            {
                this.dOCUMENT_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string POSTING_DATE
        {
            get
            {
                return this.pOSTING_DATEField;
            }
            set
            {
                this.pOSTING_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=10)]
        public string SOURCE
        {
            get
            {
                return this.sOURCEField;
            }
            set
            {
                this.sOURCEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string USER_ID
        {
            get
            {
                return this.uSER_IDField;
            }
            set
            {
                this.uSER_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string CREATED_ON
        {
            get
            {
                return this.cREATED_ONField;
            }
            set
            {
                this.cREATED_ONField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZFIDECLARATION
    {
        
        private string mANDTField;
        
        private string vKONTField;
        
        private string zDECLARATION_TYPEField;
        
        private string dATE_TOField;
        
        private string dATE_FROMField;
        
        private string zOPTIONField;
        
        private string pAN_NOField;
        
        private string aADHAR_NOField;
        
        private string cREATED_ONField;
        
        private string sOURCEField;
        
        private string uSER_IDField;
        
        private string fIN_YR1Field;
        
        private string iT_ACK_NO1Field;
        
        private string fILING_DATE1Field;
        
        private string fIN_YR2Field;
        
        private string iT_ACK_NO2Field;
        
        private string fILING_DATE2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MANDT
        {
            get
            {
                return this.mANDTField;
            }
            set
            {
                this.mANDTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string VKONT
        {
            get
            {
                return this.vKONTField;
            }
            set
            {
                this.vKONTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ZDECLARATION_TYPE
        {
            get
            {
                return this.zDECLARATION_TYPEField;
            }
            set
            {
                this.zDECLARATION_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string DATE_TO
        {
            get
            {
                return this.dATE_TOField;
            }
            set
            {
                this.dATE_TOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string DATE_FROM
        {
            get
            {
                return this.dATE_FROMField;
            }
            set
            {
                this.dATE_FROMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ZOPTION
        {
            get
            {
                return this.zOPTIONField;
            }
            set
            {
                this.zOPTIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string PAN_NO
        {
            get
            {
                return this.pAN_NOField;
            }
            set
            {
                this.pAN_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string AADHAR_NO
        {
            get
            {
                return this.aADHAR_NOField;
            }
            set
            {
                this.aADHAR_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string CREATED_ON
        {
            get
            {
                return this.cREATED_ONField;
            }
            set
            {
                this.cREATED_ONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=9)]
        public string SOURCE
        {
            get
            {
                return this.sOURCEField;
            }
            set
            {
                this.sOURCEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string USER_ID
        {
            get
            {
                return this.uSER_IDField;
            }
            set
            {
                this.uSER_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string FIN_YR1
        {
            get
            {
                return this.fIN_YR1Field;
            }
            set
            {
                this.fIN_YR1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string IT_ACK_NO1
        {
            get
            {
                return this.iT_ACK_NO1Field;
            }
            set
            {
                this.iT_ACK_NO1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string FILING_DATE1
        {
            get
            {
                return this.fILING_DATE1Field;
            }
            set
            {
                this.fILING_DATE1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string FIN_YR2
        {
            get
            {
                return this.fIN_YR2Field;
            }
            set
            {
                this.fIN_YR2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string IT_ACK_NO2
        {
            get
            {
                return this.iT_ACK_NO2Field;
            }
            set
            {
                this.iT_ACK_NO2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string FILING_DATE2
        {
            get
            {
                return this.fILING_DATE2Field;
            }
            set
            {
                this.fILING_DATE2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class BAPIRET2
    {
        
        private string tYPEField;
        
        private string idField;
        
        private string nUMBERField;
        
        private string mESSAGEField;
        
        private string lOG_NOField;
        
        private string lOG_MSG_NOField;
        
        private string mESSAGE_V1Field;
        
        private string mESSAGE_V2Field;
        
        private string mESSAGE_V3Field;
        
        private string mESSAGE_V4Field;
        
        private string pARAMETERField;
        
        private string rOWField;
        
        private string fIELDField;
        
        private string sYSTEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TYPE
        {
            get
            {
                return this.tYPEField;
            }
            set
            {
                this.tYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NUMBER
        {
            get
            {
                return this.nUMBERField;
            }
            set
            {
                this.nUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MESSAGE
        {
            get
            {
                return this.mESSAGEField;
            }
            set
            {
                this.mESSAGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string LOG_NO
        {
            get
            {
                return this.lOG_NOField;
            }
            set
            {
                this.lOG_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string LOG_MSG_NO
        {
            get
            {
                return this.lOG_MSG_NOField;
            }
            set
            {
                this.lOG_MSG_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MESSAGE_V1
        {
            get
            {
                return this.mESSAGE_V1Field;
            }
            set
            {
                this.mESSAGE_V1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string MESSAGE_V2
        {
            get
            {
                return this.mESSAGE_V2Field;
            }
            set
            {
                this.mESSAGE_V2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string MESSAGE_V3
        {
            get
            {
                return this.mESSAGE_V3Field;
            }
            set
            {
                this.mESSAGE_V3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string MESSAGE_V4
        {
            get
            {
                return this.mESSAGE_V4Field;
            }
            set
            {
                this.mESSAGE_V4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string PARAMETER
        {
            get
            {
                return this.pARAMETERField;
            }
            set
            {
                this.pARAMETERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=11)]
        public string ROW
        {
            get
            {
                return this.rOWField;
            }
            set
            {
                this.rOWField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string FIELD
        {
            get
            {
                return this.fIELDField;
            }
            set
            {
                this.fIELDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string SYSTEM
        {
            get
            {
                return this.sYSTEMField;
            }
            set
            {
                this.sYSTEMField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ZBAPI_FI_WEB_ITAX", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class SI_FI_WEB_ITAXRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SI_FI_WEB_ITAX_Website.ZST_FI_WEB_ITAX IM_INPUT;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SI_FI_WEB_ITAX_Website.BAPIRET2[] IT_RETURN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=2)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SI_FI_WEB_ITAX_Website.ZFIDECLARATION[] IT_ZFIDECLARATION;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=3)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SI_FI_WEB_ITAX_Website.ZFINTIMATION[] IT_ZFINTIMATION;
        
        public SI_FI_WEB_ITAXRequest()
        {
        }
        
        public SI_FI_WEB_ITAXRequest(SI_FI_WEB_ITAX_Website.ZST_FI_WEB_ITAX IM_INPUT, SI_FI_WEB_ITAX_Website.BAPIRET2[] IT_RETURN, SI_FI_WEB_ITAX_Website.ZFIDECLARATION[] IT_ZFIDECLARATION, SI_FI_WEB_ITAX_Website.ZFINTIMATION[] IT_ZFINTIMATION)
        {
            this.IM_INPUT = IM_INPUT;
            this.IT_RETURN = IT_RETURN;
            this.IT_ZFIDECLARATION = IT_ZFIDECLARATION;
            this.IT_ZFINTIMATION = IT_ZFINTIMATION;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ZBAPI_FI_WEB_ITAX.Response", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class SI_FI_WEB_ITAXResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SI_FI_WEB_ITAX_Website.ZST_FI_WEB_ITAX_EXP EX_OUTPUT;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SI_FI_WEB_ITAX_Website.BAPIRET2[] IT_RETURN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=2)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SI_FI_WEB_ITAX_Website.ZFIDECLARATION[] IT_ZFIDECLARATION;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=3)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SI_FI_WEB_ITAX_Website.ZFINTIMATION[] IT_ZFINTIMATION;
        
        public SI_FI_WEB_ITAXResponse()
        {
        }
        
        public SI_FI_WEB_ITAXResponse(SI_FI_WEB_ITAX_Website.ZST_FI_WEB_ITAX_EXP EX_OUTPUT, SI_FI_WEB_ITAX_Website.BAPIRET2[] IT_RETURN, SI_FI_WEB_ITAX_Website.ZFIDECLARATION[] IT_ZFIDECLARATION, SI_FI_WEB_ITAX_Website.ZFINTIMATION[] IT_ZFINTIMATION)
        {
            this.EX_OUTPUT = EX_OUTPUT;
            this.IT_RETURN = IT_RETURN;
            this.IT_ZFIDECLARATION = IT_ZFIDECLARATION;
            this.IT_ZFINTIMATION = IT_ZFINTIMATION;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_FI_WEB_ITAXChannel : SI_FI_WEB_ITAX_Website.SI_FI_WEB_ITAX, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_FI_WEB_ITAXClient : System.ServiceModel.ClientBase<SI_FI_WEB_ITAX_Website.SI_FI_WEB_ITAX>, SI_FI_WEB_ITAX_Website.SI_FI_WEB_ITAX
    {
        
        public SI_FI_WEB_ITAXClient()
        {
        }
        
        public SI_FI_WEB_ITAXClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public SI_FI_WEB_ITAXClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public SI_FI_WEB_ITAXClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public SI_FI_WEB_ITAXClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SI_FI_WEB_ITAX_Website.SI_FI_WEB_ITAXResponse SI_FI_WEB_ITAX_Website.SI_FI_WEB_ITAX.SI_FI_WEB_ITAX(SI_FI_WEB_ITAX_Website.SI_FI_WEB_ITAXRequest request)
        {
            return base.Channel.SI_FI_WEB_ITAX(request);
        }
        
        public SI_FI_WEB_ITAX_Website.ZST_FI_WEB_ITAX_EXP SI_FI_WEB_ITAX(SI_FI_WEB_ITAX_Website.ZST_FI_WEB_ITAX IM_INPUT, ref SI_FI_WEB_ITAX_Website.BAPIRET2[] IT_RETURN, ref SI_FI_WEB_ITAX_Website.ZFIDECLARATION[] IT_ZFIDECLARATION, ref SI_FI_WEB_ITAX_Website.ZFINTIMATION[] IT_ZFINTIMATION)
        {
            SI_FI_WEB_ITAX_Website.SI_FI_WEB_ITAXRequest inValue = new SI_FI_WEB_ITAX_Website.SI_FI_WEB_ITAXRequest();
            inValue.IM_INPUT = IM_INPUT;
            inValue.IT_RETURN = IT_RETURN;
            inValue.IT_ZFIDECLARATION = IT_ZFIDECLARATION;
            inValue.IT_ZFINTIMATION = IT_ZFINTIMATION;
            SI_FI_WEB_ITAX_Website.SI_FI_WEB_ITAXResponse retVal = ((SI_FI_WEB_ITAX_Website.SI_FI_WEB_ITAX)(this)).SI_FI_WEB_ITAX(inValue);
            IT_RETURN = retVal.IT_RETURN;
            IT_ZFIDECLARATION = retVal.IT_ZFIDECLARATION;
            IT_ZFINTIMATION = retVal.IT_ZFINTIMATION;
            return retVal.EX_OUTPUT;
        }
        
        public System.Threading.Tasks.Task<SI_FI_WEB_ITAX_Website.SI_FI_WEB_ITAXResponse> SI_FI_WEB_ITAXAsync(SI_FI_WEB_ITAX_Website.SI_FI_WEB_ITAXRequest request)
        {
            return base.Channel.SI_FI_WEB_ITAXAsync(request);
        }
    }
}
