//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://rel.com/xi/RelMobApp/GET_BILL_MONTH", ConfigurationName="SI_GET_BILL_MONTH_in")]
public interface SI_GET_BILL_MONTH_in
{
    
    // CODEGEN: Generating message contract since the operation SI_GET_BILL_MONTH_in is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    SI_GET_BILL_MONTH_inResponse SI_GET_BILL_MONTH_in(SI_GET_BILL_MONTH_inRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
    System.Threading.Tasks.Task<SI_GET_BILL_MONTH_inResponse> SI_GET_BILL_MONTH_inAsync(SI_GET_BILL_MONTH_inRequest request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rel.com/xi/RelMobApp/GET_BILL_MONTH")]
public partial class DT_GET_BILL_MONTH_req
{
    
    private string cONTRACT_ACCOUNTField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string CONTRACT_ACCOUNT
    {
        get
        {
            return this.cONTRACT_ACCOUNTField;
        }
        set
        {
            this.cONTRACT_ACCOUNTField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rel.com/xi/RelMobApp/GET_BILL_MONTH")]
public partial class DT_GET_BILL_MONTH_resp
{
    
    private DT_GET_BILL_MONTH_respItem[] bILL_DATAField;
    
    private DT_GET_BILL_MONTH_respItem1[] rETURNField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public DT_GET_BILL_MONTH_respItem[] BILL_DATA
    {
        get
        {
            return this.bILL_DATAField;
        }
        set
        {
            this.bILL_DATAField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public DT_GET_BILL_MONTH_respItem1[] RETURN
    {
        get
        {
            return this.rETURNField;
        }
        set
        {
            this.rETURNField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rel.com/xi/RelMobApp/GET_BILL_MONTH")]
public partial class DT_GET_BILL_MONTH_respItem
{
    
    private string cONTRACT_ACCOUNTField;
    
    private string iNVOICE_NOField;
    
    private string bILL_MONTHField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string CONTRACT_ACCOUNT
    {
        get
        {
            return this.cONTRACT_ACCOUNTField;
        }
        set
        {
            this.cONTRACT_ACCOUNTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string INVOICE_NO
    {
        get
        {
            return this.iNVOICE_NOField;
        }
        set
        {
            this.iNVOICE_NOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string BILL_MONTH
    {
        get
        {
            return this.bILL_MONTHField;
        }
        set
        {
            this.bILL_MONTHField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rel.com/xi/RelMobApp/GET_BILL_MONTH")]
public partial class DT_GET_BILL_MONTH_respItem1
{
    
    private string tYPEField;
    
    private string idField;
    
    private string nUMBERField;
    
    private string mESSAGEField;
    
    private string lOG_NOField;
    
    private string lOG_MSG_NOField;
    
    private string mESSAGE_V1Field;
    
    private string mESSAGE_V2Field;
    
    private string mESSAGE_V3Field;
    
    private string mESSAGE_V4Field;
    
    private string pARAMETERField;
    
    private string rOWField;
    
    private string fIELDField;
    
    private string sYSTEMField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string TYPE
    {
        get
        {
            return this.tYPEField;
        }
        set
        {
            this.tYPEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string ID
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string NUMBER
    {
        get
        {
            return this.nUMBERField;
        }
        set
        {
            this.nUMBERField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public string MESSAGE
    {
        get
        {
            return this.mESSAGEField;
        }
        set
        {
            this.mESSAGEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public string LOG_NO
    {
        get
        {
            return this.lOG_NOField;
        }
        set
        {
            this.lOG_NOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
    public string LOG_MSG_NO
    {
        get
        {
            return this.lOG_MSG_NOField;
        }
        set
        {
            this.lOG_MSG_NOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
    public string MESSAGE_V1
    {
        get
        {
            return this.mESSAGE_V1Field;
        }
        set
        {
            this.mESSAGE_V1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
    public string MESSAGE_V2
    {
        get
        {
            return this.mESSAGE_V2Field;
        }
        set
        {
            this.mESSAGE_V2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
    public string MESSAGE_V3
    {
        get
        {
            return this.mESSAGE_V3Field;
        }
        set
        {
            this.mESSAGE_V3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
    public string MESSAGE_V4
    {
        get
        {
            return this.mESSAGE_V4Field;
        }
        set
        {
            this.mESSAGE_V4Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
    public string PARAMETER
    {
        get
        {
            return this.pARAMETERField;
        }
        set
        {
            this.pARAMETERField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
    public string ROW
    {
        get
        {
            return this.rOWField;
        }
        set
        {
            this.rOWField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
    public string FIELD
    {
        get
        {
            return this.fIELDField;
        }
        set
        {
            this.fIELDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
    public string SYSTEM
    {
        get
        {
            return this.sYSTEMField;
        }
        set
        {
            this.sYSTEMField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class SI_GET_BILL_MONTH_inRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rel.com/xi/RelMobApp/GET_BILL_MONTH", Order=0)]
    public DT_GET_BILL_MONTH_req MT_GET_BILL_MONTH_req;
    
    public SI_GET_BILL_MONTH_inRequest()
    {
    }
    
    public SI_GET_BILL_MONTH_inRequest(DT_GET_BILL_MONTH_req MT_GET_BILL_MONTH_req)
    {
        this.MT_GET_BILL_MONTH_req = MT_GET_BILL_MONTH_req;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class SI_GET_BILL_MONTH_inResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rel.com/xi/RelMobApp/GET_BILL_MONTH", Order=0)]
    public DT_GET_BILL_MONTH_resp MT_GET_BILL_MONTH_resp;
    
    public SI_GET_BILL_MONTH_inResponse()
    {
    }
    
    public SI_GET_BILL_MONTH_inResponse(DT_GET_BILL_MONTH_resp MT_GET_BILL_MONTH_resp)
    {
        this.MT_GET_BILL_MONTH_resp = MT_GET_BILL_MONTH_resp;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface SI_GET_BILL_MONTH_inChannel : SI_GET_BILL_MONTH_in, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class SI_GET_BILL_MONTH_inClient : System.ServiceModel.ClientBase<SI_GET_BILL_MONTH_in>, SI_GET_BILL_MONTH_in
{
    
    public SI_GET_BILL_MONTH_inClient()
    {
    }
    
    public SI_GET_BILL_MONTH_inClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public SI_GET_BILL_MONTH_inClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SI_GET_BILL_MONTH_inClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SI_GET_BILL_MONTH_inClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    SI_GET_BILL_MONTH_inResponse SI_GET_BILL_MONTH_in.SI_GET_BILL_MONTH_in(SI_GET_BILL_MONTH_inRequest request)
    {
        return base.Channel.SI_GET_BILL_MONTH_in(request);
    }
    
    public DT_GET_BILL_MONTH_resp SI_GET_BILL_MONTH_in(DT_GET_BILL_MONTH_req MT_GET_BILL_MONTH_req)
    {
        SI_GET_BILL_MONTH_inRequest inValue = new SI_GET_BILL_MONTH_inRequest();
        inValue.MT_GET_BILL_MONTH_req = MT_GET_BILL_MONTH_req;
        SI_GET_BILL_MONTH_inResponse retVal = ((SI_GET_BILL_MONTH_in)(this)).SI_GET_BILL_MONTH_in(inValue);
        return retVal.MT_GET_BILL_MONTH_resp;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SI_GET_BILL_MONTH_inResponse> SI_GET_BILL_MONTH_in.SI_GET_BILL_MONTH_inAsync(SI_GET_BILL_MONTH_inRequest request)
    {
        return base.Channel.SI_GET_BILL_MONTH_inAsync(request);
    }
    
    public System.Threading.Tasks.Task<SI_GET_BILL_MONTH_inResponse> SI_GET_BILL_MONTH_inAsync(DT_GET_BILL_MONTH_req MT_GET_BILL_MONTH_req)
    {
        SI_GET_BILL_MONTH_inRequest inValue = new SI_GET_BILL_MONTH_inRequest();
        inValue.MT_GET_BILL_MONTH_req = MT_GET_BILL_MONTH_req;
        return ((SI_GET_BILL_MONTH_in)(this)).SI_GET_BILL_MONTH_inAsync(inValue);
    }
}
