//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://rel.com/xi/RelMobApp/MR_BI_GETLIST", ConfigurationName="SI_MR_BI_GETLIST_in")]
public interface SI_MR_BI_GETLIST_in
{
    
    // CODEGEN: Generating message contract since the operation SI_MR_BI_GETLIST_in is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    SI_MR_BI_GETLIST_inResponse SI_MR_BI_GETLIST_in(SI_MR_BI_GETLIST_inRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
    System.Threading.Tasks.Task<SI_MR_BI_GETLIST_inResponse> SI_MR_BI_GETLIST_inAsync(SI_MR_BI_GETLIST_inRequest request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rel.com/xi/RelMobApp/MR_BI_GETLIST")]
public partial class DT_MR_BI_GETLIST_req
{
    
    private string cA_NUMBERField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string CA_NUMBER
    {
        get
        {
            return this.cA_NUMBERField;
        }
        set
        {
            this.cA_NUMBERField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rel.com/xi/RelMobApp/MR_BI_GETLIST")]
public partial class DT_MR_BI_GETLIST_resp
{
    
    private string cONTACTField;
    
    private DT_MR_BI_GETLIST_respEXPORT eXPORTField;
    
    private DT_MR_BI_GETLIST_respItem[] jI_DETAILSField;
    
    private DT_MR_BI_GETLIST_respItem1[] mESSAGESField;
    
    private DT_MR_BI_GETLIST_respItem2[] rETURNField;
    
    private DT_MR_BI_GETLIST_respItem3[] sERIAL_NUMField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string CONTACT
    {
        get
        {
            return this.cONTACTField;
        }
        set
        {
            this.cONTACTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public DT_MR_BI_GETLIST_respEXPORT EXPORT
    {
        get
        {
            return this.eXPORTField;
        }
        set
        {
            this.eXPORTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public DT_MR_BI_GETLIST_respItem[] JI_DETAILS
    {
        get
        {
            return this.jI_DETAILSField;
        }
        set
        {
            this.jI_DETAILSField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public DT_MR_BI_GETLIST_respItem1[] MESSAGES
    {
        get
        {
            return this.mESSAGESField;
        }
        set
        {
            this.mESSAGESField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public DT_MR_BI_GETLIST_respItem2[] RETURN
    {
        get
        {
            return this.rETURNField;
        }
        set
        {
            this.rETURNField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public DT_MR_BI_GETLIST_respItem3[] SERIAL_NUM
    {
        get
        {
            return this.sERIAL_NUMField;
        }
        set
        {
            this.sERIAL_NUMField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rel.com/xi/RelMobApp/MR_BI_GETLIST")]
public partial class DT_MR_BI_GETLIST_respEXPORT
{
    
    private string bILL_MONTHField;
    
    private string v_ZWSTNDABField;
    
    private string nET_AMNTField;
    
    private string cURRENT_BILLField;
    
    private string rOUNDSUM_PAYField;
    
    private string pAY_DUE_DATEField;
    
    private string bRT_FORWARDField;
    
    private string cONSUMER_TYPEField;
    
    private string bILL_DATEField;
    
    private string tOTAL_CHARGESField;
    
    private string sTATUSField;
    
    private string tARIFFField;
    
    private string fLAGField;
    
    private string pAY_PPI_DATEField;
    
    private string pPI_BILL_AMTField;
    
    private string dUE_DATE_BILL_AMTField;
    
    private string dPC_BILL_AMTField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string BILL_MONTH
    {
        get
        {
            return this.bILL_MONTHField;
        }
        set
        {
            this.bILL_MONTHField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string V_ZWSTNDAB
    {
        get
        {
            return this.v_ZWSTNDABField;
        }
        set
        {
            this.v_ZWSTNDABField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string NET_AMNT
    {
        get
        {
            return this.nET_AMNTField;
        }
        set
        {
            this.nET_AMNTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public string CURRENT_BILL
    {
        get
        {
            return this.cURRENT_BILLField;
        }
        set
        {
            this.cURRENT_BILLField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public string ROUNDSUM_PAY
    {
        get
        {
            return this.rOUNDSUM_PAYField;
        }
        set
        {
            this.rOUNDSUM_PAYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
    public string PAY_DUE_DATE
    {
        get
        {
            return this.pAY_DUE_DATEField;
        }
        set
        {
            this.pAY_DUE_DATEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
    public string BRT_FORWARD
    {
        get
        {
            return this.bRT_FORWARDField;
        }
        set
        {
            this.bRT_FORWARDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
    public string CONSUMER_TYPE
    {
        get
        {
            return this.cONSUMER_TYPEField;
        }
        set
        {
            this.cONSUMER_TYPEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
    public string BILL_DATE
    {
        get
        {
            return this.bILL_DATEField;
        }
        set
        {
            this.bILL_DATEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
    public string TOTAL_CHARGES
    {
        get
        {
            return this.tOTAL_CHARGESField;
        }
        set
        {
            this.tOTAL_CHARGESField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
    public string STATUS
    {
        get
        {
            return this.sTATUSField;
        }
        set
        {
            this.sTATUSField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
    public string TARIFF
    {
        get
        {
            return this.tARIFFField;
        }
        set
        {
            this.tARIFFField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
    public string FLAG
    {
        get
        {
            return this.fLAGField;
        }
        set
        {
            this.fLAGField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
    public string PAY_PPI_DATE
    {
        get
        {
            return this.pAY_PPI_DATEField;
        }
        set
        {
            this.pAY_PPI_DATEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
    public string PPI_BILL_AMT
    {
        get
        {
            return this.pPI_BILL_AMTField;
        }
        set
        {
            this.pPI_BILL_AMTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
    public string DUE_DATE_BILL_AMT
    {
        get
        {
            return this.dUE_DATE_BILL_AMTField;
        }
        set
        {
            this.dUE_DATE_BILL_AMTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
    public string DPC_BILL_AMT
    {
        get
        {
            return this.dPC_BILL_AMTField;
        }
        set
        {
            this.dPC_BILL_AMTField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rel.com/xi/RelMobApp/MR_BI_GETLIST")]
public partial class DT_MR_BI_GETLIST_respItem
{
    
    private string cONTRACTField;
    
    private string uNITS_BILLEDField;
    
    private string cURR_MTH_BILL_AMField;
    
    private string pERIOD_FROMField;
    
    private string pERIOD_TOField;
    
    private string cONSUMER_TYPEField;
    
    private string mETER_NOField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string CONTRACT
    {
        get
        {
            return this.cONTRACTField;
        }
        set
        {
            this.cONTRACTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string UNITS_BILLED
    {
        get
        {
            return this.uNITS_BILLEDField;
        }
        set
        {
            this.uNITS_BILLEDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string CURR_MTH_BILL_AM
    {
        get
        {
            return this.cURR_MTH_BILL_AMField;
        }
        set
        {
            this.cURR_MTH_BILL_AMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public string PERIOD_FROM
    {
        get
        {
            return this.pERIOD_FROMField;
        }
        set
        {
            this.pERIOD_FROMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public string PERIOD_TO
    {
        get
        {
            return this.pERIOD_TOField;
        }
        set
        {
            this.pERIOD_TOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
    public string CONSUMER_TYPE
    {
        get
        {
            return this.cONSUMER_TYPEField;
        }
        set
        {
            this.cONSUMER_TYPEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
    public string METER_NO
    {
        get
        {
            return this.mETER_NOField;
        }
        set
        {
            this.mETER_NOField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rel.com/xi/RelMobApp/MR_BI_GETLIST")]
public partial class DT_MR_BI_GETLIST_respItem1
{
    
    private string lOGNUMBERField;
    
    private string mSGNUMBERField;
    
    private string lINEField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string LOGNUMBER
    {
        get
        {
            return this.lOGNUMBERField;
        }
        set
        {
            this.lOGNUMBERField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string MSGNUMBER
    {
        get
        {
            return this.mSGNUMBERField;
        }
        set
        {
            this.mSGNUMBERField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string LINE
    {
        get
        {
            return this.lINEField;
        }
        set
        {
            this.lINEField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rel.com/xi/RelMobApp/MR_BI_GETLIST")]
public partial class DT_MR_BI_GETLIST_respItem2
{
    
    private string tYPEField;
    
    private string idField;
    
    private string nUMBERField;
    
    private string mESSAGEField;
    
    private string lOG_NOField;
    
    private string lOG_MSG_NOField;
    
    private string mESSAGE_V1Field;
    
    private string mESSAGE_V2Field;
    
    private string mESSAGE_V3Field;
    
    private string mESSAGE_V4Field;
    
    private string pARAMETERField;
    
    private string rOWField;
    
    private string fIELDField;
    
    private string sYSTEMField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string TYPE
    {
        get
        {
            return this.tYPEField;
        }
        set
        {
            this.tYPEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string ID
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string NUMBER
    {
        get
        {
            return this.nUMBERField;
        }
        set
        {
            this.nUMBERField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public string MESSAGE
    {
        get
        {
            return this.mESSAGEField;
        }
        set
        {
            this.mESSAGEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public string LOG_NO
    {
        get
        {
            return this.lOG_NOField;
        }
        set
        {
            this.lOG_NOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
    public string LOG_MSG_NO
    {
        get
        {
            return this.lOG_MSG_NOField;
        }
        set
        {
            this.lOG_MSG_NOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
    public string MESSAGE_V1
    {
        get
        {
            return this.mESSAGE_V1Field;
        }
        set
        {
            this.mESSAGE_V1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
    public string MESSAGE_V2
    {
        get
        {
            return this.mESSAGE_V2Field;
        }
        set
        {
            this.mESSAGE_V2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
    public string MESSAGE_V3
    {
        get
        {
            return this.mESSAGE_V3Field;
        }
        set
        {
            this.mESSAGE_V3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
    public string MESSAGE_V4
    {
        get
        {
            return this.mESSAGE_V4Field;
        }
        set
        {
            this.mESSAGE_V4Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
    public string PARAMETER
    {
        get
        {
            return this.pARAMETERField;
        }
        set
        {
            this.pARAMETERField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
    public string ROW
    {
        get
        {
            return this.rOWField;
        }
        set
        {
            this.rOWField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
    public string FIELD
    {
        get
        {
            return this.fIELDField;
        }
        set
        {
            this.fIELDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
    public string SYSTEM
    {
        get
        {
            return this.sYSTEMField;
        }
        set
        {
            this.sYSTEMField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rel.com/xi/RelMobApp/MR_BI_GETLIST")]
public partial class DT_MR_BI_GETLIST_respItem3
{
    
    private string sERNRField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string SERNR
    {
        get
        {
            return this.sERNRField;
        }
        set
        {
            this.sERNRField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class SI_MR_BI_GETLIST_inRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rel.com/xi/RelMobApp/MR_BI_GETLIST", Order=0)]
    public DT_MR_BI_GETLIST_req MT_MR_BI_GETLIST_req;
    
    public SI_MR_BI_GETLIST_inRequest()
    {
    }
    
    public SI_MR_BI_GETLIST_inRequest(DT_MR_BI_GETLIST_req MT_MR_BI_GETLIST_req)
    {
        this.MT_MR_BI_GETLIST_req = MT_MR_BI_GETLIST_req;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class SI_MR_BI_GETLIST_inResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rel.com/xi/RelMobApp/MR_BI_GETLIST", Order=0)]
    public DT_MR_BI_GETLIST_resp MT_MR_BI_GETLIST_resp;
    
    public SI_MR_BI_GETLIST_inResponse()
    {
    }
    
    public SI_MR_BI_GETLIST_inResponse(DT_MR_BI_GETLIST_resp MT_MR_BI_GETLIST_resp)
    {
        this.MT_MR_BI_GETLIST_resp = MT_MR_BI_GETLIST_resp;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface SI_MR_BI_GETLIST_inChannel : SI_MR_BI_GETLIST_in, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class SI_MR_BI_GETLIST_inClient : System.ServiceModel.ClientBase<SI_MR_BI_GETLIST_in>, SI_MR_BI_GETLIST_in
{
    
    public SI_MR_BI_GETLIST_inClient()
    {
    }
    
    public SI_MR_BI_GETLIST_inClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public SI_MR_BI_GETLIST_inClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SI_MR_BI_GETLIST_inClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SI_MR_BI_GETLIST_inClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    SI_MR_BI_GETLIST_inResponse SI_MR_BI_GETLIST_in.SI_MR_BI_GETLIST_in(SI_MR_BI_GETLIST_inRequest request)
    {
        return base.Channel.SI_MR_BI_GETLIST_in(request);
    }
    
    public DT_MR_BI_GETLIST_resp SI_MR_BI_GETLIST_in(DT_MR_BI_GETLIST_req MT_MR_BI_GETLIST_req)
    {
        SI_MR_BI_GETLIST_inRequest inValue = new SI_MR_BI_GETLIST_inRequest();
        inValue.MT_MR_BI_GETLIST_req = MT_MR_BI_GETLIST_req;
        SI_MR_BI_GETLIST_inResponse retVal = ((SI_MR_BI_GETLIST_in)(this)).SI_MR_BI_GETLIST_in(inValue);
        return retVal.MT_MR_BI_GETLIST_resp;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SI_MR_BI_GETLIST_inResponse> SI_MR_BI_GETLIST_in.SI_MR_BI_GETLIST_inAsync(SI_MR_BI_GETLIST_inRequest request)
    {
        return base.Channel.SI_MR_BI_GETLIST_inAsync(request);
    }
    
    public System.Threading.Tasks.Task<SI_MR_BI_GETLIST_inResponse> SI_MR_BI_GETLIST_inAsync(DT_MR_BI_GETLIST_req MT_MR_BI_GETLIST_req)
    {
        SI_MR_BI_GETLIST_inRequest inValue = new SI_MR_BI_GETLIST_inRequest();
        inValue.MT_MR_BI_GETLIST_req = MT_MR_BI_GETLIST_req;
        return ((SI_MR_BI_GETLIST_in)(this)).SI_MR_BI_GETLIST_inAsync(inValue);
    }
}
