//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://rel.com/xi/RelMobApp/ONLINE_BILL_PDF", ConfigurationName="SI_ONLINE_BILL_PDF_in")]
public interface SI_ONLINE_BILL_PDF_in
{
    
    // CODEGEN: Generating message contract since the operation SI_ONLINE_BILL_PDF_in is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    SI_ONLINE_BILL_PDF_inResponse SI_ONLINE_BILL_PDF_in(SI_ONLINE_BILL_PDF_inRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
    System.Threading.Tasks.Task<SI_ONLINE_BILL_PDF_inResponse> SI_ONLINE_BILL_PDF_inAsync(SI_ONLINE_BILL_PDF_inRequest request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rel.com/xi/RelMobApp/ONLINE_BILL_PDF")]
public partial class DT_ONLINE_BILL_PDF_req
{
    
    private string cONT_ACCTField;
    
    private string bILL_INDField;
    
    private string iNVOICE_NOField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string CONT_ACCT
    {
        get
        {
            return this.cONT_ACCTField;
        }
        set
        {
            this.cONT_ACCTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string BILL_IND
    {
        get
        {
            return this.bILL_INDField;
        }
        set
        {
            this.bILL_INDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string INVOICE_NO
    {
        get
        {
            return this.iNVOICE_NOField;
        }
        set
        {
            this.iNVOICE_NOField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rel.com/xi/RelMobApp/ONLINE_BILL_PDF")]
public partial class DT_ONLINE_BILL_PDF_resp
{
    
    private string cONTACTField;
    
    private string fTYP_FLGField;
    
    private DT_ONLINE_BILL_PDF_respItem[] pDFField;
    
    private DT_ONLINE_BILL_PDF_respItem1[] rETURNField;
    
    private DT_ONLINE_BILL_PDF_respItem2[] tXTField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string CONTACT
    {
        get
        {
            return this.cONTACTField;
        }
        set
        {
            this.cONTACTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string FTYP_FLG
    {
        get
        {
            return this.fTYP_FLGField;
        }
        set
        {
            this.fTYP_FLGField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public DT_ONLINE_BILL_PDF_respItem[] PDF
    {
        get
        {
            return this.pDFField;
        }
        set
        {
            this.pDFField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public DT_ONLINE_BILL_PDF_respItem1[] RETURN
    {
        get
        {
            return this.rETURNField;
        }
        set
        {
            this.rETURNField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public DT_ONLINE_BILL_PDF_respItem2[] TXT
    {
        get
        {
            return this.tXTField;
        }
        set
        {
            this.tXTField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rel.com/xi/RelMobApp/ONLINE_BILL_PDF")]
public partial class DT_ONLINE_BILL_PDF_respItem
{
    
    private byte[] lINEField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
    public byte[] LINE
    {
        get
        {
            return this.lINEField;
        }
        set
        {
            this.lINEField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rel.com/xi/RelMobApp/ONLINE_BILL_PDF")]
public partial class DT_ONLINE_BILL_PDF_respItem1
{
    
    private string tYPEField;
    
    private string idField;
    
    private string nUMBERField;
    
    private string mESSAGEField;
    
    private string lOG_NOField;
    
    private string lOG_MSG_NOField;
    
    private string mESSAGE_V1Field;
    
    private string mESSAGE_V2Field;
    
    private string mESSAGE_V3Field;
    
    private string mESSAGE_V4Field;
    
    private string pARAMETERField;
    
    private string rOWField;
    
    private string fIELDField;
    
    private string sYSTEMField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string TYPE
    {
        get
        {
            return this.tYPEField;
        }
        set
        {
            this.tYPEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string ID
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string NUMBER
    {
        get
        {
            return this.nUMBERField;
        }
        set
        {
            this.nUMBERField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public string MESSAGE
    {
        get
        {
            return this.mESSAGEField;
        }
        set
        {
            this.mESSAGEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public string LOG_NO
    {
        get
        {
            return this.lOG_NOField;
        }
        set
        {
            this.lOG_NOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
    public string LOG_MSG_NO
    {
        get
        {
            return this.lOG_MSG_NOField;
        }
        set
        {
            this.lOG_MSG_NOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
    public string MESSAGE_V1
    {
        get
        {
            return this.mESSAGE_V1Field;
        }
        set
        {
            this.mESSAGE_V1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
    public string MESSAGE_V2
    {
        get
        {
            return this.mESSAGE_V2Field;
        }
        set
        {
            this.mESSAGE_V2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
    public string MESSAGE_V3
    {
        get
        {
            return this.mESSAGE_V3Field;
        }
        set
        {
            this.mESSAGE_V3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
    public string MESSAGE_V4
    {
        get
        {
            return this.mESSAGE_V4Field;
        }
        set
        {
            this.mESSAGE_V4Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
    public string PARAMETER
    {
        get
        {
            return this.pARAMETERField;
        }
        set
        {
            this.pARAMETERField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
    public string ROW
    {
        get
        {
            return this.rOWField;
        }
        set
        {
            this.rOWField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
    public string FIELD
    {
        get
        {
            return this.fIELDField;
        }
        set
        {
            this.fIELDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
    public string SYSTEM
    {
        get
        {
            return this.sYSTEMField;
        }
        set
        {
            this.sYSTEMField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rel.com/xi/RelMobApp/ONLINE_BILL_PDF")]
public partial class DT_ONLINE_BILL_PDF_respItem2
{
    
    private string zTXTField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string ZTXT
    {
        get
        {
            return this.zTXTField;
        }
        set
        {
            this.zTXTField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class SI_ONLINE_BILL_PDF_inRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rel.com/xi/RelMobApp/ONLINE_BILL_PDF", Order=0)]
    public DT_ONLINE_BILL_PDF_req MT_ONLINE_BILL_PDF_req;
    
    public SI_ONLINE_BILL_PDF_inRequest()
    {
    }
    
    public SI_ONLINE_BILL_PDF_inRequest(DT_ONLINE_BILL_PDF_req MT_ONLINE_BILL_PDF_req)
    {
        this.MT_ONLINE_BILL_PDF_req = MT_ONLINE_BILL_PDF_req;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class SI_ONLINE_BILL_PDF_inResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rel.com/xi/RelMobApp/ONLINE_BILL_PDF", Order=0)]
    public DT_ONLINE_BILL_PDF_resp MT_ONLINE_BILL_PDF_resp;
    
    public SI_ONLINE_BILL_PDF_inResponse()
    {
    }
    
    public SI_ONLINE_BILL_PDF_inResponse(DT_ONLINE_BILL_PDF_resp MT_ONLINE_BILL_PDF_resp)
    {
        this.MT_ONLINE_BILL_PDF_resp = MT_ONLINE_BILL_PDF_resp;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface SI_ONLINE_BILL_PDF_inChannel : SI_ONLINE_BILL_PDF_in, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class SI_ONLINE_BILL_PDF_inClient : System.ServiceModel.ClientBase<SI_ONLINE_BILL_PDF_in>, SI_ONLINE_BILL_PDF_in
{
    
    public SI_ONLINE_BILL_PDF_inClient()
    {
    }
    
    public SI_ONLINE_BILL_PDF_inClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public SI_ONLINE_BILL_PDF_inClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SI_ONLINE_BILL_PDF_inClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SI_ONLINE_BILL_PDF_inClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    SI_ONLINE_BILL_PDF_inResponse SI_ONLINE_BILL_PDF_in.SI_ONLINE_BILL_PDF_in(SI_ONLINE_BILL_PDF_inRequest request)
    {
        return base.Channel.SI_ONLINE_BILL_PDF_in(request);
    }
    
    public DT_ONLINE_BILL_PDF_resp SI_ONLINE_BILL_PDF_in(DT_ONLINE_BILL_PDF_req MT_ONLINE_BILL_PDF_req)
    {
        SI_ONLINE_BILL_PDF_inRequest inValue = new SI_ONLINE_BILL_PDF_inRequest();
        inValue.MT_ONLINE_BILL_PDF_req = MT_ONLINE_BILL_PDF_req;
        SI_ONLINE_BILL_PDF_inResponse retVal = ((SI_ONLINE_BILL_PDF_in)(this)).SI_ONLINE_BILL_PDF_in(inValue);
        return retVal.MT_ONLINE_BILL_PDF_resp;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SI_ONLINE_BILL_PDF_inResponse> SI_ONLINE_BILL_PDF_in.SI_ONLINE_BILL_PDF_inAsync(SI_ONLINE_BILL_PDF_inRequest request)
    {
        return base.Channel.SI_ONLINE_BILL_PDF_inAsync(request);
    }
    
    public System.Threading.Tasks.Task<SI_ONLINE_BILL_PDF_inResponse> SI_ONLINE_BILL_PDF_inAsync(DT_ONLINE_BILL_PDF_req MT_ONLINE_BILL_PDF_req)
    {
        SI_ONLINE_BILL_PDF_inRequest inValue = new SI_ONLINE_BILL_PDF_inRequest();
        inValue.MT_ONLINE_BILL_PDF_req = MT_ONLINE_BILL_PDF_req;
        return ((SI_ONLINE_BILL_PDF_in)(this)).SI_ONLINE_BILL_PDF_inAsync(inValue);
    }
}
