//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SapPiService.Services
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://rel.com/xi/RelMobApp/MobComplaint", ConfigurationName = "SI_RegcomplaintAll")]
    public interface SI_RegcomplaintAll
    {
        // CODEGEN: Generating message contract since the operation SI_RegcomplaintAll is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action = "http://sap.com/xi/WebService/soap1.1", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        SI_RegcomplaintAllResponse SI_RegcomplaintAll(SI_RegcomplaintAllRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://sap.com/xi/WebService/soap1.1", ReplyAction = "*")]
        System.Threading.Tasks.Task<SI_RegcomplaintAllResponse> SI_RegcomplaintAllAsync(SI_RegcomplaintAllRequest request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://rel.com/xi/RelMobApp/MobComplaint")]
    public partial class DT_RegcomplaintAll_Req
    {

        private string cA_NoField;

        private string contact_NoField;

        private string complaint_TypeField;

        private string sourceField;

        private string complaint_SubtypeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string CA_No
        {
            get
            {
                return this.cA_NoField;
            }
            set
            {
                this.cA_NoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string Contact_No
        {
            get
            {
                return this.contact_NoField;
            }
            set
            {
                this.contact_NoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string Complaint_Type
        {
            get
            {
                return this.complaint_TypeField;
            }
            set
            {
                this.complaint_TypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string Source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string Complaint_Subtype
        {
            get
            {
                return this.complaint_SubtypeField;
            }
            set
            {
                this.complaint_SubtypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://rel.com/xi/RelMobApp/MobComplaint")]
    public partial class DT_Regcomplaint_Resp
    {

        private string responseField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string Response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class SI_RegcomplaintAllRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://rel.com/xi/RelMobApp/MobComplaint", Order = 0)]
        public DT_RegcomplaintAll_Req MT_RegcomplaintAll_Req;

        public SI_RegcomplaintAllRequest()
        {
        }

        public SI_RegcomplaintAllRequest(DT_RegcomplaintAll_Req MT_RegcomplaintAll_Req)
        {
            this.MT_RegcomplaintAll_Req = MT_RegcomplaintAll_Req;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class SI_RegcomplaintAllResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://rel.com/xi/RelMobApp/MobComplaint", Order = 0)]
        public DT_Regcomplaint_Resp MT_Regcomplaint_Resp;

        public SI_RegcomplaintAllResponse()
        {
        }

        public SI_RegcomplaintAllResponse(DT_Regcomplaint_Resp MT_Regcomplaint_Resp)
        {
            this.MT_Regcomplaint_Resp = MT_Regcomplaint_Resp;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_RegcomplaintAllChannel : SI_RegcomplaintAll, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_RegcomplaintAllClient : System.ServiceModel.ClientBase<SI_RegcomplaintAll>, SI_RegcomplaintAll
    {

        public SI_RegcomplaintAllClient()
        {
        }

        public SI_RegcomplaintAllClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public SI_RegcomplaintAllClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public SI_RegcomplaintAllClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public SI_RegcomplaintAllClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SI_RegcomplaintAllResponse SI_RegcomplaintAll.SI_RegcomplaintAll(SI_RegcomplaintAllRequest request)
        {
            return base.Channel.SI_RegcomplaintAll(request);
        }

        public DT_Regcomplaint_Resp SI_RegcomplaintAll(DT_RegcomplaintAll_Req MT_RegcomplaintAll_Req)
        {
            SI_RegcomplaintAllRequest inValue = new SI_RegcomplaintAllRequest();
            inValue.MT_RegcomplaintAll_Req = MT_RegcomplaintAll_Req;
            SI_RegcomplaintAllResponse retVal = ((SI_RegcomplaintAll)(this)).SI_RegcomplaintAll(inValue);
            return retVal.MT_Regcomplaint_Resp;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SI_RegcomplaintAllResponse> SI_RegcomplaintAll.SI_RegcomplaintAllAsync(SI_RegcomplaintAllRequest request)
        {
            return base.Channel.SI_RegcomplaintAllAsync(request);
        }

        public System.Threading.Tasks.Task<SI_RegcomplaintAllResponse> SI_RegcomplaintAllAsync(DT_RegcomplaintAll_Req MT_RegcomplaintAll_Req)
        {
            SI_RegcomplaintAllRequest inValue = new SI_RegcomplaintAllRequest();
            inValue.MT_RegcomplaintAll_Req = MT_RegcomplaintAll_Req;
            return ((SI_RegcomplaintAll)(this)).SI_RegcomplaintAllAsync(inValue);
        }
    }
}
