<?xml version="1.0" encoding="utf-8"?><Database Name="AdaniGas" Class="AdaniGasPaymentHistoryDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=tcp:adanistaging-sql.database.windows.net;Initial Catalog=AdaniGas;User ID=Sitecore" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="AdaniGasConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.PaymentHistoryData" Member="PaymentHistoryDatas">
    <Type Name="PaymentHistoryData">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AccountNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OrderId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Amount" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RequestTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Checksumkey" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CurrencyType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GatewayType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CustomerType" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AdvanceAmmount" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PaymentType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TransactionId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Responsecode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ResponseTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PaymentRef" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ResponseMsg" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PaymentMode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Created_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Modified_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ISU_UPDATE_FLAG" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="ISU_UPDATE_DATETIME" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ISU_UPDATE_MESSAGE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ISUVDS_Update_Flag" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ISUVDS_Update_DateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ISUVDS_Update_Message" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NewConnectionData" Member="NewConnectionDatas">
    <Type Name="NewConnectionData">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EnquiryNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="ContactNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ConnectionTypeCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ConnectionType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CityCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CityName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="AreaCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AreaName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TypeOfHouse" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ApartmentComplex" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="OtherApartmentOrSociety" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TypeOfCustomer" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="OtherTypeOfCustomer" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Application" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="OtherApplication" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CurrentFuelUsing" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="OtherFuelUsing" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TypeOfIndustry" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="OtherTypeOfIndustry" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="MonthlyConsumption" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="HouseNo_BuildingNo" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="AddressLine1" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AddressLine2" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Pincode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ReferenceSource" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CampaignID" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="FormURL" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SubmitOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SubmittedBy" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
</Database>