#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.AdaniConneX.Website
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Realty")]
	public partial class AdaniConnexContactFormDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAdaniConnex_JoinusForm(AdaniConnex_JoinusForm instance);
    partial void UpdateAdaniConnex_JoinusForm(AdaniConnex_JoinusForm instance);
    partial void DeleteAdaniConnex_JoinusForm(AdaniConnex_JoinusForm instance);
    partial void InsertAdaniConnex_ContactForm(AdaniConnex_ContactForm instance);
    partial void UpdateAdaniConnex_ContactForm(AdaniConnex_ContactForm instance);
    partial void DeleteAdaniConnex_ContactForm(AdaniConnex_ContactForm instance);
    partial void InsertAdaniConnex_TakeAtourForm(AdaniConnex_TakeAtourForm instance);
    partial void UpdateAdaniConnex_TakeAtourForm(AdaniConnex_TakeAtourForm instance);
    partial void DeleteAdaniConnex_TakeAtourForm(AdaniConnex_TakeAtourForm instance);
    partial void InsertAdaniConnex_WhitePaperForm(AdaniConnex_WhitePaperForm instance);
    partial void UpdateAdaniConnex_WhitePaperForm(AdaniConnex_WhitePaperForm instance);
    partial void DeleteAdaniConnex_WhitePaperForm(AdaniConnex_WhitePaperForm instance);
        #endregion

        public AdaniConnexContactFormDataContext() :
                base(global::System.Configuration.ConfigurationManager.ConnectionStrings["RealtyConnectionString"].ConnectionString, mappingSource)
        {
            OnCreated();
        }
        public AdaniConnexContactFormDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AdaniConnexContactFormDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AdaniConnexContactFormDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AdaniConnexContactFormDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AdaniConnex_JoinusForm> AdaniConnex_JoinusForms
		{
			get
			{
				return this.GetTable<AdaniConnex_JoinusForm>();
			}
		}
		
		public System.Data.Linq.Table<AdaniConnex_ContactForm> AdaniConnex_ContactForms
		{
			get
			{
				return this.GetTable<AdaniConnex_ContactForm>();
			}
		}
		
		public System.Data.Linq.Table<AdaniConnex_TakeAtourForm> AdaniConnex_TakeAtourForms
		{
			get
			{
				return this.GetTable<AdaniConnex_TakeAtourForm>();
			}
		}
		
		public System.Data.Linq.Table<AdaniConnex_WhitePaperForm> AdaniConnex_WhitePaperForms
		{
			get
			{
				return this.GetTable<AdaniConnex_WhitePaperForm>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AdaniConnex_JoinusForm")]
	public partial class AdaniConnex_JoinusForm : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _Name;
		
		private string _Email;
		
		private string _Contact;
		
		private string _CVName;
		
		private System.Data.Linq.Binary _CVFile;
		
		private string _FormUrl;
		
		private string _FormType;
		
		private System.DateTime _SubmittedDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnContactChanging(string value);
    partial void OnContactChanged();
    partial void OnCVNameChanging(string value);
    partial void OnCVNameChanged();
    partial void OnCVFileChanging(System.Data.Linq.Binary value);
    partial void OnCVFileChanged();
    partial void OnFormUrlChanging(string value);
    partial void OnFormUrlChanged();
    partial void OnFormTypeChanging(string value);
    partial void OnFormTypeChanged();
    partial void OnSubmittedDateChanging(System.DateTime value);
    partial void OnSubmittedDateChanged();
    #endregion
		
		public AdaniConnex_JoinusForm()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contact", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Contact
		{
			get
			{
				return this._Contact;
			}
			set
			{
				if ((this._Contact != value))
				{
					this.OnContactChanging(value);
					this.SendPropertyChanging();
					this._Contact = value;
					this.SendPropertyChanged("Contact");
					this.OnContactChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CVName", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string CVName
		{
			get
			{
				return this._CVName;
			}
			set
			{
				if ((this._CVName != value))
				{
					this.OnCVNameChanging(value);
					this.SendPropertyChanging();
					this._CVName = value;
					this.SendPropertyChanged("CVName");
					this.OnCVNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CVFile", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary CVFile
		{
			get
			{
				return this._CVFile;
			}
			set
			{
				if ((this._CVFile != value))
				{
					this.OnCVFileChanging(value);
					this.SendPropertyChanging();
					this._CVFile = value;
					this.SendPropertyChanged("CVFile");
					this.OnCVFileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormUrl", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string FormUrl
		{
			get
			{
				return this._FormUrl;
			}
			set
			{
				if ((this._FormUrl != value))
				{
					this.OnFormUrlChanging(value);
					this.SendPropertyChanging();
					this._FormUrl = value;
					this.SendPropertyChanged("FormUrl");
					this.OnFormUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormType", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string FormType
		{
			get
			{
				return this._FormType;
			}
			set
			{
				if ((this._FormType != value))
				{
					this.OnFormTypeChanging(value);
					this.SendPropertyChanging();
					this._FormType = value;
					this.SendPropertyChanged("FormType");
					this.OnFormTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmittedDate", DbType="DateTime NOT NULL")]
		public System.DateTime SubmittedDate
		{
			get
			{
				return this._SubmittedDate;
			}
			set
			{
				if ((this._SubmittedDate != value))
				{
					this.OnSubmittedDateChanging(value);
					this.SendPropertyChanging();
					this._SubmittedDate = value;
					this.SendPropertyChanged("SubmittedDate");
					this.OnSubmittedDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AdaniConnex_ContactForm")]
	public partial class AdaniConnex_ContactForm : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _Name;
		
		private string _Email;
		
		private string _Contact;
		
		private string _Message;
		
		private string _FormType;
		
		private string _FormUrl;
		
		private System.Nullable<System.DateTime> _SubmittedDate;
		
		private string _Company;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnContactChanging(string value);
    partial void OnContactChanged();
    partial void OnMessageChanging(string value);
    partial void OnMessageChanged();
    partial void OnFormTypeChanging(string value);
    partial void OnFormTypeChanged();
    partial void OnFormUrlChanging(string value);
    partial void OnFormUrlChanged();
    partial void OnSubmittedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnSubmittedDateChanged();
    partial void OnCompanyChanging(string value);
    partial void OnCompanyChanged();
    #endregion
		
		public AdaniConnex_ContactForm()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(150)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contact", DbType="VarChar(150)")]
		public string Contact
		{
			get
			{
				return this._Contact;
			}
			set
			{
				if ((this._Contact != value))
				{
					this.OnContactChanging(value);
					this.SendPropertyChanging();
					this._Contact = value;
					this.SendPropertyChanged("Contact");
					this.OnContactChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="VarChar(150)")]
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				if ((this._Message != value))
				{
					this.OnMessageChanging(value);
					this.SendPropertyChanging();
					this._Message = value;
					this.SendPropertyChanged("Message");
					this.OnMessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormType", DbType="VarChar(50)")]
		public string FormType
		{
			get
			{
				return this._FormType;
			}
			set
			{
				if ((this._FormType != value))
				{
					this.OnFormTypeChanging(value);
					this.SendPropertyChanging();
					this._FormType = value;
					this.SendPropertyChanged("FormType");
					this.OnFormTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormUrl", DbType="VarChar(250)")]
		public string FormUrl
		{
			get
			{
				return this._FormUrl;
			}
			set
			{
				if ((this._FormUrl != value))
				{
					this.OnFormUrlChanging(value);
					this.SendPropertyChanging();
					this._FormUrl = value;
					this.SendPropertyChanged("FormUrl");
					this.OnFormUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmittedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> SubmittedDate
		{
			get
			{
				return this._SubmittedDate;
			}
			set
			{
				if ((this._SubmittedDate != value))
				{
					this.OnSubmittedDateChanging(value);
					this.SendPropertyChanging();
					this._SubmittedDate = value;
					this.SendPropertyChanged("SubmittedDate");
					this.OnSubmittedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company", DbType="VarChar(150)")]
		public string Company
		{
			get
			{
				return this._Company;
			}
			set
			{
				if ((this._Company != value))
				{
					this.OnCompanyChanging(value);
					this.SendPropertyChanging();
					this._Company = value;
					this.SendPropertyChanged("Company");
					this.OnCompanyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AdaniConnex_TakeAtourForm")]
	public partial class AdaniConnex_TakeAtourForm : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _Name;
		
		private string _Email;
		
		private string _Contact;
		
		private string _Location;
		
		private string _FormType;
		
		private string _FormUrl;
		
		private System.Nullable<System.DateTime> _SubmittedDate;
		
		private string _Company;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnContactChanging(string value);
    partial void OnContactChanged();
    partial void OnLocationChanging(string value);
    partial void OnLocationChanged();
    partial void OnFormTypeChanging(string value);
    partial void OnFormTypeChanged();
    partial void OnFormUrlChanging(string value);
    partial void OnFormUrlChanged();
    partial void OnSubmittedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnSubmittedDateChanged();
    partial void OnCompanyChanging(string value);
    partial void OnCompanyChanged();
    #endregion
		
		public AdaniConnex_TakeAtourForm()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(150)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contact", DbType="VarChar(150)")]
		public string Contact
		{
			get
			{
				return this._Contact;
			}
			set
			{
				if ((this._Contact != value))
				{
					this.OnContactChanging(value);
					this.SendPropertyChanging();
					this._Contact = value;
					this.SendPropertyChanged("Contact");
					this.OnContactChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="VarChar(150)")]
		public string Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this.OnLocationChanging(value);
					this.SendPropertyChanging();
					this._Location = value;
					this.SendPropertyChanged("Location");
					this.OnLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormType", DbType="VarChar(150)")]
		public string FormType
		{
			get
			{
				return this._FormType;
			}
			set
			{
				if ((this._FormType != value))
				{
					this.OnFormTypeChanging(value);
					this.SendPropertyChanging();
					this._FormType = value;
					this.SendPropertyChanged("FormType");
					this.OnFormTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormUrl", DbType="VarChar(150)")]
		public string FormUrl
		{
			get
			{
				return this._FormUrl;
			}
			set
			{
				if ((this._FormUrl != value))
				{
					this.OnFormUrlChanging(value);
					this.SendPropertyChanging();
					this._FormUrl = value;
					this.SendPropertyChanged("FormUrl");
					this.OnFormUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmittedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> SubmittedDate
		{
			get
			{
				return this._SubmittedDate;
			}
			set
			{
				if ((this._SubmittedDate != value))
				{
					this.OnSubmittedDateChanging(value);
					this.SendPropertyChanging();
					this._SubmittedDate = value;
					this.SendPropertyChanged("SubmittedDate");
					this.OnSubmittedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company", DbType="VarChar(150)")]
		public string Company
		{
			get
			{
				return this._Company;
			}
			set
			{
				if ((this._Company != value))
				{
					this.OnCompanyChanging(value);
					this.SendPropertyChanging();
					this._Company = value;
					this.SendPropertyChanged("Company");
					this.OnCompanyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AdaniConnex_WhitePaperForm")]
	public partial class AdaniConnex_WhitePaperForm : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _Name;
		
		private string _Email;
		
		private string _Contact;
		
		private string _Company;
		
		private string _Country;
		
		private System.Nullable<System.DateTime> _SubmittedDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnContactChanging(string value);
    partial void OnContactChanged();
    partial void OnCompanyChanging(string value);
    partial void OnCompanyChanged();
    partial void OnCountryChanging(string value);
    partial void OnCountryChanged();
    partial void OnSubmittedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnSubmittedDateChanged();
    #endregion
		
		public AdaniConnex_WhitePaperForm()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(150)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contact", DbType="VarChar(50)")]
		public string Contact
		{
			get
			{
				return this._Contact;
			}
			set
			{
				if ((this._Contact != value))
				{
					this.OnContactChanging(value);
					this.SendPropertyChanging();
					this._Contact = value;
					this.SendPropertyChanged("Contact");
					this.OnContactChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company", DbType="VarChar(150)")]
		public string Company
		{
			get
			{
				return this._Company;
			}
			set
			{
				if ((this._Company != value))
				{
					this.OnCompanyChanging(value);
					this.SendPropertyChanging();
					this._Company = value;
					this.SendPropertyChanged("Company");
					this.OnCompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="VarChar(50)")]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this.OnCountryChanging(value);
					this.SendPropertyChanging();
					this._Country = value;
					this.SendPropertyChanged("Country");
					this.OnCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmittedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> SubmittedDate
		{
			get
			{
				return this._SubmittedDate;
			}
			set
			{
				if ((this._SubmittedDate != value))
				{
					this.OnSubmittedDateChanging(value);
					this.SendPropertyChanging();
					this._SubmittedDate = value;
					this.SendPropertyChanged("SubmittedDate");
					this.OnSubmittedDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
