//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.Ports.Website.SailedBulkServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SailedBulkServiceReference.get_sailed_drybcSoap")]
    public interface get_sailed_drybcSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_sailed_drybc_data", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet get_sailed_drybc_data();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_sailed_drybc_data", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> get_sailed_drybc_dataAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface get_sailed_drybcSoapChannel : Sitecore.Ports.Website.SailedBulkServiceReference.get_sailed_drybcSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class get_sailed_drybcSoapClient : System.ServiceModel.ClientBase<Sitecore.Ports.Website.SailedBulkServiceReference.get_sailed_drybcSoap>, Sitecore.Ports.Website.SailedBulkServiceReference.get_sailed_drybcSoap {
        
        public get_sailed_drybcSoapClient() {
        }
        
        public get_sailed_drybcSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public get_sailed_drybcSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public get_sailed_drybcSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public get_sailed_drybcSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet get_sailed_drybc_data() {
            return base.Channel.get_sailed_drybc_data();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> get_sailed_drybc_dataAsync() {
            return base.Channel.get_sailed_drybc_dataAsync();
        }
    }
}
