<?xml version="1.0" encoding="utf-8"?><Database Name="Realty" Class="TransmissionContactFormRecordDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=tcp:adanistaging-sql.database.windows.net;Initial Catalog=Realty;User ID=sitecore" SettingsObjectName="Sitecore.Transmission.Website.Properties.Settings" SettingsPropertyName="RealtyConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Transmission_CarbonCalculator_LoginHistory" Member="Transmission_CarbonCalculator_LoginHistories">
    <Type Name="Transmission_CarbonCalculator_LoginHistory">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LoginId" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Created_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Modified_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Transmission_CarbonCalculator_RegistrationForm" Member="Transmission_CarbonCalculator_RegistrationForms">
    <Type Name="Transmission_CarbonCalculator_RegistrationForm">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="EmailId" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="MobileNumber" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Company" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Created_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Modified_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="OTP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email_Verified" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Mobile_Verified" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Transmission_CarbonCalculator_User_otp" Member="Transmission_CarbonCalculator_User_otps">
    <Type Name="Transmission_CarbonCalculator_User_otp">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MobileNumber" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="otp" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TransmissionCarbonOffsetValue" Member="TransmissionCarbonOffsetValues">
    <Type Name="TransmissionCarbonOffsetValue">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CostCalculatorID" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Login" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="RegistartionNumber" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="MonthName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Year" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="PersonalTransport" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="PublicTransport" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="OnlineMeeting" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="FiveStarAppliances" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NumberofTreesNeeded" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="FundNeededtoPlantTrees" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="OffsetEmissionfromDomesticUse" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="OffsetEmissionfromTransportation" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="OffsetEmissionfromAirTrips" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="TotalOffsetCarbonEmission" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="AverageOffsetEmissionperMonth" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="OffsetAnnualCarbonFootprint" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="DifferenceofAnnualCarbonFootprint" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="FormSubmitOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NoOfTreesNeededValue" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="FundNeededToPlantTreesValue" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="PersonalTransportDropdownValue" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="PersonalTransportValue" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="PublicTransportValue" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="OnlineMeetingValue" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="FiveStarAppliancesValue" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="OffSetWithCarPooling" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="OffSetwithCNG" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="OffSetwithElectricVehicle" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="OffSetwithCycle" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="OffSetWithPublicTransport" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="EmissionfromAirtrip" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="PlantationTreesNeeded" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="PlantationTreesNeededValue" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TransmissionContactFormRecord" Member="TransmissionContactFormRecords">
    <Type Name="TransmissionContactFormRecord">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="MessageType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FormType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PageInfo" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FormSubmitOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TransmissionCostCalculatorOTPHistory" Member="TransmissionCostCalculatorOTPHistories">
    <Type Name="TransmissionCostCalculatorOTPHistory">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OTPType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OTPFor" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="OTP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TransmissionInsertCostCalculator" Member="TransmissionInsertCostCalculators">
    <Type Name="TransmissionInsertCostCalculator">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Login" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="RegistartionNumber" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="MonthName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Year" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="TotalFamilyMembers" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ElectricityConsumedAtResidence" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CNGUsed" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="LPGUsed_Val" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="LPGUsed" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="DieselConsumption" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="PetrolConsumption" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CNGAutoRickshaw" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="BusUse" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="TrainUse" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NumberofTrips" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="EmissionfromDomesticUse" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="EmissionfromTransportation" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="AverageEmissionperMonth" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="LandNeededtoPlantTrees" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NumberofTreesNeeded" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="AverageAnnualCarbonFootprint" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="AnnualCarbonFootprint" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CarbonEmissionReducePercentage" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CarbonEmissionReviewYear" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CarbonEmissionReviewDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PageInfo" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="FormType" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="FormSubmitOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NumberofTress" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ProjectName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="replacewithCNG" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="replacewithElectric" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="EstimatedCarbonAnnualizedValue" Type="System.String" DbType="NChar(250)" CanBeNull="true" />
      <Column Name="CNGUsed_Val" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="DieselConsumption_Val" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="PetrolConsumption_Val" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CNGAutoRickshaw_Val" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="BusUse_Val" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="TrainUse_Val" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ElectricityBillConsumption_Val" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ElectricityAppliancesListValues" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ElectricityAppliancesConsumption_Val" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ElectricityAppliancesConsumption" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="AirTripsDropdownList" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="AirTripsValue" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="AirTrips" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="EmissiontotalTripsValue" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="FinancialYear" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="FormUpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AverageOffsetEmissionperMonth" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="AnnualFYOffsetEmission" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TransmissionInsertCostCalculatorHistory" Member="TransmissionInsertCostCalculatorHistories">
    <Type Name="TransmissionInsertCostCalculatorHistory">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CostCalculatorID" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Login" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="RegistartionNumber" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="MonthName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Year" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="TotalFamilyMembers" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ElectricityConsumedAtResidence" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CNGUsed" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="LPGUsed_Val" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="LPGUsed" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="DieselConsumption" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="PetrolConsumption" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CNGAutoRickshaw" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="BusUse" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="TrainUse" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NumberofTrips" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="EmissionfromDomesticUse" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="EmissionfromTransportation" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="AverageEmissionperMonth" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="LandNeededtoPlantTrees" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NumberofTreesNeeded" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="AverageAnnualCarbonFootprint" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="AnnualCarbonFootprint" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CarbonEmissionReducePercentage" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CarbonEmissionReviewYear" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CarbonEmissionReviewDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PageInfo" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="FormType" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="FormSubmitOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NumberofTress" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="EstimatedCarbonAnnualizedValue" Type="System.String" DbType="NChar(250)" CanBeNull="true" />
      <Column Name="CNGUsed_Val" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="DieselConsumption_Val" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="PetrolConsumption_Val" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CNGAutoRickshaw_Val" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="BusUse_Val" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="TrainUse_Val" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ElectricityConsumedAtResidence_Val" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ElectricityConsumptionRadioButton" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TransmissionVendorEnquiryForm" Member="TransmissionVendorEnquiryForms">
    <Type Name="TransmissionVendorEnquiryForm">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RegistrationNo" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="MessageType" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="MobileNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PageInfo" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FormType" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FormSubmitOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SubmittedBy" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="LastUpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastUpdatedBy" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CurrentStatusPhase1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CurrentStatusPhase2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UpdateDateTimeHistory" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="StatusUpdateHistory" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ActionRemark" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UpdateCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InqTicketStatus" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Transmission_Carbon_CalculatorOTPHistory" Member="Transmission_Carbon_CalculatorOTPHistories">
    <Type Name="Transmission_Carbon_CalculatorOTPHistory">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OTPType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OTPFor" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="OTP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Isactive" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastAttemptdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>