<?xml version="1.0" encoding="utf-8"?><Database Name="Sitecore.ExperienceForms" Class="AdaniWelspunEntityDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=Sitecore.ExperienceForms;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="experienceforms" Provider="System.Data.SqlClient" />
  <Table Name="sitecore_forms_storage.FormEntries" Member="FormEntries">
    <Type Name="FormEntry">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FormDefinitionId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ContactId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="IsRedacted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Association Name="FormEntry_FieldData" Member="FieldDatas" ThisKey="Id" OtherKey="FormEntryId" Type="FieldData" />
    </Type>
  </Table>
  <Table Name="sitecore_forms_storage.FieldData" Member="FieldDatas">
    <Type Name="FieldData">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FormEntryId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="FieldDefinitionId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="FieldName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ValueType" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Association Name="FormEntry_FieldData" Member="FormEntry" ThisKey="FormEntryId" OtherKey="Id" Type="FormEntry" IsForeignKey="true" />
    </Type>
  </Table>
</Database>