<?xml version="1.0" encoding="utf-8"?><Database Name="adani-sc902_ExperienceForms" Class="WesternTransDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.FieldData" Member="FieldDatas">
    <Type Name="FieldData">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FormEntryID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="FieldItemID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="FieldName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ValueType" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Association Name="FormEntry_FieldData" Member="FormEntry" ThisKey="FormEntryID" OtherKey="ID" Type="FormEntry" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FormEntry" Member="FormEntries">
    <Type Name="FormEntry">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FormItemID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="FormEntry_FieldData" Member="FieldDatas" ThisKey="ID" OtherKey="FormEntryID" Type="FieldData" />
    </Type>
  </Table>
</Database>