<?xml version="1.0" encoding="utf-8"?><Database Name="ElectricityTender" Class="EnquiryDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=tcp:adanistaging-sql.database.windows.net;Initial Catalog=ElectricityTender;User ID=Sitecore" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ElectricityTenderConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.user_otp" Member="user_otps">
    <Type Name="user_otp">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MobileNumber" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="otp" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ExpiryTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="OtpPurpose" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RemainingAttempt" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>