<?xml version="1.0" encoding="utf-8"?><Database Name="Realty" Class="RealtyDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=tcp:adanistaging-sql.database.windows.net;Initial Catalog=Realty;User ID=Sitecore" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="RealtyConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Registration" Member="Registrations">
    <Type Name="Registration">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="UserType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Created_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Modified_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ConsolidateFormData" Member="ConsolidateFormDatas">
    <Type Name="ConsolidateFormData">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Budget" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PropertyType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PropertyLocation" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="sale_type" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FormType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PageInfo" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="FormSubmitOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UTMSource" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Lead_City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lead_Source" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Lead_Sub_Source" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Lead_Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lead_Sub_Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lead_Gender" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lead_Profession" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_ReasonForPurchase" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Lead_Property_Stage" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_Configuration" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_PreSalesAgent" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_InboundCall" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_Lost_Reasons" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="EntrySource" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ScheduledFollowUp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FormSubmitBy" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AdaniRealtyRentalForm" Member="AdaniRealtyRentalForms">
    <Type Name="AdaniRealtyRentalForm">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="ContactNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EmailId" Type="System.String" DbType="NVarChar(70)" CanBeNull="true" />
      <Column Name="Occupation" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Budget" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BrokerName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="BrokerContactNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SelectedApartmentSizes" Type="System.String" DbType="NVarChar(1500)" CanBeNull="true" />
      <Column Name="[1-BHK]" Member="_1_BHK" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[2-BHK]" Member="_2_BHK" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[2.5-BHK]" Member="_2_5_BHK" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[3-BHK]" Member="_3_BHK" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[3.5-BHK]" Member="_3_5_BHK" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[4-BHK]" Member="_4_BHK" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[4-BHK-PENT-HOUSE]" Member="_4_BHK_PENT_HOUSE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[4-BHK-VILLA]" Member="_4_BHK_VILLA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[5-BHK-PENT-HOUSE]" Member="_5_BHK_PENT_HOUSE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[5-BHK-VILLA]" Member="_5_BHK_VILLA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[6-BHK-VILLA]" Member="_6_BHK_VILLA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SelectedApartmentTypes" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="[BASIC-FITTINGS]" Member="BASIC_FITTINGS" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[FULLY-FURNISHED]" Member="FULLY_FURNISHED" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[SEMI-FURNISHED]" Member="SEMI_FURNISHED" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Remarks" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Referencefrom" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="SubmittedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FormName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PageInfo" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.OysterGrandeEnquireNow" Member="OysterGrandeEnquireNows">
    <Type Name="OysterGrandeEnquireNow">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="FormSubmitOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AsterEnquireNow" Member="AsterEnquireNows">
    <Type Name="AsterEnquireNow">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Budget" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PropertyType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PropertyLocation" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="sale_type" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FormType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PageInfo" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="FormSubmitOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UTMSource" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Lead_City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lead_Source" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Lead_Sub_Source" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Lead_Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lead_Sub_Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lead_Gender" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lead_Profession" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_ReasonForPurchase" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Lead_Property_Stage" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_Configuration" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_PreSalesAgent" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_InboundCall" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_Lost_Reasons" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="EntrySource" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ScheduledFollowUp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FormSubmitBy" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PageUrl" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>