<?xml version="1.0" encoding="utf-8"?><Database Name="Realty" Class="RealtyBookNowFormDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=tcp:adanistaging-sql.database.windows.net,1433;Initial Catalog=Realty;User ID=sitecore" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="RealtyConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.RealtyBookNowForm" Member="RealtyBookNowForms">
    <Type Name="RealtyBookNowForm">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PanNumber" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="AadharNumber" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="EmailAddress" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Remarks" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FormName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="PageInfo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PropertyName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="PropertyCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PropertyType" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ParentProject" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PaymentAmount" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GatewayType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PaymentType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TransactionId" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ResponseCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ResponseMessage" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PaymentMode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PaymentRef" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="OrderId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RequestTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ResponseTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Checksumkey" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CurrencyType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="msg" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Modified_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
</Database>