<?xml version="1.0" encoding="utf-8"?><Database Name="AdaniWind" Class="AdaniWindDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=ASUDP-SITECORE1;Initial Catalog=AdaniWind;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="AdaniWindConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AdaniWindContactUs" Member="AdaniWindContactUs">
    <Type Name="AdaniWindContactUs">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Fullname" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NChar(200)" CanBeNull="true" />
      <Column Name="ContactNo" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Purpose" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FormSubmittedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>