//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.Ports.Website.SailedLiquidServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SailedLiquidServiceReference.get_sailed_liquidSoap")]
    public interface get_sailed_liquidSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_sailed_liquid_data", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet get_sailed_liquid_data();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_sailed_liquid_data", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> get_sailed_liquid_dataAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface get_sailed_liquidSoapChannel : Sitecore.Ports.Website.SailedLiquidServiceReference.get_sailed_liquidSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class get_sailed_liquidSoapClient : System.ServiceModel.ClientBase<Sitecore.Ports.Website.SailedLiquidServiceReference.get_sailed_liquidSoap>, Sitecore.Ports.Website.SailedLiquidServiceReference.get_sailed_liquidSoap {
        
        public get_sailed_liquidSoapClient() {
        }
        
        public get_sailed_liquidSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public get_sailed_liquidSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public get_sailed_liquidSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public get_sailed_liquidSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet get_sailed_liquid_data() {
            return base.Channel.get_sailed_liquid_data();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> get_sailed_liquid_dataAsync() {
            return base.Channel.get_sailed_liquid_dataAsync();
        }
    }
}
