<?xml version="1.0" encoding="utf-8"?><Database Name="AdaniGas" Class="AdadniGasDBModelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.DODOForm" Member="DODOForms">
    <Type Name="DODOForm">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StateName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="GeographicalArea" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Salutation" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MiddleName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address1" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Address2" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Address3" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="District" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Pincode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LandlineNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Emailid" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Occupation" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OccuptionDetails" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LandPlotNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Nearest_Highway_No_Road" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Near_LandMark" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Road_going_towards" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NameOfCity" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NameOfDistrict" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NameofState" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NameofPincode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PlotSize" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PlotType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FrontViewPhoto" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="LeftSideEntryPhoto" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="RightSideExitPhoto" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="InsideOutViewPhoto" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Latitude" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Longtitude" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NearestPumpStationName" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="NearestPumpStationDistance" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="AnyPreviousExperience" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProposedEntity" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HowdidYouKnow" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AllowSMSAlert" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TermsAndCondition" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AgreeForPayment" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsPaymentDone" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TransactionId" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CustomerID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OMC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OMCYear" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OldId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SerialNumber" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PaymentHistoryData" Member="PaymentHistoryDatas">
    <Type Name="PaymentHistoryData">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AccountNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OrderId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Amount" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RequestTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Checksumkey" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CurrencyType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GatewayType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CustomerType" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AdvanceAmmount" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PaymentType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TransactionId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Responsecode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ResponseTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PaymentRef" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ResponseMsg" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PaymentMode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Created_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Modified_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ISU_UPDATE_FLAG" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="ISU_UPDATE_DATETIME" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ISU_UPDATE_MESSAGE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ISUVDS_Update_Flag" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ISUVDS_Update_DateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ISUVDS_Update_Message" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Comp_Cat" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="SrNo" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Comp_Type" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Quantity_Min" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MessageText" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="IsAfterSalesService" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CustId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CustPass" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CustPartnerId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ENachRegistrationHistory" Member="ENachRegistrationHistories">
    <Type Name="ENachRegistrationHistory">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AccountNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OrderId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Amount" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RequestTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Checksumkey" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CurrencyType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GatewayType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CustomerType" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SIAmount" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AccountType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TransactionId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Responsecode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ResponseTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BankRefNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ResponseMsg" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PaymentMode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Created_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Modified_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ISU_UPDATE_FLAG" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="ISU_UPDATE_DATETIME" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ISU_UPDATE_MESSAGE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AccountHolderName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BankAccountNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BankName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UMRN" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ErrorStatus" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ErrorDescription" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Quantity_Min" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SapECSMsgFlag" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="SapECSMsg" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TxnDate" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsSapECSPostError" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.GasFormData" Member="GasFormDatas">
    <Type Name="GasFormData">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MessageType" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CustomerId" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="FormType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PageInfo" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FormSubmitOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NewConnectionData" Member="NewConnectionDatas">
    <Type Name="NewConnectionData">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EnquiryNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="ContactNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ConnectionTypeCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ConnectionType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CityCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CityName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="AreaCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AreaName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TypeOfHouse" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ApartmentComplex" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="OtherApartmentOrSociety" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TypeOfCustomer" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="OtherTypeOfCustomer" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Application" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="OtherApplication" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CurrentFuelUsing" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="OtherFuelUsing" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TypeOfIndustry" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="OtherTypeOfIndustry" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="MonthlyConsumption" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="HouseNo_BuildingNo" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="AddressLine1" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AddressLine2" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Pincode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ReferenceSource" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CampaignID" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="FormURL" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SubmitOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SubmittedBy" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CNG_DealerDetailsSubmit" Member="CNG_DealerDetailsSubmits">
    <Type Name="CNG_DealerDetailsSubmit">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RegistrationNo" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="VendorRegistrationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="VendorNumber" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="MobileNumber" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CNGKitNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UploadVehicleInsurance" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="UploadVehicleInsuranceLink" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="UploadVehicleInsuranceFileType" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="UploadVehicleInsuranceFileName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="UploadRCBook" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="UploadRCBookLink" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="UploadRCBookFileType" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="UploadRCBookFileName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="UploadAadharCard" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="UploadAadharCardLink" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="UploadAadharCardFileType" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="UploadAadharCardFileName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="UploadPanCard" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="UploadPanCardLink" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="UploadPanCardFileType" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="UploadPanCardFileName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="PageUrl" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FormName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SubmittedOn" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CNG_RegisteredDealerInfo" Member="CNG_RegisteredDealerInfos">
    <Type Name="CNG_RegisteredDealerInfo">
      <Column Name="DealerId" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DealerName" Type="System.String" DbType="NVarChar(350)" CanBeNull="true" />
      <Column Name="DealerMobile" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="CNG_RegisteredDealerInfo_CNG_Document" Member="CNG_Documents" ThisKey="DealerId" OtherKey="CreatedBy" Type="CNG_Document" />
      <Association Name="CNG_RegisteredDealerInfo_CNG_DealerEnquiryRegistrationHistory" Member="CNG_DealerEnquiryRegistrationHistory1s" ThisKey="DealerId" OtherKey="DealerCode" Type="CNG_DealerEnquiryRegistrationHistory" />
      <Association Name="CNG_RegisteredDealerInfo_CNG_DealerEnquiryRegistrationHistory1" Member="CNG_DealerEnquiryRegistrationHistories" Storage="_CNG_DealerEnquiryRegistrationHistory1s1" ThisKey="DealerId" OtherKey="DealerCode" Type="CNG_DealerEnquiryRegistrationHistory" />
    </Type>
  </Table>
  <Table Name="dbo.CND_DocumentTypeList" Member="CND_DocumentTypeLists">
    <Type Name="CND_DocumentTypeList">
      <Column Name="Sr" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DocumentType" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.CNG_Documents" Member="CNG_Documents">
    <Type Name="CNG_Document">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CustRegistrationNo" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DocumentType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DocumentName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DocumentData" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DocumentContentType" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DocumentDescription" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Editable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="updatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsValidDoc" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ReviewedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="CNG_RegisteredDealerInfo_CNG_Document" Member="CNG_RegisteredDealerInfo" ThisKey="CreatedBy" OtherKey="DealerId" Type="CNG_RegisteredDealerInfo" IsForeignKey="true" />
      <Association Name="CNG_CustomerRegistration_CNG_Document" Member="CNG_CustomerRegistration" ThisKey="CustRegistrationNo" OtherKey="Id" Type="CNG_CustomerRegistration" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CNG_AdminUserDetails" Member="CNG_AdminUserDetails">
    <Type Name="CNG_AdminUserDetail">
      <Column Name="UserID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="UserCreatedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserAccessLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserLastLogin" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserRecentLogin" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserCreatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UserMobileNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserEmailId" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CNG_DealerEnquiryRegistrationHistory" Member="CNG_DealerEnquiryRegistrationHistories">
    <Type Name="CNG_DealerEnquiryRegistrationHistory">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EnquiryNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DealerCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CustomerRegistrationId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="CNGKitNumber" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="VehicleInsuranceFile" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="RC_bookFile" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="AadharCardFile" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="PanCardFile" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="InvoiceCopyFile" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CNG_CylinderCertifFile" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="RTO_ApplicationReceipt" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="RTO_CertificateCopy" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CustSignedSchemeDoc" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DocumentsVerified" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DocumentsVerifiedBy" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PageInfo" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CurrentStatus" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="UpdatesHistory" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="CNG_RegisteredDealerInfo_CNG_DealerEnquiryRegistrationHistory" Member="CNG_RegisteredDealerInfo" ThisKey="DealerCode" OtherKey="DealerId" Type="CNG_RegisteredDealerInfo" IsForeignKey="true" />
      <Association Name="CNG_RegisteredDealerInfo_CNG_DealerEnquiryRegistrationHistory1" Member="CNG_RegisteredDealerInfo1" ThisKey="DealerCode" OtherKey="DealerId" Type="CNG_RegisteredDealerInfo" IsForeignKey="true" />
      <Association Name="CNG_CustomerRegistration_CNG_DealerEnquiryRegistrationHistory" Member="CNG_CustomerRegistration" ThisKey="CustomerRegistrationId" OtherKey="Id" Type="CNG_CustomerRegistration" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CNG_CustomerRegistration" Member="CNG_CustomerRegistrations">
    <Type Name="CNG_CustomerRegistration">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RegistrationNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsBS_VI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="VehicleType" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="YearOfPurchase" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="EmailId" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MobileNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CurrentAddressLine1" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="CurrentAddressLine2" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="CurrentState" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CurrentCity" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CurrentArea" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="CurrentPincode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RegAddressLine1" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="RegAddressLine2" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="RegState" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="RegCity" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="RegArea" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="RegPincode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="VehicleCompany" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="VehicleModel" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="VehicleNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FormName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="PageInfo" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="SubmittedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="CNG_CustomerRegistration_CNG_Document" Member="CNG_Documents" ThisKey="Id" OtherKey="CustRegistrationNo" Type="CNG_Document" />
      <Association Name="CNG_CustomerRegistration_CNG_DealerEnquiryRegistrationHistory" Member="CNG_DealerEnquiryRegistrationHistories" ThisKey="Id" OtherKey="CustomerRegistrationId" Type="CNG_DealerEnquiryRegistrationHistory" />
    </Type>
  </Table>
</Database>