<?xml version="1.0" encoding="utf-8"?><Database Name="ElectricityTender" Class="ElectricitySelfMeterReadingDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=ASUDP-SITECORE1;Initial Catalog=ElectricityTender;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ElectricityTenderConnectionString3" Provider="System.Data.SqlClient" />
  <Table Name="dbo.SelfMeterReading" Member="SelfMeterReadings">
    <Type Name="SelfMeterReading">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AccountNumber" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Source" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="MeterNumber" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="MeterReading" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="MeterReadingDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MobileNumber" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="MeterPhoto" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Created_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ContentType" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DocData" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>