#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.Feature.Accounts
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AdaniGas")]
	public partial class NameTransferRequestDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertNameTransferPaymentHistory(NameTransferPaymentHistory instance);
    partial void UpdateNameTransferPaymentHistory(NameTransferPaymentHistory instance);
    partial void DeleteNameTransferPaymentHistory(NameTransferPaymentHistory instance);
    partial void InsertNameTransferAdminRegistration(NameTransferAdminRegistration instance);
    partial void UpdateNameTransferAdminRegistration(NameTransferAdminRegistration instance);
    partial void DeleteNameTransferAdminRegistration(NameTransferAdminRegistration instance);
    partial void InsertNameTransferDocument(NameTransferDocument instance);
    partial void UpdateNameTransferDocument(NameTransferDocument instance);
    partial void DeleteNameTransferDocument(NameTransferDocument instance);
    partial void InsertNameTransferApplicationCheckStatus(NameTransferApplicationCheckStatus instance);
    partial void UpdateNameTransferApplicationCheckStatus(NameTransferApplicationCheckStatus instance);
    partial void DeleteNameTransferApplicationCheckStatus(NameTransferApplicationCheckStatus instance);
    partial void InsertNameTransferChangeNameByAdmin(NameTransferChangeNameByAdmin instance);
    partial void UpdateNameTransferChangeNameByAdmin(NameTransferChangeNameByAdmin instance);
    partial void DeleteNameTransferChangeNameByAdmin(NameTransferChangeNameByAdmin instance);
    partial void InsertNameTransferRequestDetail(NameTransferRequestDetail instance);
    partial void UpdateNameTransferRequestDetail(NameTransferRequestDetail instance);
    partial void DeleteNameTransferRequestDetail(NameTransferRequestDetail instance);
        #endregion

        public NameTransferRequestDataContext() :

 base(global::System.Configuration.ConfigurationManager.ConnectionStrings["AdaniGasConnectionString"].ConnectionString, mappingSource)
        {
            OnCreated();
        }

        public NameTransferRequestDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NameTransferRequestDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NameTransferRequestDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NameTransferRequestDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<NameTransferPaymentHistory> NameTransferPaymentHistories
		{
			get
			{
				return this.GetTable<NameTransferPaymentHistory>();
			}
		}
		
		public System.Data.Linq.Table<NameTransferAdminRegistration> NameTransferAdminRegistrations
		{
			get
			{
				return this.GetTable<NameTransferAdminRegistration>();
			}
		}
		
		public System.Data.Linq.Table<NameTransferStatus> NameTransferStatus
		{
			get
			{
				return this.GetTable<NameTransferStatus>();
			}
		}
		
		public System.Data.Linq.Table<NameTransferDocument> NameTransferDocuments
		{
			get
			{
				return this.GetTable<NameTransferDocument>();
			}
		}
		
		public System.Data.Linq.Table<NameTransferApplicationCheckStatus> NameTransferApplicationCheckStatus
		{
			get
			{
				return this.GetTable<NameTransferApplicationCheckStatus>();
			}
		}
		
		public System.Data.Linq.Table<NameTransferChangeNameByAdmin> NameTransferChangeNameByAdmins
		{
			get
			{
				return this.GetTable<NameTransferChangeNameByAdmin>();
			}
		}
		
		public System.Data.Linq.Table<NameTransferRequestDetail> NameTransferRequestDetails
		{
			get
			{
				return this.GetTable<NameTransferRequestDetail>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NameTransferPaymentHistory")]
	public partial class NameTransferPaymentHistory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private System.Guid _NameTransferId;
		
		private string _AccountNumber;
		
		private string _UserId;
		
		private string _OrderId;
		
		private string _Amount;
		
		private System.Nullable<System.DateTime> _RequestTime;
		
		private string _Checksumkey;
		
		private string _CurrencyType;
		
		private string _GatewayType;
		
		private string _CustomerType;
		
		private string _AdvanceAmmount;
		
		private string _PaymentType;
		
		private string _UserType;
		
		private string _Email;
		
		private string _Mobile;
		
		private string _TransactionId;
		
		private string _Status;
		
		private string _Responsecode;
		
		private string _Remark;
		
		private System.Nullable<System.DateTime> _ResponseTime;
		
		private string _PaymentRef;
		
		private string _ResponseMsg;
		
		private string _PaymentMode;
		
		private System.Nullable<System.DateTime> _Created_Date;
		
		private string _CreatedBy;
		
		private System.Nullable<System.DateTime> _Modified_Date;
		
		private string _ModifiedBy;
		
		private string _ISU_UPDATE_FLAG;
		
		private System.Nullable<System.DateTime> _ISU_UPDATE_DATETIME;
		
		private string _ISU_UPDATE_MESSAGE;
		
		private string _ISUVDS_Update_Flag;
		
		private System.Nullable<System.DateTime> _ISUVDS_Update_DateTime;
		
		private string _ISUVDS_Update_Message;
		
		private string _Comp_Cat;
		
		private string _SrNo;
		
		private string _Comp_Type;
		
		private System.Nullable<int> _Quantity_Min;
		
		private string _MessageText;
		
		private System.Nullable<bool> _IsAfterSalesService;
		
		private string _CustId;
		
		private string _CustPass;
		
		private string _CustPartnerId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnNameTransferIdChanging(System.Guid value);
    partial void OnNameTransferIdChanged();
    partial void OnAccountNumberChanging(string value);
    partial void OnAccountNumberChanged();
    partial void OnUserIdChanging(string value);
    partial void OnUserIdChanged();
    partial void OnOrderIdChanging(string value);
    partial void OnOrderIdChanged();
    partial void OnAmountChanging(string value);
    partial void OnAmountChanged();
    partial void OnRequestTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnRequestTimeChanged();
    partial void OnChecksumkeyChanging(string value);
    partial void OnChecksumkeyChanged();
    partial void OnCurrencyTypeChanging(string value);
    partial void OnCurrencyTypeChanged();
    partial void OnGatewayTypeChanging(string value);
    partial void OnGatewayTypeChanged();
    partial void OnCustomerTypeChanging(string value);
    partial void OnCustomerTypeChanged();
    partial void OnAdvanceAmmountChanging(string value);
    partial void OnAdvanceAmmountChanged();
    partial void OnPaymentTypeChanging(string value);
    partial void OnPaymentTypeChanged();
    partial void OnUserTypeChanging(string value);
    partial void OnUserTypeChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnMobileChanging(string value);
    partial void OnMobileChanged();
    partial void OnTransactionIdChanging(string value);
    partial void OnTransactionIdChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnResponsecodeChanging(string value);
    partial void OnResponsecodeChanged();
    partial void OnRemarkChanging(string value);
    partial void OnRemarkChanged();
    partial void OnResponseTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnResponseTimeChanged();
    partial void OnPaymentRefChanging(string value);
    partial void OnPaymentRefChanged();
    partial void OnResponseMsgChanging(string value);
    partial void OnResponseMsgChanged();
    partial void OnPaymentModeChanging(string value);
    partial void OnPaymentModeChanged();
    partial void OnCreated_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreated_DateChanged();
    partial void OnCreatedByChanging(string value);
    partial void OnCreatedByChanged();
    partial void OnModified_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnModified_DateChanged();
    partial void OnModifiedByChanging(string value);
    partial void OnModifiedByChanged();
    partial void OnISU_UPDATE_FLAGChanging(string value);
    partial void OnISU_UPDATE_FLAGChanged();
    partial void OnISU_UPDATE_DATETIMEChanging(System.Nullable<System.DateTime> value);
    partial void OnISU_UPDATE_DATETIMEChanged();
    partial void OnISU_UPDATE_MESSAGEChanging(string value);
    partial void OnISU_UPDATE_MESSAGEChanged();
    partial void OnISUVDS_Update_FlagChanging(string value);
    partial void OnISUVDS_Update_FlagChanged();
    partial void OnISUVDS_Update_DateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnISUVDS_Update_DateTimeChanged();
    partial void OnISUVDS_Update_MessageChanging(string value);
    partial void OnISUVDS_Update_MessageChanged();
    partial void OnComp_CatChanging(string value);
    partial void OnComp_CatChanged();
    partial void OnSrNoChanging(string value);
    partial void OnSrNoChanged();
    partial void OnComp_TypeChanging(string value);
    partial void OnComp_TypeChanged();
    partial void OnQuantity_MinChanging(System.Nullable<int> value);
    partial void OnQuantity_MinChanged();
    partial void OnMessageTextChanging(string value);
    partial void OnMessageTextChanged();
    partial void OnIsAfterSalesServiceChanging(System.Nullable<bool> value);
    partial void OnIsAfterSalesServiceChanged();
    partial void OnCustIdChanging(string value);
    partial void OnCustIdChanged();
    partial void OnCustPassChanging(string value);
    partial void OnCustPassChanged();
    partial void OnCustPartnerIdChanging(string value);
    partial void OnCustPartnerIdChanged();
    #endregion
		
		public NameTransferPaymentHistory()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameTransferId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid NameTransferId
		{
			get
			{
				return this._NameTransferId;
			}
			set
			{
				if ((this._NameTransferId != value))
				{
					this.OnNameTransferIdChanging(value);
					this.SendPropertyChanging();
					this._NameTransferId = value;
					this.SendPropertyChanged("NameTransferId");
					this.OnNameTransferIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountNumber", DbType="NVarChar(50)")]
		public string AccountNumber
		{
			get
			{
				return this._AccountNumber;
			}
			set
			{
				if ((this._AccountNumber != value))
				{
					this.OnAccountNumberChanging(value);
					this.SendPropertyChanging();
					this._AccountNumber = value;
					this.SendPropertyChanged("AccountNumber");
					this.OnAccountNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="NVarChar(50)")]
		public string UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderId", DbType="NVarChar(50)")]
		public string OrderId
		{
			get
			{
				return this._OrderId;
			}
			set
			{
				if ((this._OrderId != value))
				{
					this.OnOrderIdChanging(value);
					this.SendPropertyChanging();
					this._OrderId = value;
					this.SendPropertyChanged("OrderId");
					this.OnOrderIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="NVarChar(50)")]
		public string Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this.OnAmountChanging(value);
					this.SendPropertyChanging();
					this._Amount = value;
					this.SendPropertyChanged("Amount");
					this.OnAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> RequestTime
		{
			get
			{
				return this._RequestTime;
			}
			set
			{
				if ((this._RequestTime != value))
				{
					this.OnRequestTimeChanging(value);
					this.SendPropertyChanging();
					this._RequestTime = value;
					this.SendPropertyChanged("RequestTime");
					this.OnRequestTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Checksumkey", DbType="NVarChar(50)")]
		public string Checksumkey
		{
			get
			{
				return this._Checksumkey;
			}
			set
			{
				if ((this._Checksumkey != value))
				{
					this.OnChecksumkeyChanging(value);
					this.SendPropertyChanging();
					this._Checksumkey = value;
					this.SendPropertyChanged("Checksumkey");
					this.OnChecksumkeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrencyType", DbType="NVarChar(50)")]
		public string CurrencyType
		{
			get
			{
				return this._CurrencyType;
			}
			set
			{
				if ((this._CurrencyType != value))
				{
					this.OnCurrencyTypeChanging(value);
					this.SendPropertyChanging();
					this._CurrencyType = value;
					this.SendPropertyChanged("CurrencyType");
					this.OnCurrencyTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GatewayType", DbType="NVarChar(50)")]
		public string GatewayType
		{
			get
			{
				return this._GatewayType;
			}
			set
			{
				if ((this._GatewayType != value))
				{
					this.OnGatewayTypeChanging(value);
					this.SendPropertyChanging();
					this._GatewayType = value;
					this.SendPropertyChanged("GatewayType");
					this.OnGatewayTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerType", DbType="NVarChar(MAX)")]
		public string CustomerType
		{
			get
			{
				return this._CustomerType;
			}
			set
			{
				if ((this._CustomerType != value))
				{
					this.OnCustomerTypeChanging(value);
					this.SendPropertyChanging();
					this._CustomerType = value;
					this.SendPropertyChanged("CustomerType");
					this.OnCustomerTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdvanceAmmount", DbType="NVarChar(50)")]
		public string AdvanceAmmount
		{
			get
			{
				return this._AdvanceAmmount;
			}
			set
			{
				if ((this._AdvanceAmmount != value))
				{
					this.OnAdvanceAmmountChanging(value);
					this.SendPropertyChanging();
					this._AdvanceAmmount = value;
					this.SendPropertyChanged("AdvanceAmmount");
					this.OnAdvanceAmmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentType", DbType="NVarChar(50)")]
		public string PaymentType
		{
			get
			{
				return this._PaymentType;
			}
			set
			{
				if ((this._PaymentType != value))
				{
					this.OnPaymentTypeChanging(value);
					this.SendPropertyChanging();
					this._PaymentType = value;
					this.SendPropertyChanged("PaymentType");
					this.OnPaymentTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserType", DbType="NVarChar(50)")]
		public string UserType
		{
			get
			{
				return this._UserType;
			}
			set
			{
				if ((this._UserType != value))
				{
					this.OnUserTypeChanging(value);
					this.SendPropertyChanging();
					this._UserType = value;
					this.SendPropertyChanged("UserType");
					this.OnUserTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="NVarChar(50)")]
		public string Mobile
		{
			get
			{
				return this._Mobile;
			}
			set
			{
				if ((this._Mobile != value))
				{
					this.OnMobileChanging(value);
					this.SendPropertyChanging();
					this._Mobile = value;
					this.SendPropertyChanged("Mobile");
					this.OnMobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactionId", DbType="NVarChar(50)")]
		public string TransactionId
		{
			get
			{
				return this._TransactionId;
			}
			set
			{
				if ((this._TransactionId != value))
				{
					this.OnTransactionIdChanging(value);
					this.SendPropertyChanging();
					this._TransactionId = value;
					this.SendPropertyChanged("TransactionId");
					this.OnTransactionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Responsecode", DbType="NVarChar(50)")]
		public string Responsecode
		{
			get
			{
				return this._Responsecode;
			}
			set
			{
				if ((this._Responsecode != value))
				{
					this.OnResponsecodeChanging(value);
					this.SendPropertyChanging();
					this._Responsecode = value;
					this.SendPropertyChanged("Responsecode");
					this.OnResponsecodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="VarChar(MAX)")]
		public string Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this.OnRemarkChanging(value);
					this.SendPropertyChanging();
					this._Remark = value;
					this.SendPropertyChanged("Remark");
					this.OnRemarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResponseTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> ResponseTime
		{
			get
			{
				return this._ResponseTime;
			}
			set
			{
				if ((this._ResponseTime != value))
				{
					this.OnResponseTimeChanging(value);
					this.SendPropertyChanging();
					this._ResponseTime = value;
					this.SendPropertyChanged("ResponseTime");
					this.OnResponseTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentRef", DbType="NVarChar(50)")]
		public string PaymentRef
		{
			get
			{
				return this._PaymentRef;
			}
			set
			{
				if ((this._PaymentRef != value))
				{
					this.OnPaymentRefChanging(value);
					this.SendPropertyChanging();
					this._PaymentRef = value;
					this.SendPropertyChanged("PaymentRef");
					this.OnPaymentRefChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResponseMsg", DbType="NVarChar(MAX)")]
		public string ResponseMsg
		{
			get
			{
				return this._ResponseMsg;
			}
			set
			{
				if ((this._ResponseMsg != value))
				{
					this.OnResponseMsgChanging(value);
					this.SendPropertyChanging();
					this._ResponseMsg = value;
					this.SendPropertyChanged("ResponseMsg");
					this.OnResponseMsgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentMode", DbType="NVarChar(100)")]
		public string PaymentMode
		{
			get
			{
				return this._PaymentMode;
			}
			set
			{
				if ((this._PaymentMode != value))
				{
					this.OnPaymentModeChanging(value);
					this.SendPropertyChanging();
					this._PaymentMode = value;
					this.SendPropertyChanged("PaymentMode");
					this.OnPaymentModeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Created_Date
		{
			get
			{
				return this._Created_Date;
			}
			set
			{
				if ((this._Created_Date != value))
				{
					this.OnCreated_DateChanging(value);
					this.SendPropertyChanging();
					this._Created_Date = value;
					this.SendPropertyChanged("Created_Date");
					this.OnCreated_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="NVarChar(50)")]
		public string CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modified_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Modified_Date
		{
			get
			{
				return this._Modified_Date;
			}
			set
			{
				if ((this._Modified_Date != value))
				{
					this.OnModified_DateChanging(value);
					this.SendPropertyChanging();
					this._Modified_Date = value;
					this.SendPropertyChanged("Modified_Date");
					this.OnModified_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedBy", DbType="NVarChar(50)")]
		public string ModifiedBy
		{
			get
			{
				return this._ModifiedBy;
			}
			set
			{
				if ((this._ModifiedBy != value))
				{
					this.OnModifiedByChanging(value);
					this.SendPropertyChanging();
					this._ModifiedBy = value;
					this.SendPropertyChanged("ModifiedBy");
					this.OnModifiedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISU_UPDATE_FLAG", DbType="NChar(100)")]
		public string ISU_UPDATE_FLAG
		{
			get
			{
				return this._ISU_UPDATE_FLAG;
			}
			set
			{
				if ((this._ISU_UPDATE_FLAG != value))
				{
					this.OnISU_UPDATE_FLAGChanging(value);
					this.SendPropertyChanging();
					this._ISU_UPDATE_FLAG = value;
					this.SendPropertyChanged("ISU_UPDATE_FLAG");
					this.OnISU_UPDATE_FLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISU_UPDATE_DATETIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> ISU_UPDATE_DATETIME
		{
			get
			{
				return this._ISU_UPDATE_DATETIME;
			}
			set
			{
				if ((this._ISU_UPDATE_DATETIME != value))
				{
					this.OnISU_UPDATE_DATETIMEChanging(value);
					this.SendPropertyChanging();
					this._ISU_UPDATE_DATETIME = value;
					this.SendPropertyChanged("ISU_UPDATE_DATETIME");
					this.OnISU_UPDATE_DATETIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISU_UPDATE_MESSAGE", DbType="NVarChar(MAX)")]
		public string ISU_UPDATE_MESSAGE
		{
			get
			{
				return this._ISU_UPDATE_MESSAGE;
			}
			set
			{
				if ((this._ISU_UPDATE_MESSAGE != value))
				{
					this.OnISU_UPDATE_MESSAGEChanging(value);
					this.SendPropertyChanging();
					this._ISU_UPDATE_MESSAGE = value;
					this.SendPropertyChanged("ISU_UPDATE_MESSAGE");
					this.OnISU_UPDATE_MESSAGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISUVDS_Update_Flag", DbType="NVarChar(MAX)")]
		public string ISUVDS_Update_Flag
		{
			get
			{
				return this._ISUVDS_Update_Flag;
			}
			set
			{
				if ((this._ISUVDS_Update_Flag != value))
				{
					this.OnISUVDS_Update_FlagChanging(value);
					this.SendPropertyChanging();
					this._ISUVDS_Update_Flag = value;
					this.SendPropertyChanged("ISUVDS_Update_Flag");
					this.OnISUVDS_Update_FlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISUVDS_Update_DateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> ISUVDS_Update_DateTime
		{
			get
			{
				return this._ISUVDS_Update_DateTime;
			}
			set
			{
				if ((this._ISUVDS_Update_DateTime != value))
				{
					this.OnISUVDS_Update_DateTimeChanging(value);
					this.SendPropertyChanging();
					this._ISUVDS_Update_DateTime = value;
					this.SendPropertyChanged("ISUVDS_Update_DateTime");
					this.OnISUVDS_Update_DateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISUVDS_Update_Message", DbType="NVarChar(MAX)")]
		public string ISUVDS_Update_Message
		{
			get
			{
				return this._ISUVDS_Update_Message;
			}
			set
			{
				if ((this._ISUVDS_Update_Message != value))
				{
					this.OnISUVDS_Update_MessageChanging(value);
					this.SendPropertyChanging();
					this._ISUVDS_Update_Message = value;
					this.SendPropertyChanged("ISUVDS_Update_Message");
					this.OnISUVDS_Update_MessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comp_Cat", DbType="NVarChar(200)")]
		public string Comp_Cat
		{
			get
			{
				return this._Comp_Cat;
			}
			set
			{
				if ((this._Comp_Cat != value))
				{
					this.OnComp_CatChanging(value);
					this.SendPropertyChanging();
					this._Comp_Cat = value;
					this.SendPropertyChanged("Comp_Cat");
					this.OnComp_CatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SrNo", DbType="NVarChar(100)")]
		public string SrNo
		{
			get
			{
				return this._SrNo;
			}
			set
			{
				if ((this._SrNo != value))
				{
					this.OnSrNoChanging(value);
					this.SendPropertyChanging();
					this._SrNo = value;
					this.SendPropertyChanged("SrNo");
					this.OnSrNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comp_Type", DbType="NVarChar(200)")]
		public string Comp_Type
		{
			get
			{
				return this._Comp_Type;
			}
			set
			{
				if ((this._Comp_Type != value))
				{
					this.OnComp_TypeChanging(value);
					this.SendPropertyChanging();
					this._Comp_Type = value;
					this.SendPropertyChanged("Comp_Type");
					this.OnComp_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity_Min", DbType="Int")]
		public System.Nullable<int> Quantity_Min
		{
			get
			{
				return this._Quantity_Min;
			}
			set
			{
				if ((this._Quantity_Min != value))
				{
					this.OnQuantity_MinChanging(value);
					this.SendPropertyChanging();
					this._Quantity_Min = value;
					this.SendPropertyChanged("Quantity_Min");
					this.OnQuantity_MinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MessageText", DbType="NVarChar(1000)")]
		public string MessageText
		{
			get
			{
				return this._MessageText;
			}
			set
			{
				if ((this._MessageText != value))
				{
					this.OnMessageTextChanging(value);
					this.SendPropertyChanging();
					this._MessageText = value;
					this.SendPropertyChanged("MessageText");
					this.OnMessageTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAfterSalesService", DbType="Bit")]
		public System.Nullable<bool> IsAfterSalesService
		{
			get
			{
				return this._IsAfterSalesService;
			}
			set
			{
				if ((this._IsAfterSalesService != value))
				{
					this.OnIsAfterSalesServiceChanging(value);
					this.SendPropertyChanging();
					this._IsAfterSalesService = value;
					this.SendPropertyChanged("IsAfterSalesService");
					this.OnIsAfterSalesServiceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustId", DbType="NVarChar(50)")]
		public string CustId
		{
			get
			{
				return this._CustId;
			}
			set
			{
				if ((this._CustId != value))
				{
					this.OnCustIdChanging(value);
					this.SendPropertyChanging();
					this._CustId = value;
					this.SendPropertyChanged("CustId");
					this.OnCustIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustPass", DbType="NVarChar(50)")]
		public string CustPass
		{
			get
			{
				return this._CustPass;
			}
			set
			{
				if ((this._CustPass != value))
				{
					this.OnCustPassChanging(value);
					this.SendPropertyChanging();
					this._CustPass = value;
					this.SendPropertyChanged("CustPass");
					this.OnCustPassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustPartnerId", DbType="NVarChar(50)")]
		public string CustPartnerId
		{
			get
			{
				return this._CustPartnerId;
			}
			set
			{
				if ((this._CustPartnerId != value))
				{
					this.OnCustPartnerIdChanging(value);
					this.SendPropertyChanging();
					this._CustPartnerId = value;
					this.SendPropertyChanged("CustPartnerId");
					this.OnCustPartnerIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NameTransferAdminRegistration")]
	public partial class NameTransferAdminRegistration : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _Name;
		
		private string _MobileNumber;
		
		private string _Email;
		
		private string _Username;
		
		private string _Password;
		
		private string _City;
		
		private System.Nullable<System.DateTime> _CreatedDate;
		
		private System.Nullable<System.DateTime> _ModifiedDate;
		
		private string _Role;
		
		private string _AdminStatus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnMobileNumberChanging(string value);
    partial void OnMobileNumberChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnCreatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedDateChanged();
    partial void OnModifiedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifiedDateChanged();
    partial void OnRoleChanging(string value);
    partial void OnRoleChanged();
    partial void OnAdminStatusChanging(string value);
    partial void OnAdminStatusChanged();
    #endregion
		
		public NameTransferAdminRegistration()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileNumber", DbType="NVarChar(50)")]
		public string MobileNumber
		{
			get
			{
				return this._MobileNumber;
			}
			set
			{
				if ((this._MobileNumber != value))
				{
					this.OnMobileNumberChanging(value);
					this.SendPropertyChanging();
					this._MobileNumber = value;
					this.SendPropertyChanged("MobileNumber");
					this.OnMobileNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(50)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="Date")]
		public System.Nullable<System.DateTime> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this.OnCreatedDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedDate = value;
					this.SendPropertyChanged("CreatedDate");
					this.OnCreatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedDate", DbType="Date")]
		public System.Nullable<System.DateTime> ModifiedDate
		{
			get
			{
				return this._ModifiedDate;
			}
			set
			{
				if ((this._ModifiedDate != value))
				{
					this.OnModifiedDateChanging(value);
					this.SendPropertyChanging();
					this._ModifiedDate = value;
					this.SendPropertyChanged("ModifiedDate");
					this.OnModifiedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role", DbType="NVarChar(50)")]
		public string Role
		{
			get
			{
				return this._Role;
			}
			set
			{
				if ((this._Role != value))
				{
					this.OnRoleChanging(value);
					this.SendPropertyChanging();
					this._Role = value;
					this.SendPropertyChanged("Role");
					this.OnRoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminStatus", DbType="NVarChar(10)")]
		public string AdminStatus
		{
			get
			{
				return this._AdminStatus;
			}
			set
			{
				if ((this._AdminStatus != value))
				{
					this.OnAdminStatusChanging(value);
					this.SendPropertyChanging();
					this._AdminStatus = value;
					this.SendPropertyChanged("AdminStatus");
					this.OnAdminStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NameTransferStatus")]
	public partial class NameTransferStatus
	{
		
		private System.Nullable<int> _Id;
		
		private string _NameTransferStatus1;
		
		private string _NameTransferStatusText;
		
		public NameTransferStatus()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int")]
		public System.Nullable<int> Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="NameTransferStatus", Storage="_NameTransferStatus1", DbType="NVarChar(100)")]
		public string NameTransferStatus1
		{
			get
			{
				return this._NameTransferStatus1;
			}
			set
			{
				if ((this._NameTransferStatus1 != value))
				{
					this._NameTransferStatus1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameTransferStatusText", DbType="NVarChar(100)")]
		public string NameTransferStatusText
		{
			get
			{
				return this._NameTransferStatusText;
			}
			set
			{
				if ((this._NameTransferStatusText != value))
				{
					this._NameTransferStatusText = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NameTransferDocuments")]
	public partial class NameTransferDocument : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _NameTransferId;
		
		private string _FileName;
		
		private string _ContentType;
		
		private System.Data.Linq.Binary _DocData;
		
		private System.Nullable<System.DateTime> _CreatedDate;
		
		private System.Nullable<System.DateTime> _ModifiedDate;
		
		private string _DocumentType;
		
		private string _DocumentStatus;
		
		private string _AdminComment;
		
		private string _UploadDocumentSAPResponse;
		
		private System.Nullable<bool> _SAPUploadDocumentStatus;
		
		private string _SubDocumentType;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnNameTransferIdChanging(string value);
    partial void OnNameTransferIdChanged();
    partial void OnFileNameChanging(string value);
    partial void OnFileNameChanged();
    partial void OnContentTypeChanging(string value);
    partial void OnContentTypeChanged();
    partial void OnDocDataChanging(System.Data.Linq.Binary value);
    partial void OnDocDataChanged();
    partial void OnCreatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedDateChanged();
    partial void OnModifiedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifiedDateChanged();
    partial void OnDocumentTypeChanging(string value);
    partial void OnDocumentTypeChanged();
    partial void OnDocumentStatusChanging(string value);
    partial void OnDocumentStatusChanged();
    partial void OnAdminCommentChanging(string value);
    partial void OnAdminCommentChanged();
    partial void OnUploadDocumentSAPResponseChanging(string value);
    partial void OnUploadDocumentSAPResponseChanged();
    partial void OnSAPUploadDocumentStatusChanging(System.Nullable<bool> value);
    partial void OnSAPUploadDocumentStatusChanged();
    partial void OnSubDocumentTypeChanging(string value);
    partial void OnSubDocumentTypeChanged();
    #endregion
		
		public NameTransferDocument()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameTransferId", DbType="NVarChar(50)")]
		public string NameTransferId
		{
			get
			{
				return this._NameTransferId;
			}
			set
			{
				if ((this._NameTransferId != value))
				{
					this.OnNameTransferIdChanging(value);
					this.SendPropertyChanging();
					this._NameTransferId = value;
					this.SendPropertyChanged("NameTransferId");
					this.OnNameTransferIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="NVarChar(500)")]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this.OnFileNameChanging(value);
					this.SendPropertyChanging();
					this._FileName = value;
					this.SendPropertyChanged("FileName");
					this.OnFileNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContentType", DbType="NVarChar(MAX)")]
		public string ContentType
		{
			get
			{
				return this._ContentType;
			}
			set
			{
				if ((this._ContentType != value))
				{
					this.OnContentTypeChanging(value);
					this.SendPropertyChanging();
					this._ContentType = value;
					this.SendPropertyChanged("ContentType");
					this.OnContentTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocData", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary DocData
		{
			get
			{
				return this._DocData;
			}
			set
			{
				if ((this._DocData != value))
				{
					this.OnDocDataChanging(value);
					this.SendPropertyChanging();
					this._DocData = value;
					this.SendPropertyChanged("DocData");
					this.OnDocDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this.OnCreatedDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedDate = value;
					this.SendPropertyChanged("CreatedDate");
					this.OnCreatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifiedDate
		{
			get
			{
				return this._ModifiedDate;
			}
			set
			{
				if ((this._ModifiedDate != value))
				{
					this.OnModifiedDateChanging(value);
					this.SendPropertyChanging();
					this._ModifiedDate = value;
					this.SendPropertyChanged("ModifiedDate");
					this.OnModifiedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentType", DbType="NVarChar(150)")]
		public string DocumentType
		{
			get
			{
				return this._DocumentType;
			}
			set
			{
				if ((this._DocumentType != value))
				{
					this.OnDocumentTypeChanging(value);
					this.SendPropertyChanging();
					this._DocumentType = value;
					this.SendPropertyChanged("DocumentType");
					this.OnDocumentTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentStatus", DbType="NVarChar(500)")]
		public string DocumentStatus
		{
			get
			{
				return this._DocumentStatus;
			}
			set
			{
				if ((this._DocumentStatus != value))
				{
					this.OnDocumentStatusChanging(value);
					this.SendPropertyChanging();
					this._DocumentStatus = value;
					this.SendPropertyChanged("DocumentStatus");
					this.OnDocumentStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminComment", DbType="NVarChar(500)")]
		public string AdminComment
		{
			get
			{
				return this._AdminComment;
			}
			set
			{
				if ((this._AdminComment != value))
				{
					this.OnAdminCommentChanging(value);
					this.SendPropertyChanging();
					this._AdminComment = value;
					this.SendPropertyChanged("AdminComment");
					this.OnAdminCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UploadDocumentSAPResponse", DbType="NVarChar(100)")]
		public string UploadDocumentSAPResponse
		{
			get
			{
				return this._UploadDocumentSAPResponse;
			}
			set
			{
				if ((this._UploadDocumentSAPResponse != value))
				{
					this.OnUploadDocumentSAPResponseChanging(value);
					this.SendPropertyChanging();
					this._UploadDocumentSAPResponse = value;
					this.SendPropertyChanged("UploadDocumentSAPResponse");
					this.OnUploadDocumentSAPResponseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAPUploadDocumentStatus", DbType="Bit")]
		public System.Nullable<bool> SAPUploadDocumentStatus
		{
			get
			{
				return this._SAPUploadDocumentStatus;
			}
			set
			{
				if ((this._SAPUploadDocumentStatus != value))
				{
					this.OnSAPUploadDocumentStatusChanging(value);
					this.SendPropertyChanging();
					this._SAPUploadDocumentStatus = value;
					this.SendPropertyChanged("SAPUploadDocumentStatus");
					this.OnSAPUploadDocumentStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubDocumentType", DbType="NVarChar(50)")]
		public string SubDocumentType
		{
			get
			{
				return this._SubDocumentType;
			}
			set
			{
				if ((this._SubDocumentType != value))
				{
					this.OnSubDocumentTypeChanging(value);
					this.SendPropertyChanging();
					this._SubDocumentType = value;
					this.SendPropertyChanged("SubDocumentType");
					this.OnSubDocumentTypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NameTransferApplicationCheckStatus")]
	public partial class NameTransferApplicationCheckStatus : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _UserId;
		
		private string _RequestNumber;
		
		private string _Status;
		
		private System.Nullable<System.DateTime> _CreatedDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnUserIdChanging(string value);
    partial void OnUserIdChanged();
    partial void OnRequestNumberChanging(string value);
    partial void OnRequestNumberChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnCreatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedDateChanged();
    #endregion
		
		public NameTransferApplicationCheckStatus()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="NVarChar(50)")]
		public string UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestNumber", DbType="NVarChar(50)")]
		public string RequestNumber
		{
			get
			{
				return this._RequestNumber;
			}
			set
			{
				if ((this._RequestNumber != value))
				{
					this.OnRequestNumberChanging(value);
					this.SendPropertyChanging();
					this._RequestNumber = value;
					this.SendPropertyChanged("RequestNumber");
					this.OnRequestNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this.OnCreatedDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedDate = value;
					this.SendPropertyChanged("CreatedDate");
					this.OnCreatedDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NameTransferChangeNameByAdmin")]
	public partial class NameTransferChangeNameByAdmin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _Activity;
		
		private string _UserId;
		
		private string _CustomerId;
		
		private string _Old_data;
		
		private string _New_data;
		
		private System.Nullable<System.DateTime> _Updated_Datetime;
		
		private string _Old_status;
		
		private string _New_status;
		
		private string _Comment;
		
		private System.Nullable<bool> _is_additional_documents_reuired;
		
		private System.Nullable<bool> _is_additional_payment_reuired;
		
		private System.Nullable<int> _Additional_Payment_Value;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnActivityChanging(string value);
    partial void OnActivityChanged();
    partial void OnUserIdChanging(string value);
    partial void OnUserIdChanged();
    partial void OnCustomerIdChanging(string value);
    partial void OnCustomerIdChanged();
    partial void OnOld_dataChanging(string value);
    partial void OnOld_dataChanged();
    partial void OnNew_dataChanging(string value);
    partial void OnNew_dataChanged();
    partial void OnUpdated_DatetimeChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdated_DatetimeChanged();
    partial void OnOld_statusChanging(string value);
    partial void OnOld_statusChanged();
    partial void OnNew_statusChanging(string value);
    partial void OnNew_statusChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    partial void Onis_additional_documents_reuiredChanging(System.Nullable<bool> value);
    partial void Onis_additional_documents_reuiredChanged();
    partial void Onis_additional_payment_reuiredChanging(System.Nullable<bool> value);
    partial void Onis_additional_payment_reuiredChanged();
    partial void OnAdditional_Payment_ValueChanging(System.Nullable<int> value);
    partial void OnAdditional_Payment_ValueChanged();
    #endregion
		
		public NameTransferChangeNameByAdmin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activity", DbType="NVarChar(MAX)")]
		public string Activity
		{
			get
			{
				return this._Activity;
			}
			set
			{
				if ((this._Activity != value))
				{
					this.OnActivityChanging(value);
					this.SendPropertyChanging();
					this._Activity = value;
					this.SendPropertyChanged("Activity");
					this.OnActivityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="NVarChar(MAX)")]
		public string UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerId", DbType="NVarChar(MAX)")]
		public string CustomerId
		{
			get
			{
				return this._CustomerId;
			}
			set
			{
				if ((this._CustomerId != value))
				{
					this.OnCustomerIdChanging(value);
					this.SendPropertyChanging();
					this._CustomerId = value;
					this.SendPropertyChanged("CustomerId");
					this.OnCustomerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Old_data", DbType="NVarChar(MAX)")]
		public string Old_data
		{
			get
			{
				return this._Old_data;
			}
			set
			{
				if ((this._Old_data != value))
				{
					this.OnOld_dataChanging(value);
					this.SendPropertyChanging();
					this._Old_data = value;
					this.SendPropertyChanged("Old_data");
					this.OnOld_dataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_New_data", DbType="NVarChar(MAX)")]
		public string New_data
		{
			get
			{
				return this._New_data;
			}
			set
			{
				if ((this._New_data != value))
				{
					this.OnNew_dataChanging(value);
					this.SendPropertyChanging();
					this._New_data = value;
					this.SendPropertyChanged("New_data");
					this.OnNew_dataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Updated_Datetime", DbType="DateTime")]
		public System.Nullable<System.DateTime> Updated_Datetime
		{
			get
			{
				return this._Updated_Datetime;
			}
			set
			{
				if ((this._Updated_Datetime != value))
				{
					this.OnUpdated_DatetimeChanging(value);
					this.SendPropertyChanging();
					this._Updated_Datetime = value;
					this.SendPropertyChanged("Updated_Datetime");
					this.OnUpdated_DatetimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Old_status", DbType="NVarChar(MAX)")]
		public string Old_status
		{
			get
			{
				return this._Old_status;
			}
			set
			{
				if ((this._Old_status != value))
				{
					this.OnOld_statusChanging(value);
					this.SendPropertyChanging();
					this._Old_status = value;
					this.SendPropertyChanged("Old_status");
					this.OnOld_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_New_status", DbType="NVarChar(MAX)")]
		public string New_status
		{
			get
			{
				return this._New_status;
			}
			set
			{
				if ((this._New_status != value))
				{
					this.OnNew_statusChanging(value);
					this.SendPropertyChanging();
					this._New_status = value;
					this.SendPropertyChanged("New_status");
					this.OnNew_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(MAX)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_additional_documents_reuired", DbType="Bit")]
		public System.Nullable<bool> is_additional_documents_reuired
		{
			get
			{
				return this._is_additional_documents_reuired;
			}
			set
			{
				if ((this._is_additional_documents_reuired != value))
				{
					this.Onis_additional_documents_reuiredChanging(value);
					this.SendPropertyChanging();
					this._is_additional_documents_reuired = value;
					this.SendPropertyChanged("is_additional_documents_reuired");
					this.Onis_additional_documents_reuiredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_additional_payment_reuired", DbType="Bit")]
		public System.Nullable<bool> is_additional_payment_reuired
		{
			get
			{
				return this._is_additional_payment_reuired;
			}
			set
			{
				if ((this._is_additional_payment_reuired != value))
				{
					this.Onis_additional_payment_reuiredChanging(value);
					this.SendPropertyChanging();
					this._is_additional_payment_reuired = value;
					this.SendPropertyChanged("is_additional_payment_reuired");
					this.Onis_additional_payment_reuiredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Additional_Payment_Value", DbType="Int")]
		public System.Nullable<int> Additional_Payment_Value
		{
			get
			{
				return this._Additional_Payment_Value;
			}
			set
			{
				if ((this._Additional_Payment_Value != value))
				{
					this.OnAdditional_Payment_ValueChanging(value);
					this.SendPropertyChanging();
					this._Additional_Payment_Value = value;
					this.SendPropertyChanged("Additional_Payment_Value");
					this.OnAdditional_Payment_ValueChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NameTransferRequestDetails")]
	public partial class NameTransferRequestDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _ConnectionType;
		
		private string _ApplicationType;
		
		private string _SocietyType;
		
		private string _FirstName;
		
		private string _MiddleName;
		
		private string _LastName;
		
		private string _Mobile;
		
		private string _Email;
		
		private string _Comment;
		
		private string _CustomerId;
		
		private string _RegisterdConsumerName;
		
		private string _MeterNumber;
		
		private string _PreviousRegisteredMobile;
		
		private string _PreviousRegisteredEmail;
		
		private string _PreviousRegisteredAddress;
		
		private string _Address;
		
		private System.Nullable<System.DateTime> _CreatedDate;
		
		private System.Nullable<System.DateTime> _ModifiedDate;
		
		private string _RequestNumber;
		
		private string _Status;
		
		private string _CityCode;
		
		private string _OrderId;
		
		private string _OtherDetails;
		
		private string _PayableTotalAmount;
		
		private System.Nullable<bool> _IsRequestClosed;
		
		private string _SAPResponseComment;
		
		private string _ApproveRejectSAPResponse;
		
		private string _CustomerEmailId;
		
		private string _GasSupply;
		
		private string _GasSupplyRequestNumber;
		
		private string _GasSupplySAPResponse;
		
		private string _ClosedApplicationComment;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnConnectionTypeChanging(string value);
    partial void OnConnectionTypeChanged();
    partial void OnApplicationTypeChanging(string value);
    partial void OnApplicationTypeChanged();
    partial void OnSocietyTypeChanging(string value);
    partial void OnSocietyTypeChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnMiddleNameChanging(string value);
    partial void OnMiddleNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnMobileChanging(string value);
    partial void OnMobileChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    partial void OnCustomerIdChanging(string value);
    partial void OnCustomerIdChanged();
    partial void OnRegisterdConsumerNameChanging(string value);
    partial void OnRegisterdConsumerNameChanged();
    partial void OnMeterNumberChanging(string value);
    partial void OnMeterNumberChanged();
    partial void OnPreviousRegisteredMobileChanging(string value);
    partial void OnPreviousRegisteredMobileChanged();
    partial void OnPreviousRegisteredEmailChanging(string value);
    partial void OnPreviousRegisteredEmailChanged();
    partial void OnPreviousRegisteredAddressChanging(string value);
    partial void OnPreviousRegisteredAddressChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnCreatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedDateChanged();
    partial void OnModifiedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifiedDateChanged();
    partial void OnRequestNumberChanging(string value);
    partial void OnRequestNumberChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnCityCodeChanging(string value);
    partial void OnCityCodeChanged();
    partial void OnOrderIdChanging(string value);
    partial void OnOrderIdChanged();
    partial void OnOtherDetailsChanging(string value);
    partial void OnOtherDetailsChanged();
    partial void OnPayableTotalAmountChanging(string value);
    partial void OnPayableTotalAmountChanged();
    partial void OnIsRequestClosedChanging(System.Nullable<bool> value);
    partial void OnIsRequestClosedChanged();
    partial void OnSAPResponseCommentChanging(string value);
    partial void OnSAPResponseCommentChanged();
    partial void OnApproveRejectSAPResponseChanging(string value);
    partial void OnApproveRejectSAPResponseChanged();
    partial void OnCustomerEmailIdChanging(string value);
    partial void OnCustomerEmailIdChanged();
    partial void OnGasSupplyChanging(string value);
    partial void OnGasSupplyChanged();
    partial void OnGasSupplyRequestNumberChanging(string value);
    partial void OnGasSupplyRequestNumberChanged();
    partial void OnGasSupplySAPResponseChanging(string value);
    partial void OnGasSupplySAPResponseChanged();
    partial void OnClosedApplicationCommentChanging(string value);
    partial void OnClosedApplicationCommentChanged();
    #endregion
		
		public NameTransferRequestDetail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConnectionType", DbType="VarChar(150)")]
		public string ConnectionType
		{
			get
			{
				return this._ConnectionType;
			}
			set
			{
				if ((this._ConnectionType != value))
				{
					this.OnConnectionTypeChanging(value);
					this.SendPropertyChanging();
					this._ConnectionType = value;
					this.SendPropertyChanged("ConnectionType");
					this.OnConnectionTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicationType", DbType="VarChar(150)")]
		public string ApplicationType
		{
			get
			{
				return this._ApplicationType;
			}
			set
			{
				if ((this._ApplicationType != value))
				{
					this.OnApplicationTypeChanging(value);
					this.SendPropertyChanging();
					this._ApplicationType = value;
					this.SendPropertyChanged("ApplicationType");
					this.OnApplicationTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SocietyType", DbType="VarChar(150)")]
		public string SocietyType
		{
			get
			{
				return this._SocietyType;
			}
			set
			{
				if ((this._SocietyType != value))
				{
					this.OnSocietyTypeChanging(value);
					this.SendPropertyChanging();
					this._SocietyType = value;
					this.SendPropertyChanged("SocietyType");
					this.OnSocietyTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(150)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleName", DbType="VarChar(150)")]
		public string MiddleName
		{
			get
			{
				return this._MiddleName;
			}
			set
			{
				if ((this._MiddleName != value))
				{
					this.OnMiddleNameChanging(value);
					this.SendPropertyChanging();
					this._MiddleName = value;
					this.SendPropertyChanged("MiddleName");
					this.OnMiddleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(150)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="VarChar(50)")]
		public string Mobile
		{
			get
			{
				return this._Mobile;
			}
			set
			{
				if ((this._Mobile != value))
				{
					this.OnMobileChanging(value);
					this.SendPropertyChanging();
					this._Mobile = value;
					this.SendPropertyChanged("Mobile");
					this.OnMobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(150)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="VarChar(150)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerId", DbType="VarChar(50)")]
		public string CustomerId
		{
			get
			{
				return this._CustomerId;
			}
			set
			{
				if ((this._CustomerId != value))
				{
					this.OnCustomerIdChanging(value);
					this.SendPropertyChanging();
					this._CustomerId = value;
					this.SendPropertyChanged("CustomerId");
					this.OnCustomerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegisterdConsumerName", DbType="VarChar(150)")]
		public string RegisterdConsumerName
		{
			get
			{
				return this._RegisterdConsumerName;
			}
			set
			{
				if ((this._RegisterdConsumerName != value))
				{
					this.OnRegisterdConsumerNameChanging(value);
					this.SendPropertyChanging();
					this._RegisterdConsumerName = value;
					this.SendPropertyChanged("RegisterdConsumerName");
					this.OnRegisterdConsumerNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeterNumber", DbType="VarChar(150)")]
		public string MeterNumber
		{
			get
			{
				return this._MeterNumber;
			}
			set
			{
				if ((this._MeterNumber != value))
				{
					this.OnMeterNumberChanging(value);
					this.SendPropertyChanging();
					this._MeterNumber = value;
					this.SendPropertyChanged("MeterNumber");
					this.OnMeterNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreviousRegisteredMobile", DbType="VarChar(50)")]
		public string PreviousRegisteredMobile
		{
			get
			{
				return this._PreviousRegisteredMobile;
			}
			set
			{
				if ((this._PreviousRegisteredMobile != value))
				{
					this.OnPreviousRegisteredMobileChanging(value);
					this.SendPropertyChanging();
					this._PreviousRegisteredMobile = value;
					this.SendPropertyChanged("PreviousRegisteredMobile");
					this.OnPreviousRegisteredMobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreviousRegisteredEmail", DbType="VarChar(150)")]
		public string PreviousRegisteredEmail
		{
			get
			{
				return this._PreviousRegisteredEmail;
			}
			set
			{
				if ((this._PreviousRegisteredEmail != value))
				{
					this.OnPreviousRegisteredEmailChanging(value);
					this.SendPropertyChanging();
					this._PreviousRegisteredEmail = value;
					this.SendPropertyChanged("PreviousRegisteredEmail");
					this.OnPreviousRegisteredEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreviousRegisteredAddress", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string PreviousRegisteredAddress
		{
			get
			{
				return this._PreviousRegisteredAddress;
			}
			set
			{
				if ((this._PreviousRegisteredAddress != value))
				{
					this.OnPreviousRegisteredAddressChanging(value);
					this.SendPropertyChanging();
					this._PreviousRegisteredAddress = value;
					this.SendPropertyChanged("PreviousRegisteredAddress");
					this.OnPreviousRegisteredAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this.OnCreatedDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedDate = value;
					this.SendPropertyChanged("CreatedDate");
					this.OnCreatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifiedDate
		{
			get
			{
				return this._ModifiedDate;
			}
			set
			{
				if ((this._ModifiedDate != value))
				{
					this.OnModifiedDateChanging(value);
					this.SendPropertyChanging();
					this._ModifiedDate = value;
					this.SendPropertyChanged("ModifiedDate");
					this.OnModifiedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestNumber", DbType="VarChar(150)")]
		public string RequestNumber
		{
			get
			{
				return this._RequestNumber;
			}
			set
			{
				if ((this._RequestNumber != value))
				{
					this.OnRequestNumberChanging(value);
					this.SendPropertyChanging();
					this._RequestNumber = value;
					this.SendPropertyChanged("RequestNumber");
					this.OnRequestNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CityCode", DbType="NVarChar(50)")]
		public string CityCode
		{
			get
			{
				return this._CityCode;
			}
			set
			{
				if ((this._CityCode != value))
				{
					this.OnCityCodeChanging(value);
					this.SendPropertyChanging();
					this._CityCode = value;
					this.SendPropertyChanged("CityCode");
					this.OnCityCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderId", DbType="NVarChar(50)")]
		public string OrderId
		{
			get
			{
				return this._OrderId;
			}
			set
			{
				if ((this._OrderId != value))
				{
					this.OnOrderIdChanging(value);
					this.SendPropertyChanging();
					this._OrderId = value;
					this.SendPropertyChanged("OrderId");
					this.OnOrderIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OtherDetails", DbType="NVarChar(500)")]
		public string OtherDetails
		{
			get
			{
				return this._OtherDetails;
			}
			set
			{
				if ((this._OtherDetails != value))
				{
					this.OnOtherDetailsChanging(value);
					this.SendPropertyChanging();
					this._OtherDetails = value;
					this.SendPropertyChanged("OtherDetails");
					this.OnOtherDetailsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayableTotalAmount", DbType="NVarChar(50)")]
		public string PayableTotalAmount
		{
			get
			{
				return this._PayableTotalAmount;
			}
			set
			{
				if ((this._PayableTotalAmount != value))
				{
					this.OnPayableTotalAmountChanging(value);
					this.SendPropertyChanging();
					this._PayableTotalAmount = value;
					this.SendPropertyChanged("PayableTotalAmount");
					this.OnPayableTotalAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsRequestClosed", DbType="Bit")]
		public System.Nullable<bool> IsRequestClosed
		{
			get
			{
				return this._IsRequestClosed;
			}
			set
			{
				if ((this._IsRequestClosed != value))
				{
					this.OnIsRequestClosedChanging(value);
					this.SendPropertyChanging();
					this._IsRequestClosed = value;
					this.SendPropertyChanged("IsRequestClosed");
					this.OnIsRequestClosedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAPResponseComment", DbType="NVarChar(150)")]
		public string SAPResponseComment
		{
			get
			{
				return this._SAPResponseComment;
			}
			set
			{
				if ((this._SAPResponseComment != value))
				{
					this.OnSAPResponseCommentChanging(value);
					this.SendPropertyChanging();
					this._SAPResponseComment = value;
					this.SendPropertyChanged("SAPResponseComment");
					this.OnSAPResponseCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApproveRejectSAPResponse", DbType="NVarChar(500)")]
		public string ApproveRejectSAPResponse
		{
			get
			{
				return this._ApproveRejectSAPResponse;
			}
			set
			{
				if ((this._ApproveRejectSAPResponse != value))
				{
					this.OnApproveRejectSAPResponseChanging(value);
					this.SendPropertyChanging();
					this._ApproveRejectSAPResponse = value;
					this.SendPropertyChanged("ApproveRejectSAPResponse");
					this.OnApproveRejectSAPResponseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerEmailId", DbType="NVarChar(50)")]
		public string CustomerEmailId
		{
			get
			{
				return this._CustomerEmailId;
			}
			set
			{
				if ((this._CustomerEmailId != value))
				{
					this.OnCustomerEmailIdChanging(value);
					this.SendPropertyChanging();
					this._CustomerEmailId = value;
					this.SendPropertyChanged("CustomerEmailId");
					this.OnCustomerEmailIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GasSupply", DbType="NVarChar(50)")]
		public string GasSupply
		{
			get
			{
				return this._GasSupply;
			}
			set
			{
				if ((this._GasSupply != value))
				{
					this.OnGasSupplyChanging(value);
					this.SendPropertyChanging();
					this._GasSupply = value;
					this.SendPropertyChanged("GasSupply");
					this.OnGasSupplyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GasSupplyRequestNumber", DbType="NVarChar(50)")]
		public string GasSupplyRequestNumber
		{
			get
			{
				return this._GasSupplyRequestNumber;
			}
			set
			{
				if ((this._GasSupplyRequestNumber != value))
				{
					this.OnGasSupplyRequestNumberChanging(value);
					this.SendPropertyChanging();
					this._GasSupplyRequestNumber = value;
					this.SendPropertyChanged("GasSupplyRequestNumber");
					this.OnGasSupplyRequestNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GasSupplySAPResponse", DbType="NVarChar(50)")]
		public string GasSupplySAPResponse
		{
			get
			{
				return this._GasSupplySAPResponse;
			}
			set
			{
				if ((this._GasSupplySAPResponse != value))
				{
					this.OnGasSupplySAPResponseChanging(value);
					this.SendPropertyChanging();
					this._GasSupplySAPResponse = value;
					this.SendPropertyChanged("GasSupplySAPResponse");
					this.OnGasSupplySAPResponseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClosedApplicationComment", DbType="NVarChar(MAX)")]
		public string ClosedApplicationComment
		{
			get
			{
				return this._ClosedApplicationComment;
			}
			set
			{
				if ((this._ClosedApplicationComment != value))
				{
					this.OnClosedApplicationCommentChanging(value);
					this.SendPropertyChanging();
					this._ClosedApplicationComment = value;
					this.SendPropertyChanged("ClosedApplicationComment");
					this.OnClosedApplicationCommentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
