<?xml version="1.0" encoding="utf-8"?><Database Name="AdaniGas" Class="NameTransferRequestDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.NameTransferPaymentHistory" Member="NameTransferPaymentHistories">
    <Type Name="NameTransferPaymentHistory">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NameTransferId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="AccountNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OrderId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Amount" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RequestTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Checksumkey" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CurrencyType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GatewayType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CustomerType" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AdvanceAmmount" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PaymentType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TransactionId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Responsecode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ResponseTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PaymentRef" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ResponseMsg" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PaymentMode" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Created_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Modified_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ISU_UPDATE_FLAG" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="ISU_UPDATE_DATETIME" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ISU_UPDATE_MESSAGE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ISUVDS_Update_Flag" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ISUVDS_Update_DateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ISUVDS_Update_Message" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Comp_Cat" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="SrNo" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Comp_Type" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Quantity_Min" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MessageText" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="IsAfterSalesService" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CustId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CustPass" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CustPartnerId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NameTransferAdminRegistration" Member="NameTransferAdminRegistrations">
    <Type Name="NameTransferAdminRegistration">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MobileNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Role" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AdminStatus" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NameTransferStatus" Member="NameTransferStatus">
    <Type Name="NameTransferStatus">
      <Column Name="Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NameTransferStatus" Member="NameTransferStatus1" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NameTransferStatusText" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NameTransferDocuments" Member="NameTransferDocuments">
    <Type Name="NameTransferDocument">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NameTransferId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ContentType" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DocData" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DocumentType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="DocumentStatus" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AdminComment" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="UploadDocumentSAPResponse" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SAPUploadDocumentStatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SubDocumentType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NameTransferApplicationCheckStatus" Member="NameTransferApplicationCheckStatus">
    <Type Name="NameTransferApplicationCheckStatus">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RequestNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NameTransferChangeNameByAdmin" Member="NameTransferChangeNameByAdmins">
    <Type Name="NameTransferChangeNameByAdmin">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Activity" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CustomerId" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Old_data" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="New_data" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Updated_Datetime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Old_status" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="New_status" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="is_additional_documents_reuired" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_additional_payment_reuired" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Additional_Payment_Value" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NameTransferRequestDetails" Member="NameTransferRequestDetails">
    <Type Name="NameTransferRequestDetail">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ConnectionType" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="ApplicationType" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="SocietyType" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="MiddleName" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="CustomerId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RegisterdConsumerName" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="MeterNumber" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="PreviousRegisteredMobile" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PreviousRegisteredEmail" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="PreviousRegisteredAddress" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Address" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RequestNumber" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CityCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OrderId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OtherDetails" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="PayableTotalAmount" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsRequestClosed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SAPResponseComment" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="ApproveRejectSAPResponse" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CustomerEmailId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GasSupply" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GasSupplyRequestNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GasSupplySAPResponse" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ClosedApplicationComment" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>