<?xml version="1.0" encoding="utf-8"?>
<Database Name="ElectricityTender" Class="PaymentHistoryDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
	<Table Name="dbo.Payment_Penalty" Member="Payment_Penalties">
		<Type Name="Payment_Penalty">
			<Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
			<Column Name="CONSUMER_NO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="BILL_MONTH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="PENALTY" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="RND_PAYABLE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
		</Type>
	</Table>
	<Table Name="dbo.user_otp" Member="user_otps">
		<Type Name="user_otp">
			<Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
			<Column Name="MobileNumber" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
			<Column Name="otp" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
			<Column Name="status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
		</Type>
	</Table>
	<Table Name="dbo.ENachRegistration" Member="ENachRegistrations">
		<Type Name="ENachRegistration">
			<Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
			<Column Name="AccountNumber" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
			<Column Name="PPIFlag" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
			<Column Name="Name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
			<Column Name="Email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
			<Column Name="Mobile" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
			<Column Name="Created_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
		</Type>
	</Table>
	<Table Name="dbo.CONAreaCityPinMaster" Member="CONAreaCityPinMasters">
		<Type Name="CONAreaCityPinMaster">
			<Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
			<Column Name="City" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="Area" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="PinCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="WorkCenter" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="Remarks" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
			<Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
		</Type>
	</Table>
	<Table Name="dbo.CONDocumentSubTypeMaster" Member="CONDocumentSubTypeMasters">
		<Type Name="CONDocumentSubTypeMaster">
			<Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
			<Column Name="DocumentSubTypeCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
			<Column Name="DocumentSubTypeName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
			<Column Name="DocumentSubTypeDescription" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
			<Column Name="DocumentSubTypeSequence" Type="System.Int32" DbType="Int" CanBeNull="true" />
			<Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
		</Type>
	</Table>
	<Table Name="dbo.CONDocumentMaster" Member="CONDocumentMasters">
		<Type Name="CONDocumentMaster">
			<Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
			<Column Name="DocumentSerialNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
			<Column Name="DocumentType" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="DocumentTypeCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="ApplicationTypeCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="PremiseTypeCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="TitleCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="DocumentDescription" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
			<Column Name="ZALTYP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="FLAG_MANDATORY" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
			<Column Name="FLAG_DOCNO" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
			<Column Name="AKLASSE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
		</Type>
	</Table>
	<Table Name="dbo.CONPremiseTypeMaster" Member="CONPremiseTypeMasters">
		<Type Name="CONPremiseTypeMaster">
			<Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
			<Column Name="PremiseTypeName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="PremiseTypeCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
			<Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
			<Column Name="DisplayOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
		</Type>
	</Table>
	<Table Name="dbo.OTPValidationAEML" Member="OTPValidationAEMLs">
		<Type Name="OTPValidationAEML">
			<Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
			<Column Name="AccountNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="MeterNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="MobileNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="OTP" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="PageName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="ReferenceNumner" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
		</Type>
	</Table>
	<Table Name="dbo.CONApplicationDocumentDetails" Member="CONApplicationDocumentDetails">
		<Type Name="CONApplicationDocumentDetail">
			<Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
			<Column Name="RegistrationSerialNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="DocumentType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="DocumentTypeCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="DocumentChecklistSerialNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="DocumentName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
			<Column Name="DocumentDescription" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
			<Column Name="DocumentNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="IsSentToSAP" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
			<Column Name="SAPSentDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="DocumentData" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
			<Column Name="DocumentDataContenttype" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
			<Column Name="SAPReturnMsg" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
		</Type>
	</Table>
	<Table Name="dbo.UserProfile" Member="UserProfiles">
		<Type Name="UserProfile">
			<Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
			<Column Name="UserName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
			<Column Name="Email" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
			<Column Name="Mobile" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
			<Column Name="AccountNumber" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
			<Column Name="MeterNumber" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
			<Column Name="IsPrimary" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
			<Column Name="status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
			<Column Name="Created_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="CreatedBy" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
			<Column Name="Modified_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
			<Column Name="LastPasswordChangedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="LastLoginDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
		</Type>
	</Table>
	<Table Name="dbo.PaymentHistory" Member="PaymentHistories">
		<Type Name="PaymentHistory">
			<Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
			<Column Name="AccountNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="UserId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="OrderId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="Amount" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="RequestTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="Checksumkey" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="CurrencyType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="GatewayType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="msg" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
			<Column Name="AdvanceAmmount" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="PaymentType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="UserType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="Mobile" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="TransactionId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="Responsecode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="Remark" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
			<Column Name="ResponseTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="PaymentRef" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="ResponseMsg" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
			<Column Name="PaymentMode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="Created_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="Modified_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="ISU_UPDATE_FLAG" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
			<Column Name="ISU_UPDATE_DATETIME" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="ISU_UPDATE_MESSAGE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
			<Column Name="EMIOption" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
			<Column Name="EMIAmount" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="EMIOutstanding" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
		</Type>
	</Table>
	<Table Name="dbo.SolarApplicationDocumentMaster" Member="SolarApplicationDocumentMasters">
		<Type Name="SolarApplicationDocumentMaster">
			<Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
			<Column Name="DocumentSerialNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
			<Column Name="IsSubsidizedCategory" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
			<Column Name="DocumentName" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
			<Column Name="DocumentDescription" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
			<Column Name="DocumentTypeAllowed" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
			<Column Name="DocumentSizeAllowed" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
		</Type>
	</Table>
	<Table Name="dbo.SolarApplicationVendorList" Member="SolarApplicationVendorLists">
		<Type Name="SolarApplicationVendorList">
			<Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
			<Column Name="NameOfVendorAgency" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
			<Column Name="Address" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
			<Column Name="City" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
			<Column Name="District" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
			<Column Name="State" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
			<Column Name="ContactName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
			<Column Name="EmailAddress" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="MobileNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="PublicMobileNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="STDLandlineNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="STDFaxNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="WebsiteAddress" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="PANNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="RatingAgency" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="RatingReceived" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="ApprovedRate" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
		</Type>
	</Table>
	<Table Name="dbo.SolarApplicationVoltageMaster" Member="SolarApplicationVoltageMasters">
		<Type Name="SolarApplicationVoltageMaster">
			<Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
			<Column Name="VoltageLevel" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="VoltageDescription" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
		</Type>
	</Table>
	<Table Name="dbo.SolarApplicationDocumentDetails" Member="SolarApplicationDocumentDetails">
		<Type Name="SolarApplicationDocumentDetail">
			<Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
			<Column Name="SolarApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
			<Column Name="AccountNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="DocumentId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
			<Column Name="DocumentSerialNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
			<Column Name="DocumentName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="IsSentToSAP" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
			<Column Name="SAPSentDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="DocumentData" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
			<Column Name="DocumentDataContenttype" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="SAPReturnMsg" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
			<Column Name="ApplicationNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
		</Type>
	</Table>
	<Table Name="dbo.SolarApplicationDetails" Member="SolarApplicationDetails">
		<Type Name="SolarApplicationDetail">
			<Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
			<Column Name="AccountNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="MeterNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="ConsumerName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
			<Column Name="Address" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
			<Column Name="RateCategory" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="EmailAddress" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="MobileNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="VoltageCategorySelected" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="ProposedACcapacity" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="LECNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="IsRooftopSolarInstalled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
			<Column Name="IsOwnershipLeased" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
			<Column Name="IsObligatedEntity" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
			<Column Name="IsNetMeterOpted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
			<Column Name="InstallationCost" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="VenderSelected" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
			<Column Name="VenderNameSeleted" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
			<Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
			<Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="ApplicationNumber" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
			<Column Name="OrderNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="AmountTobePaid" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="ApplicationStatus" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="IsPaymentDone" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
			<Column Name="PaymentDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="TransactionId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="IsRooftopPlusGroundCapacity" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
			<Column Name="ApplicationCategory" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="AadharNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="IsSubsidizedCategory" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
			<Column Name="TempRegistrationNumber" Type="System.String" DbType="NVarChar(52)" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
			<Column Name="Workcenter" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="UserId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="OrderId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
		</Type>
	</Table>
	<Table Name="dbo.CONApplicationDetails" Member="CONApplicationDetails">
		<Type Name="CONApplicationDetail">
			<Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
			<Column Name="AccountNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="MeterNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="ApplicationTypeName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="ApplicationTypeId" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
			<Column Name="PremiseTypeName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="PremiseTypeCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
			<Column Name="ApplicantType" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="ApplicantTypeCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
			<Column Name="IsContinueExitingSDvalueOpt" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
			<Column Name="ExistingSecurityDepositAmount" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="SecurityDepositAmount" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="TitleName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="TitleValue" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="OrgName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
			<Column Name="FirstName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="MiddleName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="LastName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="MobileNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="LandlineNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="EmailAddress" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="WorkCenterName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
			<Column Name="IsDiffrentBillingAddressValueOpt" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
			<Column Name="PaperlessBillingFlag" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
			<Column Name="EbillPhysicalFlag" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
			<Column Name="HouseNumber" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
			<Column Name="BuildingName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
			<Column Name="StreetName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
			<Column Name="Landmark" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
			<Column Name="Area" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
			<Column Name="City" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
			<Column Name="Pincode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="Suburb" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
			<Column Name="ConsumerContractVertrag" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="ConsumerRemarks" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
			<Column Name="BillingLanguage" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="NumberOfVersion" Type="System.Int32" DbType="Int" CanBeNull="true" />
			<Column Name="RegistrationSerialNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="TempRegistrationSerialNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="ApplicationStatusName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="ApplicationStatusCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="ZALTYP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="ZAPPLBY" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="NewAccountNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="ApplicationStatusUpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="ApplicationstatusUpdatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="ApplicationStatusUpdateEmpRemarks" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
			<Column Name="ApplicationRejectionReason" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
			<Column Name="AKLASSE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="Housenumber_New" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
			<Column Name="Streetname_New" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
			<Column Name="Landmark_New" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
			<Column Name="Buildingname_New" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
			<Column Name="Suburb_New" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
			<Column Name="Pincode_New" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="City_New" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
			<Column Name="Area_New" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
			<Column Name="IsRentedProperty" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
			<Column Name="Rented_Ownername" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="Rented_Owner_Mobile" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="Rented_Owner_Landline" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="Rented_Owner_Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="BillingHouseNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="BillingBuildingName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
			<Column Name="BillingStreet" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
			<Column Name="BillingLandmark" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
			<Column Name="BillingSuburb" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="BillingCity" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="BillingPincode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="IsAddressChangeRequired" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
			<Column Name="SAPReturnMsg" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
			<Column Name="LECRegistrationNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="LECMobileNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
		</Type>
	</Table>
	<Table Name="dbo.CONLECRegistrationDetails" Member="CONLECRegistrationDetails">
		<Type Name="CONLECRegistrationDetail">
			<Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
			<Column Name="LECRegistrationNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="LECName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="LECMobileNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="LECEmailId" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="LECUserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="LECPassword" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="LECIsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
			<Column Name="LECCreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
			<Column Name="LECInActivateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="LECLastPasswordChangeDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Association Name="CONLECRegistrationDetail_CONLECUpdateLog" Member="CONLECUpdateLogs" ThisKey="ID" OtherKey="LECID" Type="CONLECUpdateLog" />
		</Type>
	</Table>
	<Table Name="dbo.CONLECUpdateLog" Member="CONLECUpdateLogs">
		<Type Name="CONLECUpdateLog">
			<Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
			<Column Name="LECID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
			<Column Name="LECRegistrationNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="LECMobileNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="LECEmailID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="IsProfileUpdated" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
			<Column Name="OldMobileNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="OldEmailId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="IsPasswordUpdated" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
			<Column Name="OldPassword" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="IsDeActivated" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
			<Column Name="DateModified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="Comments" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
			<Association Name="CONLECRegistrationDetail_CONLECUpdateLog" Member="CONLECRegistrationDetail" ThisKey="LECID" OtherKey="ID" Type="CONLECRegistrationDetail" IsForeignKey="true" />
		</Type>
	</Table>
	<Table Name="dbo.PANUpdateLog" Member="PANUpdateLogs">
		<Type Name="PANUpdateLog">
			<Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
			<Column Name="AccountNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="MobileNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="EmailId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="ConsumerName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="PANNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="GSTNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="IsPANUpdated" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
			<Column Name="IsGSTUpdated" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
			<Column Name="UpdatedPANNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="UpdatedGSTNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="Created_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="FileName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
			<Column Name="ContentType" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
			<Column Name="DocData" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
		</Type>
	</Table>
	<Table Name="dbo.ComplaintPortalLogginLog" Member="ComplaintPortalLogginLogs">
		<Type Name="ComplaintPortalLogginLog">
			<Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
			<Column Name="IsRegistered" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
			<Column Name="LoginName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="AccountNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="MobileNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="LoggedInDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
		</Type>
	</Table>
	<Table Name="dbo.ComplaintPortalCGRFZoneDivisionMaster" Member="ComplaintPortalCGRFZoneDivisionMasters">
		<Type Name="ComplaintPortalCGRFZoneDivisionMaster">
			<Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
			<Column Name="ZoneName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="DivisionName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
		</Type>
	</Table>
	<Table Name="dbo.ComplaintPortalCGRFDocumentTypeMaster" Member="ComplaintPortalCGRFDocumentTypeMasters">
		<Type Name="ComplaintPortalCGRFDocumentTypeMaster">
			<Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
			<Column Name="DocumentType" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="Decription" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
		</Type>
	</Table>
	<Table Name="dbo.ComplaintPortalCGRFComplaintHistory" Member="ComplaintPortalCGRFComplaintHistories">
		<Type Name="ComplaintPortalCGRFComplaintHistory">
			<Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
			<Column Name="ComplaintId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
			<Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
			<Column Name="AdminRemarks" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
			<Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
			<Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Association Name="ComplaintPortalRegisteredComplaint_ComplaintPortalCGRFComplaintHistory" Member="ComplaintPortalRegisteredComplaint" ThisKey="ComplaintId" OtherKey="Id" Type="ComplaintPortalRegisteredComplaint" IsForeignKey="true" />
		</Type>
	</Table>
	<Table Name="dbo.ComplaintPortalCGRFComplaintStatusMaster" Member="ComplaintPortalCGRFComplaintStatusMasters">
		<Type Name="ComplaintPortalCGRFComplaintStatusMaster">
			<Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
			<Column Name="ComplaintStatusCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="ComplaintStatusName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="ComplaintStatusDescription" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
		</Type>
	</Table>
	<Table Name="dbo.ComplaintPortalCGRFAdminLogin" Member="ComplaintPortalCGRFAdminLogins">
		<Type Name="ComplaintPortalCGRFAdminLogin">
			<Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
			<Column Name="Username" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="Role" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="EmailId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="MobileNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
		</Type>
	</Table>
	<Table Name="dbo.ComplaintPortalCGRFForwardDetails" Member="ComplaintPortalCGRFForwardDetails">
		<Type Name="ComplaintPortalCGRFForwardDetail">
			<Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
			<Column Name="ComplainId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
			<Column Name="EmailId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
		</Type>
	</Table>
	<Table Name="dbo.ComplaintPortalCGRFForwardDetails" Member="ComplaintPortalCGRFForwardDetail1s">
		<Type Name="ComplaintPortalCGRFForwardDetail1">
			<Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
			<Column Name="ComplainId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
			<Column Name="EmailId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
		</Type>
	</Table>
	<Table Name="dbo.CGRFForwardMail" Member="CGRFForwardMails">
		<Type Name="CGRFForwardMail">
			<Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
			<Column Name="ComplainId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
			<Column Name="EmailId" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
			<Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
		</Type>
	</Table>
	<Table Name="dbo.ComplaintPortalRegisteredComplaintsOrderReviewRequest" Member="ComplaintPortalRegisteredComplaintsOrderReviewRequests">
		<Type Name="ComplaintPortalRegisteredComplaintsOrderReviewRequest">
			<Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
			<Column Name="ComplaintId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
			<Column Name="AccountNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="IsAppliedWithin30Days" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
			<Column Name="IsAppealPreferred" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
			<Column Name="IsErrorApparent" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
			<Column Name="IsImportantMatterDiscovery" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
			<Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="StatusCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="StatusName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Association Name="ComplaintPortalRegisteredComplaint_ComplaintPortalRegisteredComplaintsOrderReviewRequest" Member="ComplaintPortalRegisteredComplaint" ThisKey="ComplaintId" OtherKey="Id" Type="ComplaintPortalRegisteredComplaint" IsForeignKey="true" />
		</Type>
	</Table>
	<Table Name="dbo.ComplaintPortalCGRFComplaintHearingSchedule" Member="ComplaintPortalCGRFComplaintHearingSchedules">
		<Type Name="ComplaintPortalCGRFComplaintHearingSchedule">
			<Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
			<Column Name="ComplaintId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
			<Column Name="DateOfHearing" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
			<Column Name="ScheduledDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="MOMFileName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="MOMDocumentData" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
			<Column Name="MOMDocumentContentType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="MOMUploadDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="IsOrderReviewRequest" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
			<Association Name="ComplaintPortalRegisteredComplaint_ComplaintPortalCGRFComplaintHearingSchedule" Member="ComplaintPortalRegisteredComplaint" ThisKey="ComplaintId" OtherKey="Id" Type="ComplaintPortalRegisteredComplaint" IsForeignKey="true" />
		</Type>
	</Table>
	<Table Name="dbo.ComplaintPortalCGRFComplaintDocuments" Member="ComplaintPortalCGRFComplaintDocuments">
		<Type Name="ComplaintPortalCGRFComplaintDocument">
			<Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
			<Column Name="ComplaintNumber" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
			<Column Name="DocumentType" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="DocumenttypeCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
			<Column Name="DocumentName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
			<Column Name="DocumentData" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
			<Column Name="DocumentContentType" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
			<Column Name="DocumentDescription" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
			<Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
			<Column Name="IsReviewRequestRaised" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
			<Association Name="ComplaintPortalRegisteredComplaint_ComplaintPortalCGRFComplaintDocument" Member="ComplaintPortalRegisteredComplaint" ThisKey="ComplaintNumber" OtherKey="Id" Type="ComplaintPortalRegisteredComplaint" IsForeignKey="true" />
		</Type>
	</Table>
	<Table Name="dbo.ComplaintPortalComplaintSubCategoryMaster" Member="ComplaintPortalComplaintSubCategoryMasters">
		<Type Name="ComplaintPortalComplaintSubCategoryMaster">
			<Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
			<Column Name="CategoryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
			<Column Name="SubCategory" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="SubCategoryId" Type="System.Int32" DbType="Int" CanBeNull="true" />
			<Association Name="ComplaintPortalComplaintCategoryMaster_ComplaintPortalComplaintSubCategoryMaster" Member="ComplaintPortalComplaintCategoryMaster" ThisKey="CategoryId" OtherKey="Id" Type="ComplaintPortalComplaintCategoryMaster" IsForeignKey="true" />
		</Type>
	</Table>
	<Table Name="dbo.ComplaintPortalComplaintSubTypeMaster" Member="ComplaintPortalComplaintSubTypeMasters">
		<Type Name="ComplaintPortalComplaintSubTypeMaster">
			<Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
			<Column Name="SubTypeCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="SubTypeDescription" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="SubSubTypeCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="SubSubTypeDescription" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
		</Type>
	</Table>
	<Table Name="dbo.ComplaintPortalCGRFApprovedComplaints" Member="ComplaintPortalCGRFApprovedComplaints">
		<Type Name="ComplaintPortalCGRFApprovedComplaint">
			<Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
			<Column Name="ComplaintId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
			<Column Name="ApprovedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
			<Column Name="CaseNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
		</Type>
	</Table>
	<Table Name="dbo.SecurityDepositInstallmentOptIn" Member="SecurityDepositInstallmentOptIns">
		<Type Name="SecurityDepositInstallmentOptIn">
			<Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
			<Column Name="AccountNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="MobileNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="ConsumerName" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
			<Column Name="NumberOfInstallments" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
			<Column Name="SDAmount" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
			<Column Name="Source" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="CANumberEncrypted" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
			<Column Name="IsPostToSAP" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
			<Column Name="SAPPostMessage" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
		</Type>
	</Table>
	<Table Name="dbo.GreenPowerOptIn" Member="GreenPowerOptIns">
		<Type Name="GreenPowerOptIn">
			<Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
			<Column Name="AccountNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="MobileNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="EmailId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
			<Column Name="TwitterId" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
			<Column Name="FacebookId" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
			<Column Name="OptInFlagCurrentOrNextBilling" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
			<Column Name="IPledge" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
			<Column Name="IsPicCaptured" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
			<Column Name="ImageDate" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
			<Column Name="ImageName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
			<Column Name="ImageContentType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="ImageLink" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
			<Column Name="OptInBillingFrom" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="PercentageOptIn" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
		</Type>
	</Table>
	<Table Name="dbo.NEWCON_MST_CONNECTION_TYPE" Member="NEWCON_MST_CONNECTION_TYPEs">
		<Type Name="NEWCON_MST_CONNECTION_TYPE">
			<Column Name="CONNECTION_TYPE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
			<Column Name="CONNECTION_TYPE_DESC" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
		</Type>
	</Table>
	<Table Name="dbo.NEWCON_MST_APPLICANT_TITLE" Member="NEWCON_MST_APPLICANT_TITLEs">
		<Type Name="NEWCON_MST_APPLICANT_TITLE">
			<Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
			<Column Name="APPLICANT_TITLE" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
			<Column Name="APPLICANT_TITLE_DESC" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
		</Type>
	</Table>
	<Table Name="dbo.NEWCON_MST_BILL_LANGUAGE" Member="NEWCON_MST_BILL_LANGUAGEs">
		<Type Name="NEWCON_MST_BILL_LANGUAGE">
			<Column Name="ID" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
			<Column Name="DESCRIPTION" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
		</Type>
	</Table>
	<Table Name="dbo.NEWCON_MST_METERLOAD_TYPE" Member="NEWCON_MST_METERLOAD_TYPEs">
		<Type Name="NEWCON_MST_METERLOAD_TYPE">
			<Column Name="ZLTYP" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
			<Column Name="APPLIED_TARRIF" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
			<Column Name="PURPOSE_CONNECTION" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
			<Column Name="ZUNIT_KW" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
			<Column Name="ZUNIT_HP" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
			<Column Name="KWMANDATORY" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
			<Column Name="HPMANDATORY" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
			<Column Name="DESCRIPTION" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
		</Type>
	</Table>
	<Table Name="dbo.CGRFComplaintsCounter" Member="CGRFComplaintsCounters">
		<Type Name="CGRFComplaintsCounter">
			<Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
			<Column Name="CGRFComplaintsCountValue" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
			<Column Name="FinancialYear" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
		</Type>
	</Table>
	<Table Name="dbo.CityPayment" Member="CityPayments">
		<Type Name="CityPayment">
			<Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
			<Column Name="TxnRefNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="OrderNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="NPCITxnId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="TimeStamp" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="TranAuthDate" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="StatusCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="StatusDesc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="RespCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="SettlementAmount" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="SettlementCurrency" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="Created_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="Response_Msg" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
		</Type>
	</Table>
	<Table Name="dbo.NEWCON_MST_VOLTAGE_LEVEL" Member="NEWCON_MST_VOLTAGE_LEVELs">
		<Type Name="NEWCON_MST_VOLTAGE_LEVEL">
			<Column Name="VOLTAGE_LEVEL" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
			<Column Name="DESCRIPTION" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
			<Column Name="CONNECTION_TYPE" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
			<Column Name="OA" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
			<Column Name="MeterType" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
		</Type>
	</Table>
	<Table Name="dbo.NEWCON_MST_PREMISE_TYPEs" Member="NEWCON_MST_PREMISE_TYPEs">
		<Type Name="NEWCON_MST_PREMISE_TYPE">
			<Column Name="PREMISE_TYPE" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
			<Column Name="TEXT" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
			<Column Name="ENABLE_SUB_APP1" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
			<Column Name="ENABLE_FLAG_SUB_APP2" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
			<Column Name="ENABLE_FLAG_SUB_APP3" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
			<Column Name="ENABLE_FLAG_SUB_APP4" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
			<Column Name="ENABLE_FLAG_SUB_APP5" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
			<Column Name="ENABLE_FLAG_SUB_APP6" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
			<Column Name="CHN_SEQ" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
		</Type>
	</Table>
	<Table Name="dbo.NEW_CON_APPLICATION_DOCUMENT_DETAILS" Member="NEW_CON_APPLICATION_DOCUMENT_DETAILs">
		<Type Name="NEW_CON_APPLICATION_DOCUMENT_DETAIL">
			<Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
			<Column Name="RegistrationSerialNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="DocumentType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="DocumentTypeCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="DocumentChecklistSerialNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="DocumentName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
			<Column Name="DocumentDescription" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
			<Column Name="DocumentNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="IsSentToSAP" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
			<Column Name="SAPSentDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="DocumentData" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
			<Column Name="DocumentDataContenttype" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
			<Column Name="SAPReturnMsg" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
			<Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
		</Type>
	</Table>
	<Table Name="dbo.NEWCON_DOCUMENTMASTER" Member="NEWCON_DOCUMENTMASTERs">
		<Type Name="NEWCON_DOCUMENTMASTER">
			<Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
			<Column Name="SRNO" Type="System.Int32" DbType="Int" CanBeNull="true" />
			<Column Name="DOCTY" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
			<Column Name="DOCID" Type="System.Int32" DbType="Int" CanBeNull="true" />
			<Column Name="APPLICATION_TYPE_CODE" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
			<Column Name="DESCRIPTION" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
			<Column Name="ZALSTYP" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
			<Column Name="DELETEFLAG" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
			<Column Name="FLAG_MANDATORY" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
			<Column Name="FLAG_DOCNO" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
			<Column Name="TITLE" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
			<Column Name="FLAG_INDUSTRY" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
			<Column Name="ALERT_MESSAGE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
		</Type>
	</Table>
	<Table Name="dbo.NEW_CON_APPLICATIONSUBTYPE" Member="NEW_CON_APPLICATIONSUBTYPEs">
		<Type Name="NEW_CON_APPLICATIONSUBTYPE">
			<Column Name="ApplicationSubtype" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="ApplicationSubtypeDesc" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
			<Column Name="ApplicationType" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
		</Type>
	</Table>
	<Table Name="dbo.ComplaintPortalFeedback" Member="ComplaintPortalFeedbacks">
		<Type Name="ComplaintPortalFeedback">
			<Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
			<Column Name="ComplaintRegistrationNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="IsFeedbackGiven" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
			<Column Name="FeedbackNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="OverallExperienceRating" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="ConcernAddressedRating" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="Remarks" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
			<Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
			<Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="Message" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
		</Type>
	</Table>
	<Table Name="dbo.NEWCON_MST_PURPOSE_CONNECTION" Member="NEWCON_MST_PURPOSE_CONNECTIONs">
		<Type Name="NEWCON_MST_PURPOSE_CONNECTION">
			<Column Name="PURPOSE_OF_CONNECTION" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
			<Column Name="CONNECTION_DESCRIPTION" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
			<Column Name="APPLIED_TARIFF" Type="System.String" DbType="NVarChar(498)" CanBeNull="true" />
			<Column Name="TARIFF_DESCRIPTION" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
			<Column Name="CONNECTION_TYPE" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
			<Column Name="ENABLE_FLAG_SUB_APP1" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
			<Column Name="ENABLE_FLAG_SUB_APP2" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
			<Column Name="ENABLE_FLAG_SUB_APP3" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
			<Column Name="ENABLE_FLAG_SUB_APP4" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
			<Column Name="ENABLE_FLAG_SUB_APP5" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
			<Column Name="ENABLE_FLAG_SUB_APP6" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
			<Column Name="APPLICANT_TYPE" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
			<Column Name="APPLICANT_SUB_TYPE" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
			<Column Name="IsAbove20" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
			<Column Name="PremiseType" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
		</Type>
	</Table>
	<Table Name="dbo.NEWCON_LOAD_DETAIL" Member="NEWCON_LOAD_DETAILs">
		<Type Name="NEWCON_LOAD_DETAIL">
			<Column Name="id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
			<Column Name="AccountNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="ConnectedLoadHP" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
			<Column Name="ConnectedLoadKW" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
			<Column Name="TotalLoad" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
			<Column Name="ConnectionType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="ConnectionCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
			<Column Name="VoltageLevel" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
			<Column Name="PurposeOfSupply" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
			<Column Name="MeterLoad" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
			<Column Name="MeterType" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
			<Column Name="PremiseType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="ContractDemand" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="LDPOrderNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
		</Type>
	</Table>
	<Table Name="dbo.NEW_CON_NormativeCharge" Member="NEW_CON_NormativeCharges">
		<Type Name="NEW_CON_NormativeCharge">
			<Column Name="PMActivity" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
			<Column Name="LoadUnit" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
			<Column Name="Phase" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
			<Column Name="LoadLow" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
			<Column Name="LoadHigh" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
			<Column Name="ServiceLineRate" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
			<Column Name="ApplicationCharge" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
		</Type>
	</Table>
	<Table Name="dbo.NEW_CON_APPLICATIONTYPE" Member="NEW_CON_APPLICATIONTYPEs">
		<Type Name="NEW_CON_APPLICATIONTYPE">
			<Column Name="ApplicationId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="ApplicationType" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
		</Type>
	</Table>
	<Table Name="dbo.NEWCON_MST_APPLICANT_TYPE" Member="NEWCON_MST_APPLICANT_TYPEs">
		<Type Name="NEWCON_MST_APPLICANT_TYPE">
			<Column Name="APPLICANT_TYPE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
			<Column Name="APPLICANT_TYPE_DESC" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
			<Column Name="APPLICANT_TYPE_GovernmentList" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
		</Type>
	</Table>
	<Table Name="dbo.NEW_CON_CITY_PINCODE_MST" Member="NEW_CON_CITY_PINCODE_MSTs">
		<Type Name="NEW_CON_CITY_PINCODE_MST">
			<Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
			<Column Name="City" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="Area" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="Pincode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="Division" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
			<Column Name="Unit" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
			<Column Name="WorkStation" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
			<Column Name="DummyLDP" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
			<Column Name="AreaSentToSAP" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
			<Column Name="CreatedDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
			<Column Name="CreatedBy" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
		</Type>
	</Table>
	<Table Name="dbo.NEWCON_OTHER_DETAIL" Member="NEWCON_OTHER_DETAILs">
		<Type Name="NEWCON_OTHER_DETAIL">
			<Column Name="id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
			<Column Name="AccountNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="IsMeterConnectionCabinExist" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
			<Column Name="NearestConsumerAccountNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="NearestConsumerMeterNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="ExistingConnection" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
			<Column Name="ConsumerNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="Utility" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
			<Column Name="WiringCompleted" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
			<Column Name="LECNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="NameOnLEC" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
			<Column Name="LECMobileNumber" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
			<Column Name="LECEmail" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
			<Column Name="LECLandline" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
			<Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="TR_NO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="TR_DOCUMENT" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
			<Column Name="IS_METER_SUPPLIER" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
			<Column Name="Is_DDF" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
			<Column Name="DDFRs" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
		</Type>
	</Table>
	<Table Name="dbo.UserLoginSessions" Member="UserLoginSessions">
		<Type Name="UserLoginSession">
			<Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
			<Column Name="UserName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
			<Column Name="SessionId" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
			<Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
		</Type>
	</Table>
	<Table Name="dbo.ComplaintPortalComplaintCategoryMaster" Member="ComplaintPortalComplaintCategoryMasters">
		<Type Name="ComplaintPortalComplaintCategoryMaster">
			<Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
			<Column Name="CategoryName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="IsVisibleToRegisteredOnly" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
			<Association Name="ComplaintPortalComplaintCategoryMaster_ComplaintPortalComplaintSubCategoryMaster" Member="ComplaintPortalComplaintSubCategoryMasters" ThisKey="Id" OtherKey="CategoryId" Type="ComplaintPortalComplaintSubCategoryMaster" />
			<Association Name="ComplaintPortalComplaintCategoryMaster_ComplaintPortalRegisteredComplaint" Member="ComplaintPortalRegisteredComplaints" ThisKey="Id" OtherKey="ComplaintCategoryId" Type="ComplaintPortalRegisteredComplaint" />
		</Type>
	</Table>
	<Table Name="dbo.ComplaintPortalRegisteredComplaints" Member="ComplaintPortalRegisteredComplaints">
		<Type Name="ComplaintPortalRegisteredComplaint">
			<Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
			<Column Name="AccountNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="MobileNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="IsRegisteredUser" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
			<Column Name="UserName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
			<Column Name="ConsumerName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
			<Column Name="Address" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
			<Column Name="City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="Pincode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="Zone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="Mobile" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="ConsumerCategory" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="ComplaintCategory" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="ComplaintSubCategory" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="ComplaintCategoryId" Type="System.Int32" DbType="Int" CanBeNull="true" />
			<Column Name="ComplaintSubCategoryId" Type="System.Int32" DbType="Int" CanBeNull="true" />
			<Column Name="ComplaintDescription" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
			<Column Name="DocumentData" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
			<Column Name="DocumentContentType" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
			<Column Name="DocumentFileName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="ComplaintStatusName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="ComplaintStatusCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="ComplaintLevel" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
			<Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="NumberOfVersion" Type="System.Int32" DbType="Int" CanBeNull="true" />
			<Column Name="ComplaintIdSAP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="ComplaintCategoryOtherText" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
			<Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="AdminRemarks" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
			<Column Name="TentativeHearingDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="ComplaintRegistrationNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="ComplaintNumberFromPerviousLevel" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="ComplaintRemarksPerviousLevel" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
			<Column Name="CGRFCaseNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="ComplaintFromPerviousLevelAppliedDate" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
			<Column Name="ComplaintFromPerviousLevelDivision" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="ReasonToApplyComplaint" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
			<Column Name="NodalReplyTATDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="SecretaryTATDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="ClosedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="IsReviewRequestRaised" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
			<Column Name="TransactionReceiptSentToSAP" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
			<Column Name="TransactionReceiptSentToSAPResponse" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
			<Column Name="BankAccountStatementSentToSAP" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
			<Column Name="BankAccountStatementSentToSAPResponse" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
			<Association Name="ComplaintPortalRegisteredComplaint_ComplaintPortalCGRFComplaintHistory" Member="ComplaintPortalCGRFComplaintHistories" ThisKey="Id" OtherKey="ComplaintId" Type="ComplaintPortalCGRFComplaintHistory" />
			<Association Name="ComplaintPortalRegisteredComplaint_ComplaintPortalRegisteredComplaintsOrderReviewRequest" Member="ComplaintPortalRegisteredComplaintsOrderReviewRequests" ThisKey="Id" OtherKey="ComplaintId" Type="ComplaintPortalRegisteredComplaintsOrderReviewRequest" />
			<Association Name="ComplaintPortalRegisteredComplaint_ComplaintPortalCGRFComplaintHearingSchedule" Member="ComplaintPortalCGRFComplaintHearingSchedules" ThisKey="Id" OtherKey="ComplaintId" Type="ComplaintPortalCGRFComplaintHearingSchedule" />
			<Association Name="ComplaintPortalRegisteredComplaint_ComplaintPortalCGRFComplaintDocument" Member="ComplaintPortalCGRFComplaintDocuments" ThisKey="Id" OtherKey="ComplaintNumber" Type="ComplaintPortalCGRFComplaintDocument" />
			<Association Name="ComplaintPortalComplaintCategoryMaster_ComplaintPortalRegisteredComplaint" Member="ComplaintPortalComplaintCategoryMaster" ThisKey="ComplaintCategoryId" OtherKey="Id" Type="ComplaintPortalComplaintCategoryMaster" IsForeignKey="true" />
		</Type>
	</Table>
	<Table Name="dbo.NEW_CON_APPLICATION_FORM" Member="NEW_CON_APPLICATION_FORMs">
		<Type Name="NEW_CON_APPLICATION_FORM">
			<Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
			<Column Name="ApplicationNumber" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
			<Column Name="AccountNumber" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
			<Column Name="ApplicationType" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
			<Column Name="PeriodOfSupplyFrom" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="PeriodOfSupplyTo" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="ApplicationTitle" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
			<Column Name="FirstName" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
			<Column Name="MiddleName" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
			<Column Name="LastName" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
			<Column Name="OrganizationName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
			<Column Name="DateOfBirth" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="DateOfBirthJoint1" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="AddressOfSupply" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
			<Column Name="Pincode" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
			<Column Name="Surburb" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
			<Column Name="BillingAddressDifferentFromSupply" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
			<Column Name="BillingAddress" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
			<Column Name="BillingSuburb" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
			<Column Name="BillingPincode" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
			<Column Name="AddressIncaseOfRental" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
			<Column Name="AddressOfRental" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
			<Column Name="NameOfRental" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
			<Column Name="RentalContactNo" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
			<Column Name="RentalSuburb" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
			<Column Name="RentalPincode" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
			<Column Name="RentalOwnerEmail" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
			<Column Name="MobileNumber" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
			<Column Name="Email" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
			<Column Name="LandlineNumber" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
			<Column Name="BillLanguage" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
			<Column Name="BillingFormat" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
			<Column Name="MICR" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
			<Column Name="TypeOfAccount" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
			<Column Name="Bank" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
			<Column Name="Branch" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
			<Column Name="BankAccountNumber" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
			<Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="FormName" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
			<Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
			<Column Name="ApplicationModel" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
			<Column Name="IsGreenTariffApplied" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
			<Column Name="GreenTariff" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
			<Column Name="ApplicationSubType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="IsExistingCustomer" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
			<Column Name="CANumber" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
			<Column Name="IsJoint" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
			<Column Name="ApplicantType" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
			<Column Name="GovernmentType" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
			<Column Name="IsTermConditionAccepted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
			<Column Name="IsCopiedSelfAttested" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
			<Column Name="IsSEZ" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
			<Column Name="BankHolderName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
			<Column Name="IsSAPSent" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
			<Column Name="SAPTempNumber" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
			<Column Name="StartTempDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="EndTempTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="Name1Joint" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
			<Column Name="Name2Joint" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
		</Type>
	</Table>
	<Table Name="dbo.RatusRevamp" Member="RatusRevamps">
		<Type Name="RatusRevamp">
			<Column Name="Id" AutoSync="Never" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
			<Column Name="CANumber" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
			<Column Name="CategoryName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
			<Column Name="Rating" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
			<Column Name="AppreciationNote" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
			<Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
		</Type>
	</Table>
	<Table Name="dbo.CashFreePayment" Member="CashFreePayments">
		<Type Name="CashFreePayment">
			<Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
			<Column Name="OrderNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="OrderToken" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="AccountNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="TimeStamp" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="TranAuthDate" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="StatusCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="StatusDesc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="RespCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="PaymentLink" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
			<Column Name="SettlementAmount" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="SettlementCurrency" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
			<Column Name="Created_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
			<Column Name="Response_Msg" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
		</Type>
	</Table>
</Database>