<?xml version="1.0" encoding="utf-8"?><Database Name="Realty" Class="AdaniHousingFormsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=tcp:adanistaging-sql.database.windows.net,1433;Initial Catalog=Realty;User ID=sitecore" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="RealtyConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AdaniHousingContactUsForm" Member="AdaniHousingContactUsForms">
    <Type Name="AdaniHousingContactUsForm">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Subject" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TicketID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsSubmittedToFreshdesk" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SubmittedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FormName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="PageInfo" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AdaniHousingApplyForLoanForm" Member="AdaniHousingApplyForLoanForms">
    <Type Name="AdaniHousingApplyForLoanForm">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="EmailId" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PanNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="PinCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Occupation" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="LoanAmount" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Tenure" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProductType" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="EnquirySource" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="IsSubmiitedToLMS" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PageInfo" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="FormName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="SubmittedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LMS_Key" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="LMS_Value" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AdaniHousingFeedbackForm" Member="AdaniHousingFeedbackForms">
    <Type Name="AdaniHousingFeedbackForm">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Rating" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FeedbackMsg" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="PageInfo" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="SubmittedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AdaniCapitalHousingPincodeList" Member="AdaniCapitalHousingPincodeLists">
    <Type Name="AdaniCapitalHousingPincodeList">
      <Column Name="No" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Pincode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PostOfficeName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="District" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AdaniHousingRequestCallbackForm" Member="AdaniHousingRequestCallbackForms">
    <Type Name="AdaniHousingRequestCallbackForm">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="PageInfo" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="FreshdeskTicketID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsSubmittedToFreshdesk" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FormName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="SubmittedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AdaniCapitalHousingCollectionCentre" Member="AdaniCapitalHousingCollectionCentres">
    <Type Name="AdaniCapitalHousingCollectionCentre">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OfficeType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MerchantOrShop" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ContactNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Latitude" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Longitude" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AdaniHousingBecomeAPartnerForm" Member="AdaniHousingBecomeAPartnerForms">
    <Type Name="AdaniHousingBecomeAPartnerForm">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Subject" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TicketID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsSubmittedToFreshdesk" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SubmittedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FormName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="PageInfo" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AdaniCapitalBranchList" Member="AdaniCapitalBranchLists">
    <Type Name="AdaniCapitalBranchList">
      <Column Name="SNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Business" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SubsidiaryCompany" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TypeOfAsset" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Site" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Latitude" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Longitude" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AdaniHousingFreshdeskTicketCreate" Member="AdaniHousingFreshdeskTicketCreates">
    <Type Name="AdaniHousingFreshdeskTicketCreate">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LAN" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PageInfo" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="FormName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="IsSubmittedToFreshdesk" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FreshdeskTickedId" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AdaniCapitalHousingOTP" Member="AdaniCapitalHousingOTPs">
    <Type Name="AdaniCapitalHousingOTP">
      <Column Name="No" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PageInfo" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="MobileNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OTP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Count" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ValidateOTPCount" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SessionId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SessionCount" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AdaniHousingUserLoginHistory" Member="AdaniHousingUserLoginHistories">
    <Type Name="AdaniHousingUserLoginHistory">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MobileNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastSessionId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RecentSessionId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastUserIP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RecentUserIP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LogInCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastLoginDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RecentLoginDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>