#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.AdaniHousing.Website
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Realty")]
	public partial class AdaniHousingCareerFormDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAdaniHousingCareersForm(AdaniHousingCareersForm instance);
    partial void UpdateAdaniHousingCareersForm(AdaniHousingCareersForm instance);
    partial void DeleteAdaniHousingCareersForm(AdaniHousingCareersForm instance);
    #endregion
		
		public AdaniHousingCareerFormDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["AdaniCapitalConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AdaniHousingCareerFormDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AdaniHousingCareerFormDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AdaniHousingCareerFormDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AdaniHousingCareerFormDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AdaniHousingCareersForm> AdaniHousingCareersForms
		{
			get
			{
				return this.GetTable<AdaniHousingCareersForm>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AdaniHousingCareersForm")]
	public partial class AdaniHousingCareersForm : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _RegistrationNo;
		
		private string _Name;
		
		private string _LastName;
		
		private string _Email;
		
		private System.Nullable<System.DateTime> _DateOfJoining;
		
		private string _ContactNumber;
		
		private string _City;
		
		private string _Experience;
		
		private string _LinkedinProfile;
		
		private string _ExpectedSalary;
		
		private System.Data.Linq.Binary _UploadedResume;
		
		private string _UploadedResumeLink;
		
		private string _UploadedFileType;
		
		private string _UploadedFileName;
		
		private string _Position;
		
		private System.Nullable<System.DateTime> _FormSubmitOn;
		
		private string _PageInfo;
		
		private string _FormType;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnRegistrationNoChanging(string value);
    partial void OnRegistrationNoChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDateOfJoiningChanging(System.Nullable<System.DateTime> value);
    partial void OnDateOfJoiningChanged();
    partial void OnContactNumberChanging(string value);
    partial void OnContactNumberChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnExperienceChanging(string value);
    partial void OnExperienceChanged();
    partial void OnLinkedinProfileChanging(string value);
    partial void OnLinkedinProfileChanged();
    partial void OnExpectedSalaryChanging(string value);
    partial void OnExpectedSalaryChanged();
    partial void OnUploadedResumeChanging(System.Data.Linq.Binary value);
    partial void OnUploadedResumeChanged();
    partial void OnUploadedResumeLinkChanging(string value);
    partial void OnUploadedResumeLinkChanged();
    partial void OnUploadedFileTypeChanging(string value);
    partial void OnUploadedFileTypeChanged();
    partial void OnUploadedFileNameChanging(string value);
    partial void OnUploadedFileNameChanged();
    partial void OnPositionChanging(string value);
    partial void OnPositionChanged();
    partial void OnFormSubmitOnChanging(System.Nullable<System.DateTime> value);
    partial void OnFormSubmitOnChanged();
    partial void OnPageInfoChanging(string value);
    partial void OnPageInfoChanged();
    partial void OnFormTypeChanging(string value);
    partial void OnFormTypeChanged();
    #endregion
		
		public AdaniHousingCareersForm()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegistrationNo", DbType="NVarChar(500)")]
		public string RegistrationNo
		{
			get
			{
				return this._RegistrationNo;
			}
			set
			{
				if ((this._RegistrationNo != value))
				{
					this.OnRegistrationNoChanging(value);
					this.SendPropertyChanging();
					this._RegistrationNo = value;
					this.SendPropertyChanged("RegistrationNo");
					this.OnRegistrationNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(500)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(500)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(500)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateOfJoining", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateOfJoining
		{
			get
			{
				return this._DateOfJoining;
			}
			set
			{
				if ((this._DateOfJoining != value))
				{
					this.OnDateOfJoiningChanging(value);
					this.SendPropertyChanging();
					this._DateOfJoining = value;
					this.SendPropertyChanged("DateOfJoining");
					this.OnDateOfJoiningChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactNumber", DbType="NVarChar(500)")]
		public string ContactNumber
		{
			get
			{
				return this._ContactNumber;
			}
			set
			{
				if ((this._ContactNumber != value))
				{
					this.OnContactNumberChanging(value);
					this.SendPropertyChanging();
					this._ContactNumber = value;
					this.SendPropertyChanged("ContactNumber");
					this.OnContactNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(500)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Experience", DbType="NVarChar(500)")]
		public string Experience
		{
			get
			{
				return this._Experience;
			}
			set
			{
				if ((this._Experience != value))
				{
					this.OnExperienceChanging(value);
					this.SendPropertyChanging();
					this._Experience = value;
					this.SendPropertyChanged("Experience");
					this.OnExperienceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkedinProfile", DbType="NVarChar(500)")]
		public string LinkedinProfile
		{
			get
			{
				return this._LinkedinProfile;
			}
			set
			{
				if ((this._LinkedinProfile != value))
				{
					this.OnLinkedinProfileChanging(value);
					this.SendPropertyChanging();
					this._LinkedinProfile = value;
					this.SendPropertyChanged("LinkedinProfile");
					this.OnLinkedinProfileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpectedSalary", DbType="NVarChar(500)")]
		public string ExpectedSalary
		{
			get
			{
				return this._ExpectedSalary;
			}
			set
			{
				if ((this._ExpectedSalary != value))
				{
					this.OnExpectedSalaryChanging(value);
					this.SendPropertyChanging();
					this._ExpectedSalary = value;
					this.SendPropertyChanged("ExpectedSalary");
					this.OnExpectedSalaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UploadedResume", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary UploadedResume
		{
			get
			{
				return this._UploadedResume;
			}
			set
			{
				if ((this._UploadedResume != value))
				{
					this.OnUploadedResumeChanging(value);
					this.SendPropertyChanging();
					this._UploadedResume = value;
					this.SendPropertyChanged("UploadedResume");
					this.OnUploadedResumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UploadedResumeLink", DbType="NVarChar(500)")]
		public string UploadedResumeLink
		{
			get
			{
				return this._UploadedResumeLink;
			}
			set
			{
				if ((this._UploadedResumeLink != value))
				{
					this.OnUploadedResumeLinkChanging(value);
					this.SendPropertyChanging();
					this._UploadedResumeLink = value;
					this.SendPropertyChanged("UploadedResumeLink");
					this.OnUploadedResumeLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UploadedFileType", DbType="NVarChar(100)")]
		public string UploadedFileType
		{
			get
			{
				return this._UploadedFileType;
			}
			set
			{
				if ((this._UploadedFileType != value))
				{
					this.OnUploadedFileTypeChanging(value);
					this.SendPropertyChanging();
					this._UploadedFileType = value;
					this.SendPropertyChanged("UploadedFileType");
					this.OnUploadedFileTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UploadedFileName", DbType="NVarChar(100)")]
		public string UploadedFileName
		{
			get
			{
				return this._UploadedFileName;
			}
			set
			{
				if ((this._UploadedFileName != value))
				{
					this.OnUploadedFileNameChanging(value);
					this.SendPropertyChanging();
					this._UploadedFileName = value;
					this.SendPropertyChanged("UploadedFileName");
					this.OnUploadedFileNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Position", DbType="NVarChar(500)")]
		public string Position
		{
			get
			{
				return this._Position;
			}
			set
			{
				if ((this._Position != value))
				{
					this.OnPositionChanging(value);
					this.SendPropertyChanging();
					this._Position = value;
					this.SendPropertyChanged("Position");
					this.OnPositionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormSubmitOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> FormSubmitOn
		{
			get
			{
				return this._FormSubmitOn;
			}
			set
			{
				if ((this._FormSubmitOn != value))
				{
					this.OnFormSubmitOnChanging(value);
					this.SendPropertyChanging();
					this._FormSubmitOn = value;
					this.SendPropertyChanged("FormSubmitOn");
					this.OnFormSubmitOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageInfo", DbType="NVarChar(500)")]
		public string PageInfo
		{
			get
			{
				return this._PageInfo;
			}
			set
			{
				if ((this._PageInfo != value))
				{
					this.OnPageInfoChanging(value);
					this.SendPropertyChanging();
					this._PageInfo = value;
					this.SendPropertyChanged("PageInfo");
					this.OnPageInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormType", DbType="NVarChar(500)")]
		public string FormType
		{
			get
			{
				return this._FormType;
			}
			set
			{
				if ((this._FormType != value))
				{
					this.OnFormTypeChanging(value);
					this.SendPropertyChanging();
					this._FormType = value;
					this.SendPropertyChanged("FormType");
					this.OnFormTypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
