<?xml version="1.0" encoding="utf-8"?><Database Name="Realty" Class="VendorEnrollmentFormDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=tcp:adanistaging-sql.database.windows.net;Initial Catalog=Realty;User ID=Sitecore" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="RealtyConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DefenceVendorEnrollmentForm" Member="DefenceVendorEnrollmentForms">
    <Type Name="DefenceVendorEnrollmentForm">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RegistrationNumber" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="CompanyFullName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Pincode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ContactPerson" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="EmailId" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MobileNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TelephoneNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Website" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="GSTIN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PanNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Tin" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ImportExportCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MSME" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TypeofOwnership" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NumberofEmployees" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SectorServed" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TypeofSupplier" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SegmentsServed" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="PlatformsServed" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AreYouaSupplierTo" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Clientele1" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Clientele2" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Clientele3" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Clientele4" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Clientele5" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CountryandCustomer1" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CountryandCustomer2" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CountryandCustomer3" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Commercial_FY1_Info" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Commercial_FY2_Info" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Commercial_FY3_Info" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SalesValueDandA_FY1" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SalesValueDandA_FY2" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SalesValueDandA_FY3" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SalesValueNonDandA_FY1" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SalesValueNonDandA_FY2" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SalesValueNonDandA_FY3" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AnnualSales_FY1" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AnnualSales_FY2" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AnnualSales_FY3" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="QualityCertification1" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="QualityCertification2" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="QualityCertification3" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="QualityCertification4" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="QualityCertification5" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AnyOtherCertification1" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AnyOtherCertification2" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AnyOtherCertification3" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AnyOtherCertification4" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AnyOtherCertification5" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="IsManufacturer" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ManufacturTypeList" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="ManufacturerSpecification" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IsTrader_Distributer_Dealer_Reseller" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Trade_Distriubtion_Deal_TypeList" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Trade_Distriubtion_Deal_Specifcation" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IsSpclProcess_TestingLabs" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SpclProcess_TestLabs_TypeList" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="SpclProcess_TestLabsSpecification" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IsEngineeringServices" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="EngineeringServicesTypeList" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="EngineeringServicesSpecification" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UploadedCompanyProfileFileLink" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SpecifykeyFacilities" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Place" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FormDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SubmitOnDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FormName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="PageInfo" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SubmittedBy" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DefenceVendorEnrollmentFiles" Member="DefenceVendorEnrollmentFiles">
    <Type Name="DefenceVendorEnrollmentFile">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RegistrationNumber" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="CompanyFullName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="UploadedFileName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="UploadedFile" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="UploadedFileType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>