//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.Ports.Website.MundraCT4ContainerTrackingServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MundraCT4ContainerTrackingServiceReference.get_container_tracking_ct4Soap")]
    public interface get_container_tracking_ct4Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_container_tracking_ct4_data", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet get_container_tracking_ct4_data(string eContno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_container_tracking_ct4_data", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> get_container_tracking_ct4_dataAsync(string eContno);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface get_container_tracking_ct4SoapChannel : Sitecore.Ports.Website.MundraCT4ContainerTrackingServiceReference.get_container_tracking_ct4Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class get_container_tracking_ct4SoapClient : System.ServiceModel.ClientBase<Sitecore.Ports.Website.MundraCT4ContainerTrackingServiceReference.get_container_tracking_ct4Soap>, Sitecore.Ports.Website.MundraCT4ContainerTrackingServiceReference.get_container_tracking_ct4Soap {
        
        public get_container_tracking_ct4SoapClient() {
        }
        
        public get_container_tracking_ct4SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public get_container_tracking_ct4SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public get_container_tracking_ct4SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public get_container_tracking_ct4SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet get_container_tracking_ct4_data(string eContno) {
            return base.Channel.get_container_tracking_ct4_data(eContno);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> get_container_tracking_ct4_dataAsync(string eContno) {
            return base.Channel.get_container_tracking_ct4_dataAsync(eContno);
        }
    }
}
