<?xml version="1.0" encoding="utf-8"?><Database Name="Realty" Class="AdaniFoundationCareersFormDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=tcp:adanistaging-sql.database.windows.net;Initial Catalog=Realty;User ID=Sitecore" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="RealtyConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AdaniFoundationCareerForm" Member="AdaniFoundationCareerForms">
    <Type Name="AdaniFoundationCareerForm">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="CurrentOrganization" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="ContactNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CurrentDesignation" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Education" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="CurrentCTC" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Experience" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="ResumeAttachment" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="FormType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="SubmitOn" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="PageInfo" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
</Database>