<?xml version="1.0" encoding="utf-8"?><Database Name="ElectricityTender" Class="EnquiryDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=tcp:adanistaging-sql.database.windows.net,1433;Initial Catalog=ElectricityTender;User ID=sitecore" SettingsObjectName="Sitecore.BelvedereClubGurgaon.Website.Properties.Settings" SettingsPropertyName="ElectricityTenderConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.user_otp" Member="user_otps">
    <Type Name="user_otp">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MobileNumber" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="otp" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
</Database>