<?xml version="1.0" encoding="utf-8"?><Database Name="Realty" Class="ClubAhmdRoomAvailabilityDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=tcp:adanistaging-sql.database.windows.net,1433;Initial Catalog=Realty;User ID=sitecore" SettingsObjectName="Sitecore.BelvedereClubAhmedabad.Website.Properties.Settings" SettingsPropertyName="RealtyConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ClubAhmedabadRoomAvailability" Member="ClubAhmedabadRoomAvailabilities">
    <Type Name="ClubAhmedabadRoomAvailability">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="BookDateFrom" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="BookDateTo" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NoOfRoom" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NoOfAdults" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NoOfKids" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="MobileNo" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="FormSubmitOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>