<?xml version="1.0" encoding="utf-8"?><Database Name="Realty" Class="ClubAhmedabadEnquiryDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=tcp:adanistaging-sql.database.windows.net,1433;Initial Catalog=Realty;User ID=sitecore" SettingsObjectName="Sitecore.BelvedereClubAhmedabad.Website.Properties.Settings" SettingsPropertyName="RealtyConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ClubAhmedabadEnquiry" Member="ClubAhmedabadEnquiries">
    <Type Name="ClubAhmedabadEnquiry">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="InterestedIn" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="FormType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="FormSubmitOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>