<?xml version="1.0" encoding="utf-8"?><Database Name="Realty" Class="BunkeringContactFormRecordDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=tcp:adanistaging-sql.database.windows.net,1433;Initial Catalog=Realty;User ID=sitecore" SettingsObjectName="Sitecore.Bunkering.Website.Properties.Settings" SettingsPropertyName="RealtyConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BunkeringContactFormRecord" Member="BunkeringContactFormRecords">
    <Type Name="BunkeringContactFormRecord">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="MessageType" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FormType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PageInfo" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FormSubmitOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.BunkeringRequestQuoteRecord" Member="BunkeringRequestQuoteRecords">
    <Type Name="BunkeringRequestQuoteRecord">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ContactPerson" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProductType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProductSpec" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProductQuantity" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="VesselName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Port" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Berth" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Estimated_DOA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Estimated_TOA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Estimated_DOD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Estimated_TOD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Agent" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="OtherDetails" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FormType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PageInfo" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FormSubmitOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>