<?xml version="1.0" encoding="utf-8"?><Database Name="Realty" Class="AGELPortalDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=tcp:adanistaging-sql.database.windows.net;Initial Catalog=Realty;User ID=Sitecore" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="RealtyConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AGElPortalCategory" Member="AGElPortalCategories">
    <Type Name="AGElPortalCategory">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="created_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="modified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AGELPortalContents" Member="AGELPortalContents">
    <Type Name="AGELPortalContent">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="category_id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="contetn_type" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="title" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="discription" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="document_data" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="url" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="created_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="modify_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="category_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UploadImage_data" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DocVideoCnt" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DocVideoImage_Name" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.AGELPortalRegistration" Member="AGELPortalRegistrations">
    <Type Name="AGELPortalRegistration">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="mobile" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="user_type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="allow_login" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="email_verified" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="mobile_verified" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="created_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="modified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="site" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="vendor" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="content_type" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AGELPortalLessonLearningVideo" Member="AGELPortalLessonLearningVideos">
    <Type Name="AGELPortalLessonLearningVideo">
      <Column Name="id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="video_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="video_url" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="user_id" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="user_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="created_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="video_id" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="content_type" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="category_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="docvideocnt" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AGELPortalUserLoginHistory" Member="AGELPortalUserLoginHistories">
    <Type Name="AGELPortalUserLoginHistory">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="[User Id]" Member="User_Id" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="[Login Time]" Member="Login_Time" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="checkLoginAttempts" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.AGElPortalOtpHistory" Member="AGElPortalOtpHistories">
    <Type Name="AGElPortalOtpHistory">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="otp_for" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="otp" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="WrongOTPAttempts" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsuserLock" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.AGELPortalCity" Member="AGELPortalCities">
    <Type Name="AGELPortalCity">
      <Column Name="id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="sitename" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>