#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.MiracleMile.Website
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Realty")]
	public partial class MiracleMileFormDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMiracleMileFormData(MiracleMileFormData instance);
    partial void UpdateMiracleMileFormData(MiracleMileFormData instance);
    partial void DeleteMiracleMileFormData(MiracleMileFormData instance);
    #endregion
		
		public MiracleMileFormDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["MiracleMileConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MiracleMileFormDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MiracleMileFormDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MiracleMileFormDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MiracleMileFormDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MiracleMileFormData> MiracleMileFormDatas
		{
			get
			{
				return this.GetTable<MiracleMileFormData>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MiracleMileFormData")]
	public partial class MiracleMileFormData : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _Mobile;
		
		private string _Email;
		
		private System.Nullable<decimal> _Budget;
		
		private string _Country;
		
		private string _State;
		
		private string _PropertyType;
		
		private string _PropertyLocation;
		
		private string _sale_type;
		
		private string _Comment;
		
		private string _FormType;
		
		private string _PageInfo;
		
		private System.Nullable<System.DateTime> _FormSubmitOn;
		
		private string _UTMSource;
		
		private string _Lead_City;
		
		private string _Lead_Source;
		
		private string _Lead_Sub_Source;
		
		private string _Lead_Status;
		
		private string _Lead_Sub_Status;
		
		private string _Lead_Gender;
		
		private string _Lead_Profession;
		
		private string _Lead_ReasonForPurchase;
		
		private string _Lead_Property_Stage;
		
		private string _Lead_Configuration;
		
		private string _Lead_PreSalesAgent;
		
		private string _Lead_InboundCall;
		
		private string _Lead_Lost_Reasons;
		
		private string _EntrySource;
		
		private string _City;
		
		private System.Nullable<System.DateTime> _ScheduledFollowUp;
		
		private string _FormSubmitBy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnMobileChanging(string value);
    partial void OnMobileChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnBudgetChanging(System.Nullable<decimal> value);
    partial void OnBudgetChanged();
    partial void OnCountryChanging(string value);
    partial void OnCountryChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnPropertyTypeChanging(string value);
    partial void OnPropertyTypeChanged();
    partial void OnPropertyLocationChanging(string value);
    partial void OnPropertyLocationChanged();
    partial void Onsale_typeChanging(string value);
    partial void Onsale_typeChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    partial void OnFormTypeChanging(string value);
    partial void OnFormTypeChanged();
    partial void OnPageInfoChanging(string value);
    partial void OnPageInfoChanged();
    partial void OnFormSubmitOnChanging(System.Nullable<System.DateTime> value);
    partial void OnFormSubmitOnChanged();
    partial void OnUTMSourceChanging(string value);
    partial void OnUTMSourceChanged();
    partial void OnLead_CityChanging(string value);
    partial void OnLead_CityChanged();
    partial void OnLead_SourceChanging(string value);
    partial void OnLead_SourceChanged();
    partial void OnLead_Sub_SourceChanging(string value);
    partial void OnLead_Sub_SourceChanged();
    partial void OnLead_StatusChanging(string value);
    partial void OnLead_StatusChanged();
    partial void OnLead_Sub_StatusChanging(string value);
    partial void OnLead_Sub_StatusChanged();
    partial void OnLead_GenderChanging(string value);
    partial void OnLead_GenderChanged();
    partial void OnLead_ProfessionChanging(string value);
    partial void OnLead_ProfessionChanged();
    partial void OnLead_ReasonForPurchaseChanging(string value);
    partial void OnLead_ReasonForPurchaseChanged();
    partial void OnLead_Property_StageChanging(string value);
    partial void OnLead_Property_StageChanged();
    partial void OnLead_ConfigurationChanging(string value);
    partial void OnLead_ConfigurationChanged();
    partial void OnLead_PreSalesAgentChanging(string value);
    partial void OnLead_PreSalesAgentChanged();
    partial void OnLead_InboundCallChanging(string value);
    partial void OnLead_InboundCallChanged();
    partial void OnLead_Lost_ReasonsChanging(string value);
    partial void OnLead_Lost_ReasonsChanged();
    partial void OnEntrySourceChanging(string value);
    partial void OnEntrySourceChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnScheduledFollowUpChanging(System.Nullable<System.DateTime> value);
    partial void OnScheduledFollowUpChanged();
    partial void OnFormSubmitByChanging(string value);
    partial void OnFormSubmitByChanged();
    #endregion
		
		public MiracleMileFormData()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(150)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(150)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="NVarChar(150)")]
		public string Mobile
		{
			get
			{
				return this._Mobile;
			}
			set
			{
				if ((this._Mobile != value))
				{
					this.OnMobileChanging(value);
					this.SendPropertyChanging();
					this._Mobile = value;
					this.SendPropertyChanged("Mobile");
					this.OnMobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(150)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Budget", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Budget
		{
			get
			{
				return this._Budget;
			}
			set
			{
				if ((this._Budget != value))
				{
					this.OnBudgetChanging(value);
					this.SendPropertyChanging();
					this._Budget = value;
					this.SendPropertyChanged("Budget");
					this.OnBudgetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="NVarChar(150)")]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this.OnCountryChanging(value);
					this.SendPropertyChanging();
					this._Country = value;
					this.SendPropertyChanged("Country");
					this.OnCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="NVarChar(150)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PropertyType", DbType="NVarChar(150)")]
		public string PropertyType
		{
			get
			{
				return this._PropertyType;
			}
			set
			{
				if ((this._PropertyType != value))
				{
					this.OnPropertyTypeChanging(value);
					this.SendPropertyChanging();
					this._PropertyType = value;
					this.SendPropertyChanged("PropertyType");
					this.OnPropertyTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PropertyLocation", DbType="NVarChar(150)")]
		public string PropertyLocation
		{
			get
			{
				return this._PropertyLocation;
			}
			set
			{
				if ((this._PropertyLocation != value))
				{
					this.OnPropertyLocationChanging(value);
					this.SendPropertyChanging();
					this._PropertyLocation = value;
					this.SendPropertyChanged("PropertyLocation");
					this.OnPropertyLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sale_type", DbType="NVarChar(150)")]
		public string sale_type
		{
			get
			{
				return this._sale_type;
			}
			set
			{
				if ((this._sale_type != value))
				{
					this.Onsale_typeChanging(value);
					this.SendPropertyChanging();
					this._sale_type = value;
					this.SendPropertyChanged("sale_type");
					this.Onsale_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(MAX)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormType", DbType="NVarChar(150)")]
		public string FormType
		{
			get
			{
				return this._FormType;
			}
			set
			{
				if ((this._FormType != value))
				{
					this.OnFormTypeChanging(value);
					this.SendPropertyChanging();
					this._FormType = value;
					this.SendPropertyChanged("FormType");
					this.OnFormTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageInfo", DbType="NVarChar(150)")]
		public string PageInfo
		{
			get
			{
				return this._PageInfo;
			}
			set
			{
				if ((this._PageInfo != value))
				{
					this.OnPageInfoChanging(value);
					this.SendPropertyChanging();
					this._PageInfo = value;
					this.SendPropertyChanged("PageInfo");
					this.OnPageInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormSubmitOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> FormSubmitOn
		{
			get
			{
				return this._FormSubmitOn;
			}
			set
			{
				if ((this._FormSubmitOn != value))
				{
					this.OnFormSubmitOnChanging(value);
					this.SendPropertyChanging();
					this._FormSubmitOn = value;
					this.SendPropertyChanged("FormSubmitOn");
					this.OnFormSubmitOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UTMSource", DbType="NVarChar(500)")]
		public string UTMSource
		{
			get
			{
				return this._UTMSource;
			}
			set
			{
				if ((this._UTMSource != value))
				{
					this.OnUTMSourceChanging(value);
					this.SendPropertyChanging();
					this._UTMSource = value;
					this.SendPropertyChanged("UTMSource");
					this.OnUTMSourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lead_City", DbType="NVarChar(50)")]
		public string Lead_City
		{
			get
			{
				return this._Lead_City;
			}
			set
			{
				if ((this._Lead_City != value))
				{
					this.OnLead_CityChanging(value);
					this.SendPropertyChanging();
					this._Lead_City = value;
					this.SendPropertyChanged("Lead_City");
					this.OnLead_CityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lead_Source", DbType="NVarChar(150)")]
		public string Lead_Source
		{
			get
			{
				return this._Lead_Source;
			}
			set
			{
				if ((this._Lead_Source != value))
				{
					this.OnLead_SourceChanging(value);
					this.SendPropertyChanging();
					this._Lead_Source = value;
					this.SendPropertyChanged("Lead_Source");
					this.OnLead_SourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lead_Sub_Source", DbType="NVarChar(150)")]
		public string Lead_Sub_Source
		{
			get
			{
				return this._Lead_Sub_Source;
			}
			set
			{
				if ((this._Lead_Sub_Source != value))
				{
					this.OnLead_Sub_SourceChanging(value);
					this.SendPropertyChanging();
					this._Lead_Sub_Source = value;
					this.SendPropertyChanged("Lead_Sub_Source");
					this.OnLead_Sub_SourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lead_Status", DbType="NVarChar(50)")]
		public string Lead_Status
		{
			get
			{
				return this._Lead_Status;
			}
			set
			{
				if ((this._Lead_Status != value))
				{
					this.OnLead_StatusChanging(value);
					this.SendPropertyChanging();
					this._Lead_Status = value;
					this.SendPropertyChanged("Lead_Status");
					this.OnLead_StatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lead_Sub_Status", DbType="NVarChar(50)")]
		public string Lead_Sub_Status
		{
			get
			{
				return this._Lead_Sub_Status;
			}
			set
			{
				if ((this._Lead_Sub_Status != value))
				{
					this.OnLead_Sub_StatusChanging(value);
					this.SendPropertyChanging();
					this._Lead_Sub_Status = value;
					this.SendPropertyChanged("Lead_Sub_Status");
					this.OnLead_Sub_StatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lead_Gender", DbType="NVarChar(50)")]
		public string Lead_Gender
		{
			get
			{
				return this._Lead_Gender;
			}
			set
			{
				if ((this._Lead_Gender != value))
				{
					this.OnLead_GenderChanging(value);
					this.SendPropertyChanging();
					this._Lead_Gender = value;
					this.SendPropertyChanged("Lead_Gender");
					this.OnLead_GenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lead_Profession", DbType="NVarChar(100)")]
		public string Lead_Profession
		{
			get
			{
				return this._Lead_Profession;
			}
			set
			{
				if ((this._Lead_Profession != value))
				{
					this.OnLead_ProfessionChanging(value);
					this.SendPropertyChanging();
					this._Lead_Profession = value;
					this.SendPropertyChanged("Lead_Profession");
					this.OnLead_ProfessionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lead_ReasonForPurchase", DbType="NVarChar(150)")]
		public string Lead_ReasonForPurchase
		{
			get
			{
				return this._Lead_ReasonForPurchase;
			}
			set
			{
				if ((this._Lead_ReasonForPurchase != value))
				{
					this.OnLead_ReasonForPurchaseChanging(value);
					this.SendPropertyChanging();
					this._Lead_ReasonForPurchase = value;
					this.SendPropertyChanged("Lead_ReasonForPurchase");
					this.OnLead_ReasonForPurchaseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lead_Property_Stage", DbType="NVarChar(100)")]
		public string Lead_Property_Stage
		{
			get
			{
				return this._Lead_Property_Stage;
			}
			set
			{
				if ((this._Lead_Property_Stage != value))
				{
					this.OnLead_Property_StageChanging(value);
					this.SendPropertyChanging();
					this._Lead_Property_Stage = value;
					this.SendPropertyChanged("Lead_Property_Stage");
					this.OnLead_Property_StageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lead_Configuration", DbType="NVarChar(100)")]
		public string Lead_Configuration
		{
			get
			{
				return this._Lead_Configuration;
			}
			set
			{
				if ((this._Lead_Configuration != value))
				{
					this.OnLead_ConfigurationChanging(value);
					this.SendPropertyChanging();
					this._Lead_Configuration = value;
					this.SendPropertyChanged("Lead_Configuration");
					this.OnLead_ConfigurationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lead_PreSalesAgent", DbType="NVarChar(100)")]
		public string Lead_PreSalesAgent
		{
			get
			{
				return this._Lead_PreSalesAgent;
			}
			set
			{
				if ((this._Lead_PreSalesAgent != value))
				{
					this.OnLead_PreSalesAgentChanging(value);
					this.SendPropertyChanging();
					this._Lead_PreSalesAgent = value;
					this.SendPropertyChanged("Lead_PreSalesAgent");
					this.OnLead_PreSalesAgentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lead_InboundCall", DbType="NVarChar(100)")]
		public string Lead_InboundCall
		{
			get
			{
				return this._Lead_InboundCall;
			}
			set
			{
				if ((this._Lead_InboundCall != value))
				{
					this.OnLead_InboundCallChanging(value);
					this.SendPropertyChanging();
					this._Lead_InboundCall = value;
					this.SendPropertyChanged("Lead_InboundCall");
					this.OnLead_InboundCallChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lead_Lost_Reasons", DbType="NVarChar(150)")]
		public string Lead_Lost_Reasons
		{
			get
			{
				return this._Lead_Lost_Reasons;
			}
			set
			{
				if ((this._Lead_Lost_Reasons != value))
				{
					this.OnLead_Lost_ReasonsChanging(value);
					this.SendPropertyChanging();
					this._Lead_Lost_Reasons = value;
					this.SendPropertyChanged("Lead_Lost_Reasons");
					this.OnLead_Lost_ReasonsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntrySource", DbType="NVarChar(100)")]
		public string EntrySource
		{
			get
			{
				return this._EntrySource;
			}
			set
			{
				if ((this._EntrySource != value))
				{
					this.OnEntrySourceChanging(value);
					this.SendPropertyChanging();
					this._EntrySource = value;
					this.SendPropertyChanged("EntrySource");
					this.OnEntrySourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(50)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScheduledFollowUp", DbType="DateTime")]
		public System.Nullable<System.DateTime> ScheduledFollowUp
		{
			get
			{
				return this._ScheduledFollowUp;
			}
			set
			{
				if ((this._ScheduledFollowUp != value))
				{
					this.OnScheduledFollowUpChanging(value);
					this.SendPropertyChanging();
					this._ScheduledFollowUp = value;
					this.SendPropertyChanged("ScheduledFollowUp");
					this.OnScheduledFollowUpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormSubmitBy", DbType="NVarChar(100)")]
		public string FormSubmitBy
		{
			get
			{
				return this._FormSubmitBy;
			}
			set
			{
				if ((this._FormSubmitBy != value))
				{
					this.OnFormSubmitByChanging(value);
					this.SendPropertyChanging();
					this._FormSubmitBy = value;
					this.SendPropertyChanged("FormSubmitBy");
					this.OnFormSubmitByChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
