<?xml version="1.0" encoding="utf-8"?><Database Name="Realty" Class="InspireBPFormDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=tcp:adanistaging-sql.database.windows.net;Initial Catalog=Realty;User ID=Sitecore" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="RealtyConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.MiracleMileFormData" Member="MiracleMileFormDatas">
    <Type Name="MiracleMileFormData">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Budget" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PropertyType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PropertyLocation" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="sale_type" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FormType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PageInfo" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="FormSubmitOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UTMSource" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Lead_City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lead_Source" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Lead_Sub_Source" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Lead_Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lead_Sub_Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lead_Gender" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lead_Profession" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_ReasonForPurchase" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Lead_Property_Stage" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_Configuration" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_PreSalesAgent" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_InboundCall" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_Lost_Reasons" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="EntrySource" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ScheduledFollowUp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FormSubmitBy" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
</Database>