//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.Ports.Website.MurmugaoExpectedServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MurmugaoExpectedServiceReference.get_vessel_at_expectedSoap")]
    public interface get_vessel_at_expectedSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_vessel_at_expected_data", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet get_vessel_at_expected_data();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_vessel_at_expected_data", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> get_vessel_at_expected_dataAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface get_vessel_at_expectedSoapChannel : Sitecore.Ports.Website.MurmugaoExpectedServiceReference.get_vessel_at_expectedSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class get_vessel_at_expectedSoapClient : System.ServiceModel.ClientBase<Sitecore.Ports.Website.MurmugaoExpectedServiceReference.get_vessel_at_expectedSoap>, Sitecore.Ports.Website.MurmugaoExpectedServiceReference.get_vessel_at_expectedSoap {
        
        public get_vessel_at_expectedSoapClient() {
        }
        
        public get_vessel_at_expectedSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public get_vessel_at_expectedSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public get_vessel_at_expectedSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public get_vessel_at_expectedSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet get_vessel_at_expected_data() {
            return base.Channel.get_vessel_at_expected_data();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> get_vessel_at_expected_dataAsync() {
            return base.Channel.get_vessel_at_expected_dataAsync();
        }
    }
}
