<?xml version="1.0" encoding="utf-8"?><Database Name="adanirealty_Custom" Class="AdaniRealityDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LT-0105-F19D5B3;Initial Catalog=adanirealty_Custom;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="adanirealty_CustomConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[Reality_ OTP]" Member="Reality__OTPs">
    <Type Name="Reality__OTP">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OTP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Session" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Attempt" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AsterEnquireNow" Member="AsterEnquireNows">
    <Type Name="AsterEnquireNow">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Budget" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PropertyType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PropertyLocation" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="sale_type" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FormType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PageInfo" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="FormSubmitOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UTMSource" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Lead_City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lead_Source" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Lead_Sub_Source" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Lead_Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lead_Sub_Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lead_Gender" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lead_Profession" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_ReasonForPurchase" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Lead_Property_Stage" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_Configuration" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_PreSalesAgent" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_InboundCall" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_Lost_Reasons" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="EntrySource" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ScheduledFollowUp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FormSubmitBy" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PageUrl" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.OysterGrandeEnquireNow" Member="OysterGrandeEnquireNows">
    <Type Name="OysterGrandeEnquireNow">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="FormSubmitOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.OysterGrandePenthouseEnquireNow" Member="OysterGrandePenthouseEnquireNows">
    <Type Name="OysterGrandePenthouseEnquireNow">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Budget" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PropertyType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PropertyLocation" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="sale_type" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FormType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PageInfo" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="FormSubmitOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UTMSource" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Lead_City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lead_Source" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Lead_Sub_Source" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Lead_Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lead_Sub_Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lead_Gender" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lead_Profession" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_ReasonForPurchase" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Lead_Property_Stage" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_Configuration" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_PreSalesAgent" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_InboundCall" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_Lost_Reasons" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="EntrySource" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ScheduledFollowUp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FormSubmitBy" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PageUrl" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.platinumRealtyEnquireFormData" Member="platinumRealtyEnquireFormDatas">
    <Type Name="platinumRealtyEnquireFormData">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Budget" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PropertyType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PropertyLocation" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="sale_type" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FormType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PageInfo" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="FormSubmitOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UTMSource" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Lead_City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lead_Source" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Lead_Sub_Source" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Lead_Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lead_Sub_Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lead_Gender" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lead_Profession" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_ReasonForPurchase" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Lead_Property_Stage" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_Configuration" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_PreSalesAgent" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_InboundCall" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_Lost_Reasons" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="EntrySource" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ScheduledFollowUp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FormSubmitBy" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PageUrl" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.ConsolidateFormData" Member="ConsolidateFormDatas">
    <Type Name="ConsolidateFormData">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Budget" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PropertyType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PropertyLocation" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="sale_type" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FormType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PageInfo" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="FormSubmitOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UTMSource" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Lead_City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lead_Source" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Lead_Sub_Source" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Lead_Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lead_Sub_Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lead_Gender" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lead_Profession" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_ReasonForPurchase" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Lead_Property_Stage" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_Configuration" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_PreSalesAgent" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_InboundCall" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_Lost_Reasons" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="EntrySource" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ScheduledFollowUp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FormSubmitBy" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.platinumRealtyOtpHistory" Member="platinumRealtyOtpHistories">
    <Type Name="platinumRealtyOtpHistory">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MobileNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="otp" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.platinumRealtyDownloadBrochureFormData" Member="platinumRealtyDownloadBrochureFormDatas">
    <Type Name="platinumRealtyDownloadBrochureFormData">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Budget" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PropertyType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PropertyLocation" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="sale_type" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FormType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PageInfo" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="FormSubmitOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UTMSource" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Lead_City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lead_Source" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Lead_Sub_Source" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Lead_Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lead_Sub_Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lead_Gender" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lead_Profession" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_ReasonForPurchase" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Lead_Property_Stage" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_Configuration" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_PreSalesAgent" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_InboundCall" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_Lost_Reasons" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="EntrySource" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ScheduledFollowUp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FormSubmitBy" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SamsaraVilasaEnquireNow" Member="SamsaraVilasaEnquireNows">
    <Type Name="SamsaraVilasaEnquireNow">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Budget" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PropertyType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PropertyLocation" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="sale_type" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FormType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PageInfo" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="FormSubmitOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UTMSource" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Lead_City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lead_Source" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Lead_Sub_Source" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Lead_Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lead_Sub_Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lead_Gender" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lead_Profession" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_ReasonForPurchase" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Lead_Property_Stage" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_Configuration" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_PreSalesAgent" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_InboundCall" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_Lost_Reasons" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="EntrySource" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ScheduledFollowUp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FormSubmitBy" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PageUrl" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.GoodLifeFestEnquireNow" Member="GoodLifeFestEnquireNows">
    <Type Name="GoodLifeFestEnquireNow">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Project" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Budget" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PropertyType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PropertyLocation" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="sale_type" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FormType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PageInfo" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="FormSubmitOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UTMSource" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Lead_City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lead_Source" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Lead_Sub_Source" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Lead_Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lead_Sub_Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lead_Gender" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lead_Profession" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_ReasonForPurchase" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Lead_Property_Stage" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_Configuration" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_PreSalesAgent" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_InboundCall" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_Lost_Reasons" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="EntrySource" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ScheduledFollowUp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FormSubmitBy" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PageUrl" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.NriCornerDataBase" Member="NriCornerDataBases">
    <Type Name="NriCornerDataBase">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Projectname" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="RecordType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="MasterProjectID" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PropertyType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="FormType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="UTMSource" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="UTMPlacement" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AdvertisementID" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="TermsAndCondition" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HomeLoan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="PageInfo" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Session" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="country" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PageUrl" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ArchwayEnquireNow" Member="ArchwayEnquireNows">
    <Type Name="ArchwayEnquireNow">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Budget" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PropertyType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PropertyLocation" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="sale_type" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FormType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Projectname" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PageInfo" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="FormSubmitOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UTMSource" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Lead_City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lead_Source" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Lead_Sub_Source" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Lead_Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lead_Sub_Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lead_Gender" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lead_Profession" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_ReasonForPurchase" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Lead_Property_Stage" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_Configuration" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_PreSalesAgent" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_InboundCall" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_Lost_Reasons" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="EntrySource" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ScheduledFollowUp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FormSubmitBy" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PageUrl" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.AtriusEnquireNow" Member="AtriusEnquireNows">
    <Type Name="AtriusEnquireNow">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Budget" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PropertyType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PropertyLocation" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="sale_type" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FormType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PageInfo" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="FormSubmitOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Projectname" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="UTMSource" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Lead_City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lead_Source" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Lead_Sub_Source" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Lead_Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lead_Sub_Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lead_Gender" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lead_Profession" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_ReasonForPurchase" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Lead_Property_Stage" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_Configuration" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_PreSalesAgent" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_InboundCall" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lead_Lost_Reasons" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="EntrySource" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ScheduledFollowUp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FormSubmitBy" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PageUrl" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.ZeroEmiEnquireNow" Member="ZeroEmiEnquireNows">
    <Type Name="ZeroEmiEnquireNow">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Project" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="RecordType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="MasterProjectID" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="AdvertisementID" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PropertyType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PropertyLocation" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FormType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PageInfo" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="FormSubmitOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UTMSource" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Lead_Sub_Source" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PageUrl" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.SamsaraVilasa2EnquireNow" Member="SamsaraVilasa2EnquireNows">
    <Type Name="SamsaraVilasa2EnquireNow">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PropertyType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PropertyLocation" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FormType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PageInfo" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="FormSubmitOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UTMSource" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Lead_Sub_Source" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PageUrl" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="MasterProjectID" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="AdvertisementID" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Project" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="RecordType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.InspireBusinessParkEnquireNow" Member="InspireBusinessParkEnquireNows">
    <Type Name="InspireBusinessParkEnquireNow">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PropertyType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PropertyLocation" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FormType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PageInfo" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="FormSubmitOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UTMSource" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Lead_Sub_Source" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PageUrl" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="MasterProjectID" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="AdvertisementID" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Project" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="RecordType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
</Database>