<?xml version="1.0" encoding="utf-8"?><Database Name="Realty" Class="AccountRegistrationFormDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=adanistaging-sql.database.windows.net;Initial Catalog=Realty;User ID=Sitecore" SettingsObjectName="Sitecore.Ports.Website.Properties.Settings" SettingsPropertyName="RealtyConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.PortsAccountRegistrationForm" Member="PortsAccountRegistrationForms">
    <Type Name="PortsAccountRegistrationForm">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserRegisterationID" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TypeofCustomers" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="PortType" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ShippingAgentDetails" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NameofPrincipal" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NameofCompany" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CompanyRegistrationDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SCMTRCode" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SCMTRID" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="PANNumber" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TANNumber" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="GSTNumber" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="RegisteredOfficeAddress" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="RegisteredOfficeState" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="RegisteredOfficeCountry" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="RegisteredOfficeContactNumber" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="RegisteredOfficeEmail" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="LocalOfficeAddress" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="LocalOfficeState" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="LocalOfficeCountry" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="LocalOfficeContactNumber" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="LocalOfficeEmail" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="BillingAddress" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="BillingState" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="BillingCountry" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="BillingContactNumber" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="BillingEmail" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="OperationsName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="OperationsDesignation" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="OperationDirectNo" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="OperationMobileNumber" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="OperationEmailID" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="OperationsName2" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="OperationsDesignation2" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="OperationDirectNo2" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="OperationMobileNumber2" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="OperationEmailID2" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="OperationsName3" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="OperationsDesignation3" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="OperationDirectNo3" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="OperationMobileNumber3" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="OperationEmailID3" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FinanceName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FinanceDesignation" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FinanceDirectNo" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FinanceMobileNumber" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FinanceEmailID" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FinanceName2" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FinanceDesignation2" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FinanceDirectNo2" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FinanceMobileNumber2" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FinanceEmailID2" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FinanceName3" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FinanceDesignation3" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FinanceDirectNo3" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FinanceMobileNumber3" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FinanceEmailID3" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="MICTRegisterCode" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CT2RegisterCode" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CT3RegisterCode" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CT4RegisterCode" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="T2RegisterCode" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Rupees" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RupeesInWords" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AgreementWithPrincipal" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CertificationOfIncorporation" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="MemorandumArticleAssociation" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DrivingLicense" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="PanCard" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AcknowledgementGSTRegistration" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="IECodeCertificate" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="MunicipalLicence" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AEOLicence" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CustomDPDPermission" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CancelledCheque" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Designation" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SubmitOnDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CommunicationEmail1" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CommunicationEmail2" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CommunicationEmail3" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FormType" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="PageInfo" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="PowerofAttorney" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SCMTRProof" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
</Database>