<?xml version="1.0" encoding="utf-8"?><Database Name="Realty" Class="PortsGMSDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=adanistaging-sql.database.windows.net;Initial Catalog=Realty;User ID=Sitecore" SettingsObjectName="Sitecore.Ports.Website.Properties.Settings" SettingsPropertyName="RealtyConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.PortsGms_Registration_Attachments" Member="PortsGms_Registration_Attachments">
    <Type Name="PortsGms_Registration_Attachment">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Gms_Registration_Id" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ContentType" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DocData" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Created_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Modified_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="PortsGms_Registration_PortsGms_Registration_Attachment" Member="PortsGms_Registration" ThisKey="Gms_Registration_Id" OtherKey="Id" Type="PortsGms_Registration" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PortsGMSOTPHistory" Member="PortsGMSOTPHistories">
    <Type Name="PortsGMSOTPHistory">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OTPType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OTPFor" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="OTP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PortsGMSLoginHistory" Member="PortsGMSLoginHistories">
    <Type Name="PortsGMSLoginHistory">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LoginId" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Create_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PortsGms_Grievance_Booking_Attachments" Member="PortsGms_Grievance_Booking_Attachments">
    <Type Name="PortsGms_Grievance_Booking_Attachment">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Grievance_booking_Id" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ContentType" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DocData" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Created_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Modified_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PortsGMSInCompleteGrievance" Member="PortsGMSInCompleteGrievances">
    <Type Name="PortsGMSInCompleteGrievance">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GirevanceId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Modified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PortsGms_Registration" Member="PortsGms_Registrations">
    <Type Name="PortsGms_Registration">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="DOB" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Fax_No" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Department" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Qustion" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Answer" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Company_Name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Pin_Code" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="User_Type" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Corporate_User" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Allow_Login" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Email_Verified" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Mobile_Verified" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Created_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Modified_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="WhatsappNumber" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="BusinessGroup" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Team" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="SiteHead" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="HO" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Association Name="PortsGms_Registration_PortsGms_Registration_Attachment" Member="PortsGms_Registration_Attachments" ThisKey="Id" OtherKey="Gms_Registration_Id" Type="PortsGms_Registration_Attachment" />
    </Type>
  </Table>
  <Table Name="dbo.PortsGMSBookingAssignment" Member="PortsGMSBookingAssignments">
    <Type Name="PortsGMSBookingAssignment">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GrievanceBookingId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="RegistrationId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="LevelInfo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Response" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Department" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="BusinessGroup" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SiteHead" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PointMan" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Comments" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AssignedLevel" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="ActionDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AssignedState" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HOType" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PortsGMSGrievanceBookingOnBehalf" Member="PortsGMSGrievanceBookingOnBehalfs">
    <Type Name="PortsGMSGrievanceBookingOnBehalf">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="OnBehalf" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Created_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Modified_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BookingId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PortsGMSGrievanceBooking" Member="PortsGMSGrievanceBookings">
    <Type Name="PortsGMSGrievanceBooking">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nature" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Subject" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Company" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="WhoImpacted" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Brief" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="RegistrationId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Created_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Modified_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PointMan" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="BuisnessGroup" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SiteHead" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AssignedLevel" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AssignedState" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FinalComment" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="HOType" Type="System.String" DbType="NChar(150)" CanBeNull="true" />
      <Column Name="ChkResponse" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="StakeholderRemarks" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>