<?xml version="1.0" encoding="utf-8"?><Database Name="Realty" Class="PortsIncomeTaxDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=adanistaging-sql.database.windows.net;Initial Catalog=Realty;User ID=Sitecore" SettingsObjectName="Sitecore.Ports.Website.Properties.Settings" SettingsPropertyName="RealtyConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.PortsIncomeTaxReturns" Member="PortsIncomeTaxReturns">
    <Type Name="PortsIncomeTaxReturn">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="VendorId" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="VendorName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="PanCardNumber" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AadharCardNumber" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="LinkedPanWithAdhar" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AadharPanAttachment" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FilledItReturns" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ProofOfItReturn" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FormName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FormSubmitOn" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
</Database>