<?xml version="1.0" encoding="utf-8"?><Database Name="Realty" Class="PortsQuoteDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=tcp:adanistaging-sql.database.windows.net;Initial Catalog=Realty;User ID=sitecore" SettingsObjectName="Sitecore.Ports.Website.Properties.Settings" SettingsPropertyName="RealtyConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.PortsQuoteDetail" Member="PortsQuoteDetails">
    <Type Name="PortsQuoteDetail">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Company" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DeliveryType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Commodity" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ExpectedQuantity" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ExpectedDate" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FormType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PageInfo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FormSubmitOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CommodityType" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.PortsLogisticsQuoteDetail" Member="PortsLogisticsQuoteDetails">
    <Type Name="PortsLogisticsQuoteDetail">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Organization" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ContactNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Service" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Details" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FormType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PageInfo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FormSubmitOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>