<?xml version="1.0" encoding="utf-8"?><Database Class="AffordablePaymentHistoryDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.PaymentHistory" Member="PaymentHistories">
    <Type Name="PaymentHistory">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AccountNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OrderId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Amount" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RequestTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Checksumkey" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CurrencyType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GatewayType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="msg" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AdvanceAmmount" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PaymentType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TransactionId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Responsecode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ResponseTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PaymentRef" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ResponseMsg" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PaymentMode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Created_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Modified_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ISU_UPDATE_FLAG" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="ISU_UPDATE_DATETIME" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ISU_UPDATE_MESSAGE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>