<?xml version="1.0" encoding="utf-8"?><Database Name="Realty" Class="EnterprisesContactFormRecordDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=tcp:adanistaging-sql.database.windows.net;Initial Catalog=Realty;User ID=sitecore" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="RealtyConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.EnterprisesContactFormRecord" Member="EnterprisesContactFormRecords">
    <Type Name="EnterprisesContactFormRecord">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="MessageType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FormType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PageInfo" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FormSubmitOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>