<?xml version="1.0" encoding="utf-8"?><Database Name="Adanisolar" Class="AdaniSolarDownloadHistoryDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=ASUDP-SITECORE1;Initial Catalog=Adanisolar;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="AdanisolarConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AdaniSolarDownloadHistory" Member="AdaniSolarDownloadHistories">
    <Type Name="AdaniSolarDownloadHistory">
      <Column Name="Auto_number" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Invoice_Number" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Invoice_Date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Pallet_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Module_Serial_Number" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Warranty_valid_till" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Currentdate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CurrentTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>