<?xml version="1.0" encoding="utf-8"?><Database Name="Adanisolar" Class="AdaniSolarOTPHistoryDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=ASUDP-SITECORE1;Initial Catalog=Adanisolar;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="AdanisolarConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AdaniSolarOTPHistory" Member="AdaniSolarOTPHistories">
    <Type Name="AdaniSolarOTPHistory">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OTPType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OTPFor" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="OTP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="attempt" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>