<?xml version="1.0" encoding="utf-8"?><Database Name="Realty" Class="GyaanGalaxyDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=tcp:adanistaging-sql.database.windows.net;Initial Catalog=Realty;User ID=Sitecore" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="RealtyConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.GyaanGalaxyContactUs" Member="GyaanGalaxyContactUs">
    <Type Name="GyaanGalaxyContactUs">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="MessageType" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="MobileNo" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="PageInfo" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FormType" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FormSubmitOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SubmittedBy" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.GyannGalaxyRegistrationForm" Member="GyannGalaxyRegistrationForms">
    <Type Name="GyannGalaxyRegistrationForm">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RegistrationNo" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="StudentName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Age" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="MobileNo" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ClassGrade" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="HouseAddress" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SchoolName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SchoolAddress" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FormSubmitOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PageInfo" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FormType" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SubmittedBy" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.GyaanGalaxySubmissionForm" Member="GyaanGalaxySubmissionForms">
    <Type Name="GyaanGalaxySubmissionForm">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RegistrationNo" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Age" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SchoolName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="MobileNo" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="HouseAddress" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SchoolAddress" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ClassOrGrade" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CategoryOfProject" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TitleOfProject" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="EmailID" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Purpose" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="[Procedure]" Member="Procedure" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NatureDataCollection" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Conclusions" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PossibleResearchApplication" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UploadResearchPaper" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="UploadResearchLink" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="UploadedFileType" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UploadedFileName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FormSubmitOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PageInfo" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FormType" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SubmittedBy" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
</Database>