<?xml version="1.0" encoding="utf-8"?><Database Name="ElectricityTender" Class="TenderDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=ElectricityTender;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ElectricityTenderConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TenderDocument" Member="TenderDocuments">
    <Type Name="TenderDocument">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenderId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DocumentPath" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Created_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Modified_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="TenderList_TenderDocument" Member="TenderList" ThisKey="TenderId" OtherKey="Id" Type="TenderList" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserTenderMapping" Member="UserTenderMappings">
    <Type Name="UserTenderMapping">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="TenderId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Envelope" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Corrigendum" Member="Corrigendums">
    <Type Name="Corrigendum">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Created_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Modified_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Corrigendum_CorrigendumDocument" Member="CorrigendumDocuments" ThisKey="Id" OtherKey="CorrigendumId" Type="CorrigendumDocument" />
      <Association Name="Corrigendum_CorrigendumTenderMapping" Member="CorrigendumTenderMappings" ThisKey="Id" OtherKey="CorrigendumId" Type="CorrigendumTenderMapping" />
    </Type>
  </Table>
  <Table Name="dbo.CorrigendumDocument" Member="CorrigendumDocuments">
    <Type Name="CorrigendumDocument">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CorrigendumId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DocumentPath" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Created_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Modified_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Corrigendum_CorrigendumDocument" Member="Corrigendum" ThisKey="CorrigendumId" OtherKey="Id" Type="Corrigendum" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CorrigendumTenderMapping" Member="CorrigendumTenderMappings">
    <Type Name="CorrigendumTenderMapping">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CorrigendumId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="TenderId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Created_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Modified_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Corrigendum_CorrigendumTenderMapping" Member="Corrigendum" ThisKey="CorrigendumId" OtherKey="Id" Type="Corrigendum" IsForeignKey="true" />
      <Association Name="TenderList_CorrigendumTenderMapping" Member="TenderList" ThisKey="TenderId" OtherKey="Id" Type="TenderList" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PaymentHistory" Member="PaymentHistories">
    <Type Name="PaymentHistory">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AccountNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OrderId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Amount" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RequestTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Checksumkey" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CurrencyType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GatewayType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="msg" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AdvanceAmmount" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PaymentType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TransactionId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Responsecode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ResponseTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PaymentRef" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ResponseMsg" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PaymentMode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Created_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Modified_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserProfile" Member="UserProfiles">
    <Type Name="UserProfile">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="AccountNumber" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="MeterNumber" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="IsPrimary" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Created_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Modified_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SolarApplicationVendorList" Member="SolarApplicationVendorLists">
    <Type Name="SolarApplicationVendorList">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NameOfVendorAgency" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="District" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="ContactName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="EmailAddress" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MobileNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PublicMobileNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="STDLandlineNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="STDFaxNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="WebsiteAddress" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PANNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RatingAgency" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RatingReceived" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ApprovedRate" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="VendorCode" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.District" Member="Districts">
    <Type Name="District">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(10,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StateID" Type="System.Decimal" DbType="Decimal(10,0)" CanBeNull="true" />
      <Column Name="DistrictName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Association Name="State_District" Member="State" ThisKey="StateID" OtherKey="ID" Type="State" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.State" Member="States">
    <Type Name="State">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(10,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StateName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Association Name="State_District" Member="Districts" ThisKey="ID" OtherKey="StateID" Type="District" />
    </Type>
  </Table>
  <Table Name="dbo.TenderList" Member="TenderLists">
    <Type Name="TenderList">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NITNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Business" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Adv_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Closing_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Estimated_Cost" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Cost_of_EMD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Staus" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Created_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Modified_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsReminderMailSent" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsCloseEmailSent" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="OnHold" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BuyerName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BuyerEmailId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LeadBuyerName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LeadBuyerEmailId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserEmailId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="TenderList_TenderDocument" Member="TenderDocuments" ThisKey="Id" OtherKey="TenderId" Type="TenderDocument" />
      <Association Name="TenderList_CorrigendumTenderMapping" Member="CorrigendumTenderMappings" ThisKey="Id" OtherKey="TenderId" Type="CorrigendumTenderMapping" />
      <Association Name="TenderList_TenderUserFeeEMDDetail" Member="TenderUserFeeEMDDetails" ThisKey="Id" OtherKey="TenderId" Type="TenderUserFeeEMDDetail" />
      <Association Name="TenderList_Registration" Member="Registrations" ThisKey="Id" OtherKey="TenderId" Type="Registration" />
    </Type>
  </Table>
  <Table Name="dbo.TenderUserFeeEMDDetails" Member="TenderUserFeeEMDDetails">
    <Type Name="TenderUserFeeEMDDetail">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="TenderId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="CustomerCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PANNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PANDocumentData" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PANDocumentContentType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GSTNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GSTDocumentData" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="GSTDocumentContentType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TenderFeeBankReferenceNo" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TenderFeeDocumentData" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TenderFeeDocumentContentType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TenderFeeModeOfPayment" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TenderFeeAmount" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TenderFeeBankBranch" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TenderFeeDateOfPayment" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EMDBankReferenceNo" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="EMDDocumentData" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="EMDDocumentContentType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EMDModeOfPayment" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EMDFeeAmount" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EMDBankBranch" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EMDDateOfPayment" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsFeePaid" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PANDocumentName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="GSTDocumentName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TenderFeeDocumentName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="EMDDocumentName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="VendorCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="TenderList_TenderUserFeeEMDDetail" Member="TenderList" ThisKey="TenderId" OtherKey="Id" Type="TenderList" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TenderBidderCustomerCodeMaster" Member="TenderBidderCustomerCodeMasters">
    <Type Name="TenderBidderCustomerCodeMaster">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PostalCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PANNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GSTNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="VenderCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CustomerCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.GreenPowerOptIn" Member="GreenPowerOptIns">
    <Type Name="GreenPowerOptIn">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AccountNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MobileNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EmailId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TwitterId" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FacebookId" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="OptInFlagCurrentOrNextBilling" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IPledge" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsPicCaptured" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ImageDate" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ImageName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ImageContentType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ImageLink" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="OptInBillingFrom" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PercentageOptIn" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserFeedbackInteractionData" Member="UserFeedbackInteractionDatas">
    <Type Name="UserFeedbackInteractionData">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FeedbackType" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Source" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Sr_Number" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Overall_Experience" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Attitude_Empathy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Quality" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Process" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Attitude_Disatifaction_Reason" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Quality_Disatifaction_CC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CCC_intraction_with" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Quality_Disatifaction_CCC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Quality_Disatifaction_EMAIL" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Quality_Disatifaction_Digital" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Quality_Disatifaction_BackEnd" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Number_Contacted" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Concerns_addressed" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ease_of_register_concerns" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Informed_alternate_digital_channels" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Recomandation_scale_Adani_Electricity" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[AEML could_be_doing_differently]]]" Member="AEML_could_be_doing_differently_" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="valuable_inputs" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Rate_Adani_Brand" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Timeliness_of_our_services" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Safety_practices" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Rate_Technology_Equipment" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Rate_quality_cable_laying" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Rate_Responsivenes_Adan_Point_of_Contact" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Process_Disatifaction_reason" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Other_Remark" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="IsSavedInSAP" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SAPMessage" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Created_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ITSR_BidderFormDetails" Member="ITSR_BidderFormDetails">
    <Type Name="ITSR_BidderFormDetail">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FormId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="TenderNo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ProposalOwnerName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ProposalOwnerEmail" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BuyerName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="BuyerEmail" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="ITSR_BidderFormDetail_ITSR_BidderFormSubmissions_Document" Member="ITSR_BidderFormSubmissions_Documents" ThisKey="Id" OtherKey="BidderFormDetailsId" Type="ITSR_BidderFormSubmissions_Document" />
    </Type>
  </Table>
  <Table Name="dbo.OTPValidationAEML" Member="OTPValidationAEMLs">
    <Type Name="OTPValidationAEML">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AccountNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MeterNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MobileNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OTP" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PageName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ReferenceNumner" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ITSR_Logins" Member="ITSR_Logins">
    <Type Name="ITSR_Login">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="UserRole" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Created_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Modified_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ITSR_BidderFormSubmissions_Documents" Member="ITSR_BidderFormSubmissions_Documents">
    <Type Name="ITSR_BidderFormSubmissions_Document">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BidderFormDetailsId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="BidderFormSubmissionId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="FormId" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DocumenttypeCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DocumentName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="DocumentData" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="DocumentContentType" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="DocumentDescription" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="ITSR_BidderFormDetail_ITSR_BidderFormSubmissions_Document" Member="ITSR_BidderFormDetail" ThisKey="BidderFormDetailsId" OtherKey="Id" Type="ITSR_BidderFormDetail" IsForeignKey="true" />
      <Association Name="ITSR_BidderFormSubmission_ITSR_BidderFormSubmissions_Document" Member="ITSR_BidderFormSubmission" ThisKey="BidderFormSubmissionId" OtherKey="Id" Type="ITSR_BidderFormSubmission" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ITSR_UserRoles" Member="ITSR_UserRoles">
    <Type Name="ITSR_UserRole">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RoleValue" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SwitchToGreen_ChargingStationRequest" Member="SwitchToGreen_ChargingStationRequests">
    <Type Name="SwitchToGreen_ChargingStationRequest">
      <Column Name="RequestId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RequestType" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EmailId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MobileNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SwitchToGreen_PledgeRequest" Member="SwitchToGreen_PledgeRequests">
    <Type Name="SwitchToGreen_PledgeRequest">
      <Column Name="PledgeId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PledgeType" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="EmailId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MobileNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ZipCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="VehicleType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsSignUp" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FormType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SwitchToGreenPledge_VehicleMaster" Member="SwitchToGreenPledge_VehicleMasters">
    <Type Name="SwitchToGreenPledge_VehicleMaster">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VehicleTypeName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="VehicleTypeCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsIndividualVehicleType" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsGroupVehicleType" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ITSR_BidderFormSubmissions" Member="ITSR_BidderFormSubmissions">
    <Type Name="ITSR_BidderFormSubmission">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MobileNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EmailId" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FormId" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Deviation_if_any" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Acceptance_of_Bill_of_Quantity" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Delivery_Schedule_terms_of_weeks" Type="System.String" DbType="NVarChar(1500)" CanBeNull="true" />
      <Column Name="Site_Visit_done" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Demonstration_of_product" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SPOCPersonName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TenderNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsSubmit" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="ITSR_BidderFormSubmission_ITSR_BidderFormSubmissions_Document" Member="ITSR_BidderFormSubmissions_Documents" ThisKey="Id" OtherKey="BidderFormSubmissionId" Type="ITSR_BidderFormSubmissions_Document" />
    </Type>
  </Table>
  <Table Name="dbo.UserTenderDocument" Member="UserTenderDocuments">
    <Type Name="UserTenderDocument">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="EnvelopeType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DocumentPath" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Created_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Modified_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DocType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="UserTenderDocument_UserTenderDocument" Member="UserTenderDocument2" ThisKey="Id" OtherKey="Id" Type="UserTenderDocument" Cardinality="One" />
      <Association Name="UserTenderDocument_UserTenderDocument" Member="UserTenderDocument1" ThisKey="Id" OtherKey="Id" Type="UserTenderDocument" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Registration" Member="Registrations">
    <Type Name="Registration">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="UserType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TenderId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Created_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Modified_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Fax_No" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsBuyer" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BuyerType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Business" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Category" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="TenderList_Registration" Member="TenderList" ThisKey="TenderId" OtherKey="Id" Type="TenderList" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserLoginSessions" Member="UserLoginSessions">
    <Type Name="UserLoginSession">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SessionId" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
</Database>